// AUTO-GENERATED from research sub-agent corpus (samples-cu.json).
import type { EuSample } from "./types";

export const cuSamples: EuSample[] = [
  {
    "input": "Calle 23 #456 e/ L y M, Vedado, Plaza de la Revolución, La Habana 10400",
    "number": "456",
    "street": "23",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "L y M",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 23 e/ L y M, Plaza de la Revolución, La Habana 10400",
    "street": "23",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "L y M",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Avenida 5ta #7802 e/ 78 y 80, Miramar, Playa, La Habana 11300",
    "number": "7802",
    "street": "5ta",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "78 y 80",
    "postal_code": "11300",
    "city": "Playa",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Neptuno #150 e/ Consulado y Industria, Centro Habana, La Habana 10200",
    "number": "150",
    "street": "Neptuno",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Consulado y Industria",
    "postal_code": "10200",
    "city": "Centro Habana",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Obispo #256 e/ Cuba y Aguiar, Habana Vieja, La Habana 10100",
    "number": "256",
    "street": "Obispo",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Cuba y Aguiar",
    "postal_code": "10100",
    "city": "Habana Vieja",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle San Rafael #62 e/ Águila y Galiano, Centro Habana, La Habana 10200",
    "number": "62",
    "street": "San Rafael",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Águila y Galiano",
    "postal_code": "10200",
    "city": "Centro Habana",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle L #353 e/ 23 y 25, Vedado, Plaza de la Revolución, La Habana 10400",
    "number": "353",
    "street": "L",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "23 y 25",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 42 #514 e/ 5ta y 7ma, Playa, La Habana 11300",
    "number": "514",
    "street": "42",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "5ta y 7ma",
    "postal_code": "11300",
    "city": "Playa",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Avenida 51 #3410 e/ 34 y 36, Marianao, La Habana 11400",
    "number": "3410",
    "street": "51",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "34 y 36",
    "postal_code": "11400",
    "city": "Marianao",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calzada de Diez de Octubre #250 e/ Santa Catalina y San Mariano, Diez de Octubre, La Habana 10500",
    "number": "250",
    "street": "de Diez de Octubre",
    "type": "Calzada",
    "sec_unit_type": "e/",
    "sec_unit_num": "Santa Catalina y San Mariano",
    "postal_code": "10500",
    "city": "Diez de Octubre",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Línea #12 e/ M y N, Vedado, Plaza de la Revolución, La Habana 10400",
    "number": "12",
    "street": "Línea",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "M y N",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 100 #4520 e/ 45 y 47, Boyeros, La Habana 10800",
    "number": "4520",
    "street": "100",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "45 y 47",
    "postal_code": "10800",
    "city": "Boyeros",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Martí #52 entre Céspedes y Maceo, Trinidad, Sancti Spíritus 62600",
    "number": "52",
    "street": "Martí",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Céspedes y Maceo",
    "postal_code": "62600",
    "city": "Trinidad",
    "state": "Sancti Spíritus",
    "country": "CU"
  },
  {
    "input": "Calle Martí #52 entre Céspedes y Maceo, Trinidad, Sancti Spiritus 62600",
    "number": "52",
    "street": "Martí",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Céspedes y Maceo",
    "postal_code": "62600",
    "city": "Trinidad",
    "state": "Sancti Spíritus",
    "country": "CU"
  },
  {
    "input": "Calle Enramadas #302 e/ San Félix y San Pedro, Reparto Sueño, Santiago de Cuba, Santiago de Cuba 90100",
    "number": "302",
    "street": "Enramadas",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "San Félix y San Pedro",
    "postal_code": "90100",
    "city": "Santiago de Cuba",
    "state": "Santiago de Cuba",
    "country": "CU"
  },
  {
    "input": "Calle Heredia #204 e/ Carnicería y Calvario, Santiago de Cuba, Santiago de Cuba 90100",
    "number": "204",
    "street": "Heredia",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Carnicería y Calvario",
    "postal_code": "90100",
    "city": "Santiago de Cuba",
    "state": "Santiago de Cuba",
    "country": "CU"
  },
  {
    "input": "Calle Maceo #45 e/ Martí y Máximo Gómez, Bayamo, Granma 85100",
    "number": "45",
    "street": "Maceo",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Martí y Máximo Gómez",
    "postal_code": "85100",
    "city": "Bayamo",
    "state": "Granma",
    "country": "CU"
  },
  {
    "input": "Calle Independencia #78 e/ Maceo y Martí, Las Tunas, Las Tunas 75100",
    "number": "78",
    "street": "Independencia",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Maceo y Martí",
    "postal_code": "75100",
    "city": "Las Tunas",
    "state": "Las Tunas",
    "country": "CU"
  },
  {
    "input": "Avenida de los Libertadores #120 e/ 20 y 22, Holguín, Holguín 80100",
    "number": "120",
    "street": "de los Libertadores",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "20 y 22",
    "postal_code": "80100",
    "city": "Holguín",
    "state": "Holguín",
    "country": "CU"
  },
  {
    "input": "Avenida de los Libertadores #120 e/ 20 y 22, Holguín, Holguin 80100",
    "number": "120",
    "street": "de los Libertadores",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "20 y 22",
    "postal_code": "80100",
    "city": "Holguín",
    "state": "Holguín",
    "country": "CU"
  },
  {
    "input": "Calle Maceo #33 e/ Independencia y República, Camagüey, Camagüey 70100",
    "number": "33",
    "street": "Maceo",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Independencia y República",
    "postal_code": "70100",
    "city": "Camagüey",
    "state": "Camagüey",
    "country": "CU"
  },
  {
    "input": "Calle Maceo #33 e/ Independencia y República, Camagüey, Camaguey 70100",
    "number": "33",
    "street": "Maceo",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Independencia y República",
    "postal_code": "70100",
    "city": "Camagüey",
    "state": "Camagüey",
    "country": "CU"
  },
  {
    "input": "Calle Martí #90 e/ Colón y Gloria, Santa Clara, Villa Clara 50100",
    "number": "90",
    "street": "Martí",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Colón y Gloria",
    "postal_code": "50100",
    "city": "Santa Clara",
    "state": "Villa Clara",
    "country": "CU"
  },
  {
    "input": "Avenida 54 #3708 e/ 37 y 39, Cienfuegos, Cienfuegos 55100",
    "number": "3708",
    "street": "54",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "37 y 39",
    "postal_code": "55100",
    "city": "Cienfuegos",
    "state": "Cienfuegos",
    "country": "CU"
  },
  {
    "input": "Calle Martí #66 e/ Colón y Maceo, Pinar del Río, Pinar del Río 20100",
    "number": "66",
    "street": "Martí",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Colón y Maceo",
    "postal_code": "20100",
    "city": "Pinar del Río",
    "state": "Pinar del Río",
    "country": "CU"
  },
  {
    "input": "Calle Martí #66 e/ Colón y Maceo, Pinar del Río, Pinar del Rio 20100",
    "number": "66",
    "street": "Martí",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Colón y Maceo",
    "postal_code": "20100",
    "city": "Pinar del Río",
    "state": "Pinar del Río",
    "country": "CU"
  },
  {
    "input": "Calle 24 #105 e/ 1ra y 3ra, Cárdenas, Matanzas 42100",
    "number": "105",
    "street": "24",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "1ra y 3ra",
    "postal_code": "42100",
    "city": "Cárdenas",
    "state": "Matanzas",
    "country": "CU"
  },
  {
    "input": "Calle 83 #4210 e/ 42 y 44, Ciego de Ávila, Ciego de Ávila 65100",
    "number": "4210",
    "street": "83",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "42 y 44",
    "postal_code": "65100",
    "city": "Ciego de Ávila",
    "state": "Ciego de Ávila",
    "country": "CU"
  },
  {
    "input": "Calle 83 #4210 e/ 42 y 44, Ciego de Ávila, Ciego de Avila 65100",
    "number": "4210",
    "street": "83",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "42 y 44",
    "postal_code": "65100",
    "city": "Ciego de Ávila",
    "state": "Ciego de Ávila",
    "country": "CU"
  },
  {
    "input": "Calle Calixto García #20 e/ Martí y Maceo, Guantánamo, Guantánamo 95100",
    "number": "20",
    "street": "Calixto García",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Martí y Maceo",
    "postal_code": "95100",
    "city": "Guantánamo",
    "state": "Guantánamo",
    "country": "CU"
  },
  {
    "input": "Calle Calixto García #20 e/ Martí y Maceo, Guantánamo, Guantanamo 95100",
    "number": "20",
    "street": "Calixto García",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Martí y Maceo",
    "postal_code": "95100",
    "city": "Guantánamo",
    "state": "Guantánamo",
    "country": "CU"
  },
  {
    "input": "Calle 41 #1805 e/ 18 y 20, San José de las Lajas, Mayabeque 33100",
    "number": "1805",
    "street": "41",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "18 y 20",
    "postal_code": "33100",
    "city": "San José de las Lajas",
    "state": "Mayabeque",
    "country": "CU"
  },
  {
    "input": "Calle 3ra #45 e/ 2 y 4, Artemisa, Artemisa 34100",
    "number": "45",
    "street": "3ra",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "2 y 4",
    "postal_code": "34100",
    "city": "Artemisa",
    "state": "Artemisa",
    "country": "CU"
  },
  {
    "input": "Calle 39 #1602 e/ 16 y 18, Nueva Gerona, Isla de la Juventud 25100",
    "number": "1602",
    "street": "39",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "16 y 18",
    "postal_code": "25100",
    "city": "Nueva Gerona",
    "state": "Isla de la Juventud",
    "country": "CU"
  },
  {
    "input": "Calle Sol #12 esq. a Oficios, Habana Vieja, La Habana 10100",
    "number": "12",
    "street": "Sol",
    "type": "Calle",
    "sec_unit_type": "esq",
    "sec_unit_num": "a Oficios",
    "postal_code": "10100",
    "city": "Habana Vieja",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle G #501 e/ 25 y 27, Vedado, Plaza de la Revolución, La Habana",
    "number": "501",
    "street": "G",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "25 y 27",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 12 #305 e/ 3ra y 5ta, Playa, La Habana",
    "number": "305",
    "street": "12",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "3ra y 5ta",
    "city": "Playa",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 17 e/ E y F, Vedado, Plaza de la Revolución, La Habana 10400",
    "street": "17",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "E y F",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Avenida 26 #650 e/ 35 y 37, Nuevo Vedado, Plaza de la Revolución, La Habana 10600",
    "number": "650",
    "street": "26",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "35 y 37",
    "postal_code": "10600",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle 70 #1904 e/ 19 y 21, Marianao, La Habana 11400",
    "number": "1904",
    "street": "70",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "19 y 21",
    "postal_code": "11400",
    "city": "Marianao",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle San Lázaro #660 e/ Belascoaín y Gervasio, Centro Habana, La Habana 10200",
    "number": "660",
    "street": "San Lázaro",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Belascoaín y Gervasio",
    "postal_code": "10200",
    "city": "Centro Habana",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Aguacate #58 e/ Obispo y Obrapía, Habana Vieja, La Habana 10100",
    "number": "58",
    "street": "Aguacate",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Obispo y Obrapía",
    "postal_code": "10100",
    "city": "Habana Vieja",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Calle Céspedes #14 e/ Agramonte y Independencia, Camagüey, Camagüey 70100",
    "number": "14",
    "street": "Céspedes",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Agramonte y Independencia",
    "postal_code": "70100",
    "city": "Camagüey",
    "state": "Camagüey",
    "country": "CU"
  },
  {
    "input": "Calle Máximo Gómez #7 e/ Martí y Maceo, Morón, Ciego de Ávila 67210",
    "number": "7",
    "street": "Máximo Gómez",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Martí y Maceo",
    "postal_code": "67210",
    "city": "Morón",
    "state": "Ciego de Ávila",
    "country": "CU"
  },
  {
    "input": "Apartado Postal 6055, Plaza de la Revolución, La Habana",
    "sec_unit_type": "Apartado Postal",
    "sec_unit_num": "6055",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Apartado 122, Santiago de Cuba, Santiago de Cuba",
    "sec_unit_type": "Apartado Postal",
    "sec_unit_num": "122",
    "city": "Santiago de Cuba",
    "state": "Santiago de Cuba",
    "country": "CU"
  },
  {
    "input": "Calle Aguilera #58 e/ Reloj y Calvario, Santiago de Cuba, Santiago de Cuba 90100",
    "number": "58",
    "street": "Aguilera",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "Reloj y Calvario",
    "postal_code": "90100",
    "city": "Santiago de Cuba",
    "state": "Santiago de Cuba",
    "country": "CU"
  },
  {
    "input": "Calle 19 #802 e/ 8 y 10, Vedado, Plaza de la Revolución, La Habana 10400",
    "number": "802",
    "street": "19",
    "type": "Calle",
    "sec_unit_type": "e/",
    "sec_unit_num": "8 y 10",
    "postal_code": "10400",
    "city": "Plaza de la Revolución",
    "state": "La Habana",
    "country": "CU"
  },
  {
    "input": "Avenida Carlos Manuel de Céspedes #14 e/ 1ra y 3ra, Bayamo, Granma 85100",
    "number": "14",
    "street": "Carlos Manuel de Céspedes",
    "type": "Avenida",
    "sec_unit_type": "e/",
    "sec_unit_num": "1ra y 3ra",
    "postal_code": "85100",
    "city": "Bayamo",
    "state": "Granma",
    "country": "CU"
  },
  {
    "input": "Calle 10 #5, Reparto Sueño, Santiago de Cuba, Santiago de Cuba 90400",
    "__skip": "reparto without cross-street cannot be dropped (no 'e/' anchor)"
  },
  {
    "input": "Reparto Antonio Maceo, Manzana 7, Casa 12, Santiago de Cuba",
    "__skip": "reparto/manzana/casa leading chain not modelled"
  },
  {
    "input": "Edificio 12, Apto 4, Zona 6, Alamar, Habana del Este, La Habana",
    "__skip": "housing-block edificio/apto/zona micro-district chain not modelled"
  },
  {
    "input": "Calle 23 e/ L y M, Vedado, La Habana",
    "__skip": "reparto+province only (no municipio) ambiguous; province would be read as city"
  },
  {
    "input": "Carretera Central Km 12, Reparto Buenos Aires, Santiago de Cuba",
    "__skip": "km highway + reparto descriptive form"
  },
  {
    "input": "Finca La Esperanza, Guasimal, Sancti Spíritus",
    "__skip": "rural finca/paraje locality not modelled"
  },
  {
    "input": "Calle 5ta esquina a 42, Miramar, Playa, La Habana",
    "__skip": "esquina-only cross reference with reparto ambiguity"
  },
  {
    "input": "Reparto Flores, Calle Segunda #3, Boyeros, La Habana",
    "__skip": "reparto-leading order not modelled"
  }
];
