// AUTO-GENERATED from research sub-agent corpus (samples-dk.json).
// Ground-truth field breakdowns for DK addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const dkSamples: EuSample[] = [
  {
    "input": "Nørregade 12, 1165 København",
    "number": "12",
    "street": "Nørre",
    "type": "gade",
    "postal_code": "1165",
    "city": "København",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Vestergade 3, 1456 København K",
    "number": "3",
    "street": "Vester",
    "type": "gade",
    "postal_code": "1456",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade; district letter K"
  },
  {
    "input": "Istedgade 44, 1650 København V",
    "number": "44",
    "street": "Isted",
    "type": "gade",
    "postal_code": "1650",
    "city": "København V",
    "country": "DK",
    "notes": "fused -gade; Vesterbro"
  },
  {
    "input": "Gothersgade 101, 1123 København K",
    "number": "101",
    "street": "Gothers",
    "type": "gade",
    "postal_code": "1123",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Landemærket 8, 1119 København K",
    "number": "8",
    "street": "Landemærket",
    "postal_code": "1119",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable; -et definite terrain name"
  },
  {
    "input": "Larsbjørnsstræde 9, 1454 København K",
    "number": "9",
    "street": "Larsbjørns",
    "type": "stræde",
    "postal_code": "1454",
    "city": "København K",
    "country": "DK",
    "notes": "fused -stræde"
  },
  {
    "input": "Læderstræde 15, 1201 København K",
    "number": "15",
    "street": "Læder",
    "type": "stræde",
    "postal_code": "1201",
    "city": "København K",
    "country": "DK",
    "notes": "fused -stræde; æ"
  },
  {
    "input": "Pilestræde 40, 1112 København K",
    "number": "40",
    "street": "Pile",
    "type": "stræde",
    "postal_code": "1112",
    "city": "København K",
    "country": "DK",
    "notes": "fused -stræde"
  },
  {
    "input": "Grønnegade 10, 1107 København K",
    "number": "10",
    "street": "Grønne",
    "type": "gade",
    "postal_code": "1107",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade; ø"
  },
  {
    "input": "Store Kongensgade 40, 1264 København K",
    "number": "40",
    "street": "Store Kongens",
    "type": "gade",
    "postal_code": "1264",
    "city": "København K",
    "country": "DK",
    "notes": "multi-word name, Store spaced, gade fused"
  },
  {
    "input": "Bredgade 25, 1260 København K",
    "number": "25",
    "street": "Bred",
    "type": "gade",
    "postal_code": "1260",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Adelgade 5, 1304 København K",
    "number": "5",
    "street": "Adel",
    "type": "gade",
    "postal_code": "1304",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Borgergade 14, 1300 København K",
    "number": "14",
    "street": "Borger",
    "type": "gade",
    "postal_code": "1300",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Klerkegade 19, 1308 København K",
    "number": "19",
    "street": "Klerke",
    "type": "gade",
    "postal_code": "1308",
    "city": "København K",
    "country": "DK",
    "notes": "fused -gade"
  },
  {
    "input": "Blågårdsgade 7, 2200 København N",
    "number": "7",
    "street": "Blågårds",
    "type": "gade",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "fused -gade; å; district N"
  },
  {
    "input": "Enghavevej 80, 2450 København SV",
    "number": "80",
    "street": "Enghave",
    "type": "vej",
    "postal_code": "2450",
    "city": "København SV",
    "country": "DK",
    "notes": "fused -vej; district SV"
  },
  {
    "input": "Strandvejen 100, 2900 Hellerup",
    "number": "100",
    "street": "Strand",
    "type": "vejen",
    "postal_code": "2900",
    "city": "Hellerup",
    "country": "DK",
    "notes": "fused -vejen definite"
  },
  {
    "input": "Amagerbrogade 50, 2300 København S",
    "number": "50",
    "street": "Amagerbro",
    "type": "gade",
    "postal_code": "2300",
    "city": "København S",
    "country": "DK",
    "notes": "fused -brogade; district S"
  },
  {
    "input": "Gammel Kongevej 60, 1850 Frederiksberg C",
    "number": "60",
    "street": "Gammel Konge",
    "type": "vej",
    "postal_code": "1850",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "multi-word; Gammel spaced, vej fused"
  },
  {
    "input": "Tagensvej 15, 2200 København N",
    "number": "15",
    "street": "Tagens",
    "type": "vej",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "fused -vej"
  },
  {
    "input": "Jagtvej 120, 2200 København N",
    "number": "120",
    "street": "Jagt",
    "type": "vej",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "fused -vej"
  },
  {
    "input": "Lyngbyvej 20, 2100 København Ø",
    "number": "20",
    "street": "Lyngby",
    "type": "vej",
    "postal_code": "2100",
    "city": "København Ø",
    "country": "DK",
    "notes": "fused -vej; district Ø"
  },
  {
    "input": "Roskildevej 200, 2500 Valby",
    "number": "200",
    "street": "Roskilde",
    "type": "vej",
    "postal_code": "2500",
    "city": "Valby",
    "country": "DK",
    "notes": "fused -vej"
  },
  {
    "input": "Frederikssundsvej 90, 2400 København NV",
    "number": "90",
    "street": "Frederikssunds",
    "type": "vej",
    "postal_code": "2400",
    "city": "København NV",
    "country": "DK",
    "notes": "fused -vej; district NV"
  },
  {
    "input": "Vesterbrogade 4, 1620 København V",
    "number": "4",
    "street": "Vesterbro",
    "type": "gade",
    "postal_code": "1620",
    "city": "København V",
    "country": "DK",
    "notes": "fused -brogade"
  },
  {
    "input": "Nørrebrogade 66, 2200 København N",
    "number": "66",
    "street": "Nørrebro",
    "type": "gade",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "fused -brogade; ø"
  },
  {
    "input": "Østerbrogade 105, 2100 København Ø",
    "number": "105",
    "street": "Østerbro",
    "type": "gade",
    "postal_code": "2100",
    "city": "København Ø",
    "country": "DK",
    "notes": "fused -brogade; Ø"
  },
  {
    "input": "Falkoner Allé 7, 2000 Frederiksberg",
    "number": "7",
    "street": "Falkoner",
    "type": "allé",
    "postal_code": "2000",
    "city": "Frederiksberg",
    "country": "DK",
    "notes": "spaced type Allé; é"
  },
  {
    "input": "Frederiksberg Allé 22, 1820 Frederiksberg C",
    "number": "22",
    "street": "Frederiksberg",
    "type": "allé",
    "postal_code": "1820",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "spaced type Allé"
  },
  {
    "input": "Nørre Allé 45, 2200 København N",
    "number": "45",
    "street": "Nørre",
    "type": "allé",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "spaced type Allé"
  },
  {
    "input": "Amagertorv 6, 1160 København K",
    "number": "6",
    "street": "Amagertorv",
    "postal_code": "1160",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable per research; keep whole"
  },
  {
    "input": "Kultorvet 11, 1175 København K",
    "number": "11",
    "street": "Kul",
    "type": "torvet",
    "postal_code": "1175",
    "city": "København K",
    "country": "DK",
    "notes": "fused -torvet definite"
  },
  {
    "input": "Nytorv 3, 1450 København K",
    "number": "3",
    "street": "Ny",
    "type": "torv",
    "postal_code": "1450",
    "city": "København K",
    "country": "DK",
    "notes": "fused -torv"
  },
  {
    "input": "Gammeltorv 8, 1457 København K",
    "number": "8",
    "street": "Gammel",
    "type": "torv",
    "postal_code": "1457",
    "city": "København K",
    "country": "DK",
    "notes": "fused -torv"
  },
  {
    "input": "Kongens Nytorv 13, 1050 København K",
    "number": "13",
    "street": "Kongens Ny",
    "type": "torv",
    "postal_code": "1050",
    "city": "København K",
    "country": "DK",
    "notes": "multi-word; Ny+torv fused"
  },
  {
    "input": "Rådhuspladsen 1, 1550 København V",
    "number": "1",
    "street": "Rådhus",
    "type": "pladsen",
    "postal_code": "1550",
    "city": "København V",
    "country": "DK",
    "notes": "fused -pladsen; å"
  },
  {
    "input": "Højbro Plads 10, 1200 København K",
    "number": "10",
    "street": "Højbro",
    "type": "plads",
    "postal_code": "1200",
    "city": "København K",
    "country": "DK",
    "notes": "spaced Plads; Højbro proper name"
  },
  {
    "input": "Sankt Hans Torv 30, 2200 København N",
    "number": "30",
    "street": "Sankt Hans",
    "type": "torv",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "Sankt name; spaced Torv"
  },
  {
    "input": "Sankt Annæ Plads 12, 1250 København K",
    "number": "12",
    "street": "Sankt Annæ",
    "type": "plads",
    "postal_code": "1250",
    "city": "København K",
    "country": "DK",
    "notes": "Sankt name; spaced Plads; æ"
  },
  {
    "input": "Israels Plads 5, 1357 København K",
    "number": "5",
    "street": "Israels",
    "type": "plads",
    "postal_code": "1357",
    "city": "København K",
    "country": "DK",
    "notes": "spaced Plads"
  },
  {
    "input": "Åboulevarden 1, 1635 København V",
    "number": "1",
    "street": "Å",
    "type": "boulevarden",
    "postal_code": "1635",
    "city": "København V",
    "country": "DK",
    "notes": "fused -boulevarden; Å"
  },
  {
    "input": "H.C. Andersens Boulevard 18, 1553 København V",
    "number": "18",
    "street": "H.C. Andersens",
    "type": "boulevard",
    "postal_code": "1553",
    "city": "København V",
    "country": "DK",
    "notes": "spaced Boulevard; initials"
  },
  {
    "input": "Sønder Boulevard 60, 1720 København V",
    "number": "60",
    "street": "Sønder",
    "type": "boulevard",
    "postal_code": "1720",
    "city": "København V",
    "country": "DK",
    "notes": "spaced Boulevard"
  },
  {
    "input": "Åboulevarden 22, 8000 Aarhus C",
    "number": "22",
    "street": "Å",
    "type": "boulevarden",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "fused -boulevarden; Aarhus"
  },
  {
    "input": "Sankt Peders Stræde 28, 1453 København K",
    "number": "28",
    "street": "Sankt Peders",
    "type": "stræde",
    "postal_code": "1453",
    "city": "København K",
    "country": "DK",
    "notes": "Sankt name; spaced Stræde"
  },
  {
    "input": "Sankt Pauls Gade 20, 1313 København K",
    "number": "20",
    "street": "Sankt Pauls",
    "type": "gade",
    "postal_code": "1313",
    "city": "København K",
    "country": "DK",
    "notes": "Sankt name; spaced Gade"
  },
  {
    "input": "Skt. Clemens Torv 8, 8000 Aarhus C",
    "number": "8",
    "street": "Skt. Clemens",
    "type": "torv",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Skt. abbrev; spaced Torv"
  },
  {
    "input": "Vester Voldgade 90, 1552 København V",
    "number": "90",
    "street": "Vester Vold",
    "type": "gade",
    "postal_code": "1552",
    "city": "København V",
    "country": "DK",
    "notes": "Vester spaced, Vold+gade fused"
  },
  {
    "input": "Nørre Voldgade 21, 1358 København K",
    "number": "21",
    "street": "Nørre Vold",
    "type": "gade",
    "postal_code": "1358",
    "city": "København K",
    "country": "DK",
    "notes": "Nørre spaced, Vold+gade fused"
  },
  {
    "input": "Øster Voldgade 10, 1350 København K",
    "number": "10",
    "street": "Øster Vold",
    "type": "gade",
    "postal_code": "1350",
    "city": "København K",
    "country": "DK",
    "notes": "Øster spaced, Vold+gade fused"
  },
  {
    "input": "Nordre Frihavnsgade 55, 2100 København Ø",
    "number": "55",
    "street": "Nordre Frihavns",
    "type": "gade",
    "postal_code": "2100",
    "city": "København Ø",
    "country": "DK",
    "notes": "multi-word; gade fused"
  },
  {
    "input": "Strøget 5, 1160 København K",
    "number": "5",
    "street": "Strøget",
    "postal_code": "1160",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable pedestrian street"
  },
  {
    "input": "Nyhavn 17, 1051 København K",
    "number": "17",
    "street": "Nyhavn",
    "postal_code": "1051",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable; Ny+havn kept whole"
  },
  {
    "input": "Islands Brygge 25, 2300 København S",
    "number": "25",
    "street": "Islands Brygge",
    "postal_code": "2300",
    "city": "København S",
    "country": "DK",
    "notes": "brygge wharf; kept whole"
  },
  {
    "input": "Christianshavn 2, 1440 København K",
    "number": "2",
    "street": "Christianshavn",
    "postal_code": "1440",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable proper name"
  },
  {
    "input": "Sluseholmen 14, 2450 København SV",
    "number": "14",
    "street": "Sluse",
    "type": "holmen",
    "postal_code": "2450",
    "city": "København SV",
    "country": "DK",
    "notes": "fused -holmen terrain type"
  },
  {
    "input": "Nørregade 12, 3. tv, 1165 København K",
    "number": "12",
    "street": "Nørre",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "3. tv",
    "postal_code": "1165",
    "city": "København K",
    "country": "DK",
    "notes": "floor+left tv"
  },
  {
    "input": "Istedgade 44, 2. th, 1650 København V",
    "number": "44",
    "street": "Isted",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "2. th",
    "postal_code": "1650",
    "city": "København V",
    "country": "DK",
    "notes": "floor+right th"
  },
  {
    "input": "Vesterbrogade 4, st. tv, 1620 København V",
    "number": "4",
    "street": "Vesterbro",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "st. tv",
    "postal_code": "1620",
    "city": "København V",
    "country": "DK",
    "notes": "ground floor left"
  },
  {
    "input": "Gothersgade 101, 4. mf, 1123 København K",
    "number": "101",
    "street": "Gothers",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "4. mf",
    "postal_code": "1123",
    "city": "København K",
    "country": "DK",
    "notes": "floor+middle mf"
  },
  {
    "input": "Blågårdsgade 7, st., 2200 København N",
    "number": "7",
    "street": "Blågårds",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "st.",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "bare ground floor st."
  },
  {
    "input": "Amagerbrogade 50, 1. sal, 2300 København S",
    "number": "50",
    "street": "Amagerbro",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "1. sal",
    "postal_code": "2300",
    "city": "København S",
    "country": "DK",
    "notes": "1st floor spelled sal"
  },
  {
    "input": "Jagtvej 120, 5. th, 2200 København N",
    "number": "120",
    "street": "Jagt",
    "type": "vej",
    "sec_unit_type": "sal",
    "sec_unit_num": "5. th",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "high floor right"
  },
  {
    "input": "Tagensvej 15, st. th, 2200 København N",
    "number": "15",
    "street": "Tagens",
    "type": "vej",
    "sec_unit_type": "sal",
    "sec_unit_num": "st. th",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "ground floor right"
  },
  {
    "input": "Nørrebrogade 66, 3. tv, 2200 København N",
    "number": "66",
    "street": "Nørrebro",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "3. tv",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "floor left"
  },
  {
    "input": "Østerbrogade 105, 2. tv, 2100 København Ø",
    "number": "105",
    "street": "Østerbro",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "2. tv",
    "postal_code": "2100",
    "city": "København Ø",
    "country": "DK",
    "notes": "floor left"
  },
  {
    "input": "Frederiksberg Allé 22, 4. tv, 1820 Frederiksberg C",
    "number": "22",
    "street": "Frederiksberg",
    "type": "allé",
    "sec_unit_type": "sal",
    "sec_unit_num": "4. tv",
    "postal_code": "1820",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "spaced Allé + floor"
  },
  {
    "input": "Bredgade 25, 1. mf, 1260 København K",
    "number": "25",
    "street": "Bred",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "1. mf",
    "postal_code": "1260",
    "city": "København K",
    "country": "DK",
    "notes": "floor middle"
  },
  {
    "input": "Nørregade 12A, 1165 København K",
    "number": "12",
    "civic_number_suffix": "A",
    "street": "Nørre",
    "type": "gade",
    "postal_code": "1165",
    "city": "København K",
    "country": "DK",
    "notes": "letter suffix A on husnr"
  },
  {
    "input": "Istedgade 34B, 1650 København V",
    "number": "34",
    "civic_number_suffix": "B",
    "street": "Isted",
    "type": "gade",
    "postal_code": "1650",
    "city": "København V",
    "country": "DK",
    "notes": "letter suffix B"
  },
  {
    "input": "Vestergade 7C, 1456 København K",
    "number": "7",
    "civic_number_suffix": "C",
    "street": "Vester",
    "type": "gade",
    "postal_code": "1456",
    "city": "København K",
    "country": "DK",
    "notes": "letter suffix C"
  },
  {
    "input": "Strandvejen 100A, 2. th, 2900 Hellerup",
    "number": "100",
    "civic_number_suffix": "A",
    "street": "Strand",
    "type": "vejen",
    "sec_unit_type": "sal",
    "sec_unit_num": "2. th",
    "postal_code": "2900",
    "city": "Hellerup",
    "country": "DK",
    "notes": "letter suffix + floor"
  },
  {
    "input": "Bredgade 25B, 1260 København K",
    "number": "25",
    "civic_number_suffix": "B",
    "street": "Bred",
    "type": "gade",
    "postal_code": "1260",
    "city": "København K",
    "country": "DK",
    "notes": "letter suffix B"
  },
  {
    "input": "Jagtvej 227D, 2100 København Ø",
    "number": "227",
    "civic_number_suffix": "D",
    "street": "Jagt",
    "type": "vej",
    "postal_code": "2100",
    "city": "København Ø",
    "country": "DK",
    "notes": "letter suffix D"
  },
  {
    "input": "Gothersgade 12-14, 1123 København K",
    "number": "12",
    "civic_number_suffix": "-14",
    "street": "Gothers",
    "type": "gade",
    "postal_code": "1123",
    "city": "København K",
    "country": "DK",
    "notes": "house-number range"
  },
  {
    "input": "Vesterbrogade 10-16, 1620 København V",
    "number": "10",
    "civic_number_suffix": "-16",
    "street": "Vesterbro",
    "type": "gade",
    "postal_code": "1620",
    "city": "København V",
    "country": "DK",
    "notes": "house-number range"
  },
  {
    "input": "Amagerbrogade 30-32, 2300 København S",
    "number": "30",
    "civic_number_suffix": "-32",
    "street": "Amagerbro",
    "type": "gade",
    "postal_code": "2300",
    "city": "København S",
    "country": "DK",
    "notes": "house-number range"
  },
  {
    "input": "Store Kongensgade 40-44, 1264 København K",
    "number": "40",
    "civic_number_suffix": "-44",
    "street": "Store Kongens",
    "type": "gade",
    "postal_code": "1264",
    "city": "København K",
    "country": "DK",
    "notes": "range + multi-word"
  },
  {
    "input": "Rosenvænget 5, 4000 Roskilde",
    "number": "5",
    "street": "Rosen",
    "type": "vænget",
    "postal_code": "4000",
    "city": "Roskilde",
    "country": "DK",
    "notes": "fused -vænget definite; æ"
  },
  {
    "input": "Birkevænget 12, 2800 Kongens Lyngby",
    "number": "12",
    "street": "Birke",
    "type": "vænget",
    "postal_code": "2800",
    "city": "Kongens Lyngby",
    "country": "DK",
    "notes": "fused -vænget"
  },
  {
    "input": "Egeparken 8, 5000 Odense C",
    "number": "8",
    "street": "Ege",
    "type": "parken",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "fused -parken definite"
  },
  {
    "input": "Æblehaven 3, 8200 Aarhus N",
    "number": "3",
    "street": "Æble",
    "type": "haven",
    "postal_code": "8200",
    "city": "Aarhus N",
    "country": "DK",
    "notes": "fused -haven definite; Æ"
  },
  {
    "input": "Solbakken 14, 8210 Aarhus V",
    "number": "14",
    "street": "Sol",
    "type": "bakken",
    "postal_code": "8210",
    "city": "Aarhus V",
    "country": "DK",
    "notes": "fused -bakken terrain type"
  },
  {
    "input": "Kastanie Allé 6, 5000 Odense C",
    "number": "6",
    "street": "Kastanie",
    "type": "allé",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "spaced Allé"
  },
  {
    "input": "Søndergade 5, 8000 Aarhus C",
    "number": "5",
    "street": "Sønder",
    "type": "gade",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; fused -gade"
  },
  {
    "input": "Store Torv 4, 8000 Aarhus C",
    "number": "4",
    "street": "Store",
    "type": "torv",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "spaced Torv; Aarhus"
  },
  {
    "input": "Vestergade 58, 8000 Aarhus C",
    "number": "58",
    "street": "Vester",
    "type": "gade",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; fused -gade"
  },
  {
    "input": "Frederiks Allé 30, 8000 Aarhus C",
    "number": "30",
    "street": "Frederiks",
    "type": "allé",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "spaced Allé; Aarhus"
  },
  {
    "input": "Ryesgade 3, 8000 Aarhus C",
    "number": "3",
    "street": "Ryes",
    "type": "gade",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; fused -gade"
  },
  {
    "input": "Silkeborgvej 100, 8000 Aarhus C",
    "number": "100",
    "street": "Silkeborg",
    "type": "vej",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; fused -vej"
  },
  {
    "input": "Mejlgade 35, 8000 Aarhus C",
    "number": "35",
    "street": "Mejl",
    "type": "gade",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; fused -gade"
  },
  {
    "input": "Banegårdsgade 12, 8000 Aarhus C",
    "number": "12",
    "street": "Banegårds",
    "type": "gade",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "Aarhus; å; fused -gade"
  },
  {
    "input": "Marselisborg Allé 5, 8000 Aarhus C",
    "number": "5",
    "street": "Marselisborg",
    "type": "allé",
    "postal_code": "8000",
    "city": "Aarhus C",
    "country": "DK",
    "notes": "spaced Allé"
  },
  {
    "input": "Vestergade 70, 5000 Odense C",
    "number": "70",
    "street": "Vester",
    "type": "gade",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "Odense; fused -gade"
  },
  {
    "input": "Kongensgade 40, 5000 Odense C",
    "number": "40",
    "street": "Kongens",
    "type": "gade",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "Odense; fused -gade"
  },
  {
    "input": "Overgade 15, 5000 Odense C",
    "number": "15",
    "street": "Over",
    "type": "gade",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "Odense; fused -gade"
  },
  {
    "input": "Hans Jensens Stræde 37, 5000 Odense C",
    "number": "37",
    "street": "Hans Jensens",
    "type": "stræde",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "spaced Stræde; Andersen area"
  },
  {
    "input": "Nyborgvej 22, 5000 Odense C",
    "number": "22",
    "street": "Nyborg",
    "type": "vej",
    "postal_code": "5000",
    "city": "Odense C",
    "country": "DK",
    "notes": "Odense; fused -vej"
  },
  {
    "input": "Middelfartvej 8, 5200 Odense V",
    "number": "8",
    "street": "Middelfart",
    "type": "vej",
    "postal_code": "5200",
    "city": "Odense V",
    "country": "DK",
    "notes": "Odense; fused -vej"
  },
  {
    "input": "Boulevarden 40, 9000 Aalborg",
    "number": "40",
    "street": "Boulevarden",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "unsplittable; the whole name IS the type"
  },
  {
    "input": "Bispensgade 12, 9000 Aalborg",
    "number": "12",
    "street": "Bispens",
    "type": "gade",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "Aalborg; fused -gade"
  },
  {
    "input": "Vesterbro 77, 9000 Aalborg",
    "number": "77",
    "street": "Vesterbro",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "unsplittable proper name; Aalborg"
  },
  {
    "input": "Hasserisgade 5, 9000 Aalborg",
    "number": "5",
    "street": "Hasseris",
    "type": "gade",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "Aalborg; fused -gade"
  },
  {
    "input": "Nytorv 9, 9000 Aalborg",
    "number": "9",
    "street": "Ny",
    "type": "torv",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "Aalborg; fused -torv"
  },
  {
    "input": "Hobrovej 50, 9000 Aalborg",
    "number": "50",
    "street": "Hobro",
    "type": "vej",
    "postal_code": "9000",
    "city": "Aalborg",
    "country": "DK",
    "notes": "Aalborg; fused -vej"
  },
  {
    "input": "Torvegade 8, 6700 Esbjerg",
    "number": "8",
    "street": "Torve",
    "type": "gade",
    "postal_code": "6700",
    "city": "Esbjerg",
    "country": "DK",
    "notes": "Esbjerg; fused -gade"
  },
  {
    "input": "Kongensgade 60, 6700 Esbjerg",
    "number": "60",
    "street": "Kongens",
    "type": "gade",
    "postal_code": "6700",
    "city": "Esbjerg",
    "country": "DK",
    "notes": "Esbjerg; fused -gade"
  },
  {
    "input": "Jernbanegade 5, 4000 Roskilde",
    "number": "5",
    "street": "Jernbane",
    "type": "gade",
    "postal_code": "4000",
    "city": "Roskilde",
    "country": "DK",
    "notes": "Roskilde; fused -gade"
  },
  {
    "input": "Algade 31, 4000 Roskilde",
    "number": "31",
    "street": "Al",
    "type": "gade",
    "postal_code": "4000",
    "city": "Roskilde",
    "country": "DK",
    "notes": "Roskilde; fused -gade"
  },
  {
    "input": "Slotsgade 20, 3400 Hillerød",
    "number": "20",
    "street": "Slots",
    "type": "gade",
    "postal_code": "3400",
    "city": "Hillerød",
    "country": "DK",
    "notes": "Hillerød; fused -gade; ø"
  },
  {
    "input": "Kongevejen 15, 2840 Holte",
    "number": "15",
    "street": "Konge",
    "type": "vejen",
    "postal_code": "2840",
    "city": "Holte",
    "country": "DK",
    "notes": "fused -vejen definite"
  },
  {
    "input": "Havnegade 3, 5500 Middelfart",
    "number": "3",
    "street": "Havne",
    "type": "gade",
    "postal_code": "5500",
    "city": "Middelfart",
    "country": "DK",
    "notes": "Middelfart; fused -gade"
  },
  {
    "input": "Nørregade 22, 7100 Vejle",
    "number": "22",
    "street": "Nørre",
    "type": "gade",
    "postal_code": "7100",
    "city": "Vejle",
    "country": "DK",
    "notes": "Vejle; fused -gade"
  },
  {
    "input": "Søndergade 45, 7400 Herning",
    "number": "45",
    "street": "Sønder",
    "type": "gade",
    "postal_code": "7400",
    "city": "Herning",
    "country": "DK",
    "notes": "Herning; fused -gade"
  },
  {
    "input": "Østergade 18, 6000 Kolding",
    "number": "18",
    "street": "Øster",
    "type": "gade",
    "postal_code": "6000",
    "city": "Kolding",
    "country": "DK",
    "notes": "Kolding; fused -gade; Ø"
  },
  {
    "input": "H.C. Ørsteds Vej 50, 1879 Frederiksberg C",
    "number": "50",
    "street": "H.C. Ørsteds",
    "type": "vej",
    "postal_code": "1879",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "initials; spaced Vej; Ø"
  },
  {
    "input": "N.J. Fjords Allé 3, 1957 Frederiksberg C",
    "number": "3",
    "street": "N.J. Fjords",
    "type": "allé",
    "postal_code": "1957",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "initials; spaced Allé"
  },
  {
    "input": "Nørregade 12, 1165 København, Danmark",
    "number": "12",
    "street": "Nørre",
    "type": "gade",
    "postal_code": "1165",
    "city": "København",
    "country": "DK",
    "notes": "country native Danmark"
  },
  {
    "input": "Strandvejen 100, 2900 Hellerup, Denmark",
    "number": "100",
    "street": "Strand",
    "type": "vejen",
    "postal_code": "2900",
    "city": "Hellerup",
    "country": "DK",
    "notes": "country English Denmark"
  },
  {
    "input": "Vesterbrogade 4, 1620 Copenhagen, DK",
    "number": "4",
    "street": "Vesterbro",
    "type": "gade",
    "postal_code": "1620",
    "city": "Copenhagen",
    "country": "DK",
    "notes": "English exonym Copenhagen; DK"
  },
  {
    "input": "Åboulevarden 22, 8000 Århus C",
    "number": "22",
    "street": "Å",
    "type": "boulevarden",
    "postal_code": "8000",
    "city": "Århus C",
    "country": "DK",
    "notes": "old spelling Århus"
  },
  {
    "input": "Blågårdsgade 7A, 3. tv, 2200 København N",
    "number": "7",
    "civic_number_suffix": "A",
    "street": "Blågårds",
    "type": "gade",
    "sec_unit_type": "sal",
    "sec_unit_num": "3. tv",
    "postal_code": "2200",
    "city": "København N",
    "country": "DK",
    "notes": "letter + floor combo"
  },
  {
    "input": "Gammel Kongevej 60, kld., 1850 Frederiksberg C",
    "__skip": "basement floor marker (kld.) not modelled",
    "number": "60",
    "street": "Gammel Konge",
    "type": "vej",
    "sec_unit_type": "sal",
    "sec_unit_num": "kld.",
    "postal_code": "1850",
    "city": "Frederiksberg C",
    "country": "DK",
    "notes": "basement kld"
  },
  {
    "input": "Enghavevej 80, k1, 2450 København SV",
    "__skip": "basement-level unit (k1) not modelled",
    "number": "80",
    "street": "Enghave",
    "type": "vej",
    "sec_unit_type": "sal",
    "sec_unit_num": "k1",
    "postal_code": "2450",
    "city": "København SV",
    "country": "DK",
    "notes": "basement k1"
  },
  {
    "input": "Pilestræde 40, 2. dør 3, 1112 København K",
    "__skip": "floor + door (dør) stacked unit",
    "number": "40",
    "street": "Pile",
    "type": "stræde",
    "sec_unit_type": "sal",
    "sec_unit_num": "2. dør 3",
    "postal_code": "1112",
    "city": "København K",
    "country": "DK",
    "notes": "numeric door"
  },
  {
    "input": "Nyhavn 17, 1. th, 1051 København K",
    "number": "17",
    "street": "Nyhavn",
    "sec_unit_type": "sal",
    "sec_unit_num": "1. th",
    "postal_code": "1051",
    "city": "København K",
    "country": "DK",
    "notes": "unsplittable + floor"
  }
];
