// AUTO-GENERATED from research sub-agent corpus (samples-es.json).
// Ground-truth field breakdowns for ES addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const esSamples: EuSample[] = [
  {
    "input": "Calle de Alcalá, 42, 28014 Madrid",
    "number": "42",
    "street": "de Alcalá",
    "type": "Calle",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "normal; comma before number"
  },
  {
    "input": "Calle Mayor, 10, 3.º B, 28013 Madrid",
    "number": "10",
    "street": "Mayor",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3.º B",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor+door 3.º B kept as one secondary unit"
  },
  {
    "input": "C/ Mayor, 10, 28013 Madrid",
    "number": "10",
    "street": "Mayor",
    "type": "C/",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "C/ abbreviation for Calle"
  },
  {
    "input": "C. Gran Vía, 28, 28013 Madrid",
    "number": "28",
    "street": "Gran Vía",
    "type": "C.",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "C. abbreviation with period; name is itself Gran Vía"
  },
  {
    "input": "Gran Vía, 28, 28013 Madrid",
    "number": "28",
    "type": "Gran Vía",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "multiword type Gran Vía with no further name"
  },
  {
    "input": "Avenida Diagonal, 640, 3º B, 08017 Barcelona",
    "number": "640",
    "street": "Diagonal",
    "type": "Avenida",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3º B",
    "postal_code": "08017",
    "city": "Barcelona",
    "country": "ES",
    "notes": "floor+door 3º B; no particle in name"
  },
  {
    "input": "Carrer de Mallorca, 401, 08013 Barcelona",
    "number": "401",
    "street": "de Mallorca",
    "type": "Carrer",
    "postal_code": "08013",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Carrer de; near Sagrada Família"
  },
  {
    "input": "Passeig de Gràcia, 92, 08008 Barcelona",
    "number": "92",
    "street": "de Gràcia",
    "type": "Passeig",
    "postal_code": "08008",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Passeig; accent à in Gràcia"
  },
  {
    "input": "Plaça de Catalunya, 1, 08002 Barcelona",
    "number": "1",
    "street": "de Catalunya",
    "type": "Plaça",
    "postal_code": "08002",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Plaça with cedilla"
  },
  {
    "input": "Rambla de Catalunya, 145, 3r-2a, 08008 Barcelona",
    "number": "145",
    "street": "de Catalunya",
    "type": "Rambla",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3r-2a",
    "postal_code": "08008",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan ordinal floor+door 3r-2a (3rd floor, door 2)"
  },
  {
    "input": "Carrer de Muntaner, 240, 4t 1a, 08021 Barcelona",
    "number": "240",
    "street": "de Muntaner",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4t 1a",
    "postal_code": "08021",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan ordinal 4t (quart) 1a"
  },
  {
    "input": "Avinguda Diagonal, 3, 08019 Barcelona",
    "number": "3",
    "street": "Diagonal",
    "type": "Avinguda",
    "postal_code": "08019",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Avinguda"
  },
  {
    "input": "Calle del Prado, s/n, 28014 Madrid",
    "street": "del Prado",
    "type": "Calle",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "s/n = sin número, number is null"
  },
  {
    "input": "Avenida de América, 5, 28002 Madrid",
    "number": "5",
    "street": "de América",
    "type": "Avenida",
    "postal_code": "28002",
    "city": "Madrid",
    "country": "ES",
    "notes": "accent in América"
  },
  {
    "input": "Avda. de América, 5, 28002 Madrid",
    "number": "5",
    "street": "de América",
    "type": "Avda.",
    "postal_code": "28002",
    "city": "Madrid",
    "country": "ES",
    "notes": "Avda. abbreviation for Avenida"
  },
  {
    "input": "Av. de la Constitución, 1, 41001 Sevilla",
    "number": "1",
    "street": "de la Constitución",
    "type": "Av.",
    "postal_code": "41001",
    "city": "Sevilla",
    "country": "ES",
    "notes": "Av. abbrev; particle de la kept"
  },
  {
    "input": "Plaza de España, 1, 41013 Sevilla",
    "number": "1",
    "street": "de España",
    "type": "Plaza",
    "postal_code": "41013",
    "city": "Sevilla",
    "country": "ES",
    "notes": "ñ in España"
  },
  {
    "input": "Pza. del Pilar, 18, 50003 Zaragoza",
    "number": "18",
    "street": "del Pilar",
    "type": "Pza.",
    "postal_code": "50003",
    "city": "Zaragoza",
    "country": "ES",
    "notes": "Pza. abbreviation for Plaza"
  },
  {
    "input": "Pl. Mayor, 1, 47001 Valladolid",
    "number": "1",
    "street": "Mayor",
    "type": "Pl.",
    "postal_code": "47001",
    "city": "Valladolid",
    "country": "ES",
    "notes": "Pl. abbreviation"
  },
  {
    "input": "Paseo de la Castellana, 200, 28046 Madrid",
    "number": "200",
    "street": "de la Castellana",
    "type": "Paseo",
    "postal_code": "28046",
    "city": "Madrid",
    "country": "ES",
    "notes": "Paseo type"
  },
  {
    "input": "Po de la Castellana, 259, 28046 Madrid",
    "number": "259",
    "street": "de la Castellana",
    "type": "Po",
    "postal_code": "28046",
    "city": "Madrid",
    "country": "ES",
    "notes": "Po abbreviation for Paseo (Torre de Cristal area)"
  },
  {
    "input": "P.º del Prado, 8, 28014 Madrid",
    "number": "8",
    "street": "del Prado",
    "type": "P.º",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "P.º abbreviation for Paseo (Museo del Prado)"
  },
  {
    "input": "Calle de Alcalá, nº 42, 28014 Madrid",
    "number": "42",
    "street": "de Alcalá",
    "type": "Calle",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "nº number marker before digits"
  },
  {
    "input": "Calle Mayor núm. 10, 28013 Madrid",
    "number": "10",
    "street": "Mayor",
    "type": "Calle",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "núm. marker, no comma before it"
  },
  {
    "input": "Calle Bailén, 3, n.º 2, 28005 Madrid",
    "number": "3",
    "street": "Bailén",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "2",
    "postal_code": "28005",
    "city": "Madrid",
    "country": "ES",
    "notes": "n.º here marks door number; accent in Bailén"
  },
  {
    "input": "Calle de Ferraz, 12 bis, 28008 Madrid",
    "number": "12",
    "civic_number_suffix": "bis",
    "street": "de Ferraz",
    "type": "Calle",
    "postal_code": "28008",
    "city": "Madrid",
    "country": "ES",
    "notes": "bis suffix on number"
  },
  {
    "input": "Calle de Serrano, 27 A, 28001 Madrid",
    "number": "27",
    "civic_number_suffix": "A",
    "street": "de Serrano",
    "type": "Calle",
    "postal_code": "28001",
    "city": "Madrid",
    "country": "ES",
    "notes": "letter suffix on number"
  },
  {
    "input": "Calle de Goya, 12-14, 28001 Madrid",
    "number": "12-14",
    "street": "de Goya",
    "type": "Calle",
    "postal_code": "28001",
    "city": "Madrid",
    "country": "ES",
    "notes": "number range 12-14"
  },
  {
    "input": "Calle de Velázquez, 50, 4.º Izda., 28001 Madrid",
    "number": "50",
    "street": "de Velázquez",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4.º Izda.",
    "postal_code": "28001",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor + Izda (left); accent in Velázquez"
  },
  {
    "input": "Calle de Fuencarral, 70, 2.º Dcha., 28004 Madrid",
    "number": "70",
    "street": "de Fuencarral",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "2.º Dcha.",
    "postal_code": "28004",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor + Dcha (right)"
  },
  {
    "input": "Calle de Atocha, 25, Bajo, 28012 Madrid",
    "number": "25",
    "street": "de Atocha",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Bajo",
    "postal_code": "28012",
    "city": "Madrid",
    "country": "ES",
    "notes": "word-floor Bajo (ground floor)"
  },
  {
    "input": "Calle de la Montera, 32, Ático, 28013 Madrid",
    "number": "32",
    "street": "de la Montera",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Ático",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "word-floor Ático (top)"
  },
  {
    "input": "Calle de Preciados, 9, Entresuelo, 28013 Madrid",
    "number": "9",
    "street": "de Preciados",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Entresuelo",
    "postal_code": "28013",
    "city": "Madrid",
    "country": "ES",
    "notes": "word-floor Entresuelo (mezzanine)"
  },
  {
    "input": "Calle de Toledo, 5, Pral. Dcha., 28005 Madrid",
    "number": "5",
    "street": "de Toledo",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Pral. Dcha.",
    "postal_code": "28005",
    "city": "Madrid",
    "country": "ES",
    "notes": "Pral. = Principal floor + Dcha"
  },
  {
    "input": "Calle Gran Capitán, 20, Esc. 2, 3.º A, 18001 Granada",
    "__skip": "stacked multiple secondary units",
    "number": "20",
    "street": "Gran Capitán",
    "type": "Calle",
    "sec_unit_type": "Escalera",
    "sec_unit_num": "2, 3.º A",
    "postal_code": "18001",
    "city": "Granada",
    "country": "ES",
    "notes": "escalera + floor + door chain; only 20 is civic number"
  },
  {
    "input": "Calle Larios, 4, Portal 2, 1.º B, 29005 Málaga",
    "__skip": "stacked multiple secondary units",
    "number": "4",
    "street": "Larios",
    "type": "Calle",
    "sec_unit_type": "Portal",
    "sec_unit_num": "2, 1.º B",
    "postal_code": "29005",
    "city": "Málaga",
    "country": "ES",
    "notes": "portal + floor + door"
  },
  {
    "input": "Carretera de Burgos, km 12, 28050 Madrid",
    "street": "de Burgos",
    "type": "Carretera",
    "sec_unit_type": "km",
    "sec_unit_num": "12",
    "postal_code": "28050",
    "city": "Madrid",
    "country": "ES",
    "notes": "km point on carretera, no civic number"
  },
  {
    "input": "Ctra. de Cádiz, km 176, 29600 Marbella (Málaga)",
    "street": "de Cádiz",
    "type": "Ctra.",
    "sec_unit_type": "km",
    "sec_unit_num": "176",
    "postal_code": "29600",
    "city": "Marbella",
    "state": "Málaga",
    "country": "ES",
    "notes": "Ctra. abbrev; km; province in parens"
  },
  {
    "input": "Ronda de Toledo, 10, 28005 Madrid",
    "number": "10",
    "street": "de Toledo",
    "type": "Ronda",
    "postal_code": "28005",
    "city": "Madrid",
    "country": "ES",
    "notes": "Ronda type"
  },
  {
    "input": "Rda. de Sant Pere, 44, 08010 Barcelona",
    "number": "44",
    "street": "de Sant Pere",
    "type": "Rda.",
    "postal_code": "08010",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Rda. abbrev for Ronda; Catalan name"
  },
  {
    "input": "Camino de la Fuente, 8, 28660 Boadilla del Monte (Madrid)",
    "number": "8",
    "street": "de la Fuente",
    "type": "Camino",
    "postal_code": "28660",
    "city": "Boadilla del Monte",
    "state": "Madrid",
    "country": "ES",
    "notes": "Camino; province in parens; multiword city"
  },
  {
    "input": "Cno. Viejo de Simancas, 30, 47008 Valladolid",
    "number": "30",
    "street": "Viejo de Simancas",
    "type": "Cno.",
    "postal_code": "47008",
    "city": "Valladolid",
    "country": "ES",
    "notes": "Cno. abbrev for Camino"
  },
  {
    "input": "Travesía de las Vistillas, 3, 28005 Madrid",
    "number": "3",
    "street": "de las Vistillas",
    "type": "Travesía",
    "postal_code": "28005",
    "city": "Madrid",
    "country": "ES",
    "notes": "Travesía type; particle de las"
  },
  {
    "input": "Trav. de Gràcia, 12, 08021 Barcelona",
    "number": "12",
    "street": "de Gràcia",
    "type": "Trav.",
    "postal_code": "08021",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Trav. abbrev; Catalan Travessera"
  },
  {
    "input": "Glorieta de Bilbao, 1, 28004 Madrid",
    "number": "1",
    "street": "de Bilbao",
    "type": "Glorieta",
    "postal_code": "28004",
    "city": "Madrid",
    "country": "ES",
    "notes": "Glorieta type"
  },
  {
    "input": "Cuesta de la Vega, 4, 28005 Madrid",
    "number": "4",
    "street": "de la Vega",
    "type": "Cuesta",
    "postal_code": "28005",
    "city": "Madrid",
    "country": "ES",
    "notes": "Cuesta type"
  },
  {
    "input": "Vía Layetana, 30, 08003 Barcelona",
    "number": "30",
    "street": "Layetana",
    "type": "Vía",
    "postal_code": "08003",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Vía type (single word)"
  },
  {
    "input": "Bulevar Louis Pasteur, 33, 29010 Málaga",
    "number": "33",
    "street": "Louis Pasteur",
    "type": "Bulevar",
    "postal_code": "29010",
    "city": "Málaga",
    "country": "ES",
    "notes": "Bulevar type"
  },
  {
    "input": "Rúa do Vilar, 47, 15705 Santiago de Compostela (A Coruña)",
    "number": "47",
    "street": "do Vilar",
    "type": "Rúa",
    "postal_code": "15705",
    "city": "Santiago de Compostela",
    "state": "A Coruña",
    "country": "ES",
    "notes": "Galician Rúa; particle do; province A Coruña in parens"
  },
  {
    "input": "Rúa Nova, 5, 27001 Lugo",
    "number": "5",
    "street": "Nova",
    "type": "Rúa",
    "postal_code": "27001",
    "city": "Lugo",
    "country": "ES",
    "notes": "Galician Rúa"
  },
  {
    "input": "Gran Vía Kalea, 1, 48001 Bilbao",
    "__skip": "Basque suffix-placed type (Kalea)",
    "number": "1",
    "street": "Gran Vía",
    "type": "Kalea",
    "postal_code": "48001",
    "city": "Bilbao",
    "country": "ES",
    "notes": "Basque Kalea is a SUFFIX type (comes after the name)"
  },
  {
    "input": "Ledesma Kalea, 10, 48001 Bilbao",
    "__skip": "Basque suffix-placed type (Kalea)",
    "number": "10",
    "street": "Ledesma",
    "type": "Kalea",
    "postal_code": "48001",
    "city": "Bilbao",
    "country": "ES",
    "notes": "Basque suffix type Kalea"
  },
  {
    "input": "Ercilla Kalea, 24, 48011 Bilbao",
    "__skip": "Basque suffix-placed type (Kalea)",
    "number": "24",
    "street": "Ercilla",
    "type": "Kalea",
    "postal_code": "48011",
    "city": "Bilbao",
    "country": "ES",
    "notes": "Basque suffix type"
  },
  {
    "input": "Calle Marqués del Puerto, 8, 48009 Bilbao",
    "number": "8",
    "street": "Marqués del Puerto",
    "type": "Calle",
    "postal_code": "48009",
    "city": "Bilbao",
    "country": "ES",
    "notes": "Castilian form used in Basque Country; accent in Marqués"
  },
  {
    "input": "Calle de Colón, 1, 46004 Valencia",
    "number": "1",
    "street": "de Colón",
    "type": "Calle",
    "postal_code": "46004",
    "city": "Valencia",
    "country": "ES",
    "notes": "accent in Colón"
  },
  {
    "input": "Carrer de Colom, 1, 46004 València",
    "number": "1",
    "street": "de Colom",
    "type": "Carrer",
    "postal_code": "46004",
    "city": "València",
    "country": "ES",
    "notes": "Valencian Carrer; city spelled València with accent"
  },
  {
    "input": "Plaça de l'Ajuntament, 1, 46002 València",
    "number": "1",
    "street": "de l'Ajuntament",
    "type": "Plaça",
    "postal_code": "46002",
    "city": "València",
    "country": "ES",
    "notes": "Valencian; apostrophe in de l'Ajuntament"
  },
  {
    "input": "Avinguda del Port, 100, 46023 València",
    "number": "100",
    "street": "del Port",
    "type": "Avinguda",
    "postal_code": "46023",
    "city": "València",
    "country": "ES",
    "notes": "Valencian Avinguda; particle del"
  },
  {
    "input": "Calle de Larios, 2, 4.º, 29015 Málaga",
    "number": "2",
    "street": "de Larios",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4.º",
    "postal_code": "29015",
    "city": "Málaga",
    "country": "ES",
    "notes": "floor only, no door"
  },
  {
    "input": "Calle Real, 22, 1ª, 15003 A Coruña",
    "number": "22",
    "street": "Real",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "1ª",
    "postal_code": "15003",
    "city": "A Coruña",
    "country": "ES",
    "notes": "feminine ordinal floor 1ª; city A Coruña"
  },
  {
    "input": "Calle Betis, 60, 41010 Sevilla",
    "number": "60",
    "street": "Betis",
    "type": "Calle",
    "postal_code": "41010",
    "city": "Sevilla",
    "country": "ES",
    "notes": "normal, Triana district"
  },
  {
    "input": "Avenida de la Palmera, 20, 41013 Sevilla",
    "number": "20",
    "street": "de la Palmera",
    "type": "Avenida",
    "postal_code": "41013",
    "city": "Sevilla",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Calle Sierpes, 15, 41004 Sevilla",
    "number": "15",
    "street": "Sierpes",
    "type": "Calle",
    "postal_code": "41004",
    "city": "Sevilla",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Calle de la Paz, 12, Pta. 5, 46003 València",
    "number": "12",
    "street": "de la Paz",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "5",
    "postal_code": "46003",
    "city": "València",
    "country": "ES",
    "notes": "Pta. = puerta (door) explicit"
  },
  {
    "input": "Calle San Vicente, 45, Piso 2, Puerta 4, 46007 Valencia",
    "__skip": "stacked multiple secondary units",
    "number": "45",
    "street": "San Vicente",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "2, Puerta 4",
    "postal_code": "46007",
    "city": "Valencia",
    "country": "ES",
    "notes": "explicit Piso and Puerta words"
  },
  {
    "input": "Calle Uría, 30, 33003 Oviedo (Asturias)",
    "number": "30",
    "street": "Uría",
    "type": "Calle",
    "postal_code": "33003",
    "city": "Oviedo",
    "state": "Asturias",
    "country": "ES",
    "notes": "province Asturias (code 33) in parens; accent in Uría"
  },
  {
    "input": "Calle Corrida, 20, 33206 Gijón (Asturias)",
    "number": "20",
    "street": "Corrida",
    "type": "Calle",
    "postal_code": "33206",
    "city": "Gijón",
    "state": "Asturias",
    "country": "ES",
    "notes": "Gijón in Asturias province; ñ and accent"
  },
  {
    "input": "Calle Ancha, 5, 11001 Cádiz",
    "number": "5",
    "street": "Ancha",
    "type": "Calle",
    "postal_code": "11001",
    "city": "Cádiz",
    "country": "ES",
    "notes": "accent in Cádiz"
  },
  {
    "input": "Calle Larga, 40, 11402 Jerez de la Frontera (Cádiz)",
    "number": "40",
    "street": "Larga",
    "type": "Calle",
    "postal_code": "11402",
    "city": "Jerez de la Frontera",
    "state": "Cádiz",
    "country": "ES",
    "notes": "multiword city; province Cádiz in parens"
  },
  {
    "input": "Calle Mayor, 25, 3.º, 28801 Alcalá de Henares (Madrid)",
    "number": "25",
    "street": "Mayor",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3.º",
    "postal_code": "28801",
    "city": "Alcalá de Henares",
    "state": "Madrid",
    "country": "ES",
    "notes": "province Madrid in parens for a non-capital town; floor"
  },
  {
    "input": "Calle Libertad, 8, 28850 Torrejón de Ardoz (Madrid)",
    "number": "8",
    "street": "Libertad",
    "type": "Calle",
    "postal_code": "28850",
    "city": "Torrejón de Ardoz",
    "state": "Madrid",
    "country": "ES",
    "notes": "province in parens"
  },
  {
    "input": "Avenida de España, 3, 28100 Alcobendas (Madrid)",
    "number": "3",
    "street": "de España",
    "type": "Avenida",
    "postal_code": "28100",
    "city": "Alcobendas",
    "state": "Madrid",
    "country": "ES",
    "notes": "province in parens"
  },
  {
    "input": "Calle Real, 18, 28770 Colmenar Viejo (Madrid)",
    "number": "18",
    "street": "Real",
    "type": "Calle",
    "postal_code": "28770",
    "city": "Colmenar Viejo",
    "state": "Madrid",
    "country": "ES",
    "notes": "province in parens"
  },
  {
    "input": "Carrer Major, 12, 08870 Sitges (Barcelona)",
    "number": "12",
    "street": "Major",
    "type": "Carrer",
    "postal_code": "08870",
    "city": "Sitges",
    "state": "Barcelona",
    "country": "ES",
    "notes": "Catalan Carrer Major; province Barcelona in parens"
  },
  {
    "input": "Rambla Nova, 100, 43003 Tarragona",
    "number": "100",
    "street": "Nova",
    "type": "Rambla",
    "postal_code": "43003",
    "city": "Tarragona",
    "country": "ES",
    "notes": "Rambla in Tarragona"
  },
  {
    "input": "Carrer de l'Hospital, 56, 08001 Barcelona",
    "number": "56",
    "street": "de l'Hospital",
    "type": "Carrer",
    "postal_code": "08001",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan apostrophe de l'Hospital; leading-zero CP 08001"
  },
  {
    "input": "Carrer Gran de Gràcia, 15, 2n 1a, 08012 Barcelona",
    "number": "15",
    "street": "Gran de Gràcia",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "2n 1a",
    "postal_code": "08012",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan ordinal 2n (segon) 1a"
  },
  {
    "input": "Passeig Marítim, 33, 08003 Barcelona",
    "number": "33",
    "street": "Marítim",
    "type": "Passeig",
    "postal_code": "08003",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan; accent in Marítim"
  },
  {
    "input": "Carrer de Balmes, 200, Àtic, 08006 Barcelona",
    "number": "200",
    "street": "de Balmes",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Àtic",
    "postal_code": "08006",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan word-floor Àtic"
  },
  {
    "input": "Carrer del Bruc, 88, Baixos, 08009 Barcelona",
    "number": "88",
    "street": "del Bruc",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Baixos",
    "postal_code": "08009",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan word-floor Baixos (ground)"
  },
  {
    "input": "Carrer de Sants, 79, Entresòl, 08014 Barcelona",
    "number": "79",
    "street": "de Sants",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Entresòl",
    "postal_code": "08014",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Entresòl (mezzanine)"
  },
  {
    "input": "Calle Nueva, 3, 3.º 2ª, 30201 Cartagena (Murcia)",
    "number": "3",
    "street": "Nueva",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3.º 2ª",
    "postal_code": "30201",
    "city": "Cartagena",
    "state": "Murcia",
    "country": "ES",
    "notes": "floor+door mixed masc/fem 3.º 2ª; province in parens"
  },
  {
    "input": "Gran Vía Marqués del Turia, 49, 46005 Valencia",
    "number": "49",
    "street": "Marqués del Turia",
    "type": "Gran Vía",
    "postal_code": "46005",
    "city": "Valencia",
    "country": "ES",
    "notes": "multiword type Gran Vía + name Marqués del Turia"
  },
  {
    "input": "Gran Via de les Corts Catalanes, 400, 08015 Barcelona",
    "number": "400",
    "street": "de les Corts Catalanes",
    "type": "Gran Via",
    "postal_code": "08015",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Gran Via multiword type; long name with particle de les"
  },
  {
    "input": "Calle del Carmen, 14, 28012 Madrid",
    "number": "14",
    "street": "del Carmen",
    "type": "Calle",
    "postal_code": "28012",
    "city": "Madrid",
    "country": "ES",
    "notes": "particle del"
  },
  {
    "input": "Calle de los Reyes, 7, 28015 Madrid",
    "number": "7",
    "street": "de los Reyes",
    "type": "Calle",
    "postal_code": "28015",
    "city": "Madrid",
    "country": "ES",
    "notes": "particle de los"
  },
  {
    "input": "Calle de las Huertas, 18, 28014 Madrid",
    "number": "18",
    "street": "de las Huertas",
    "type": "Calle",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "particle de las"
  },
  {
    "input": "Calle Cardenal Cisneros, 22, 28010 Madrid",
    "number": "22",
    "street": "Cardenal Cisneros",
    "type": "Calle",
    "postal_code": "28010",
    "city": "Madrid",
    "country": "ES",
    "notes": "multiword name, no particle"
  },
  {
    "input": "Calle Núñez de Balboa, 35, 28001 Madrid",
    "number": "35",
    "street": "Núñez de Balboa",
    "type": "Calle",
    "postal_code": "28001",
    "city": "Madrid",
    "country": "ES",
    "notes": "ñ and accent in Núñez; internal particle de"
  },
  {
    "input": "Paseo de Gracia, 43, 08007 Barcelona",
    "number": "43",
    "street": "de Gracia",
    "type": "Paseo",
    "postal_code": "08007",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Castilian spelling Paseo de Gracia (Casa Batlló)"
  },
  {
    "input": "Calle Sagasta, 5, 4.º C, 28004 Madrid",
    "number": "5",
    "street": "Sagasta",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4.º C",
    "postal_code": "28004",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor+door 4.º C"
  },
  {
    "input": "Calle O'Donnell, 12, 28009 Madrid",
    "number": "12",
    "street": "O'Donnell",
    "type": "Calle",
    "postal_code": "28009",
    "city": "Madrid",
    "country": "ES",
    "notes": "apostrophe in name O'Donnell"
  },
  {
    "input": "Carrer d'Aragó, 300, 08009 Barcelona",
    "number": "300",
    "street": "d'Aragó",
    "type": "Carrer",
    "postal_code": "08009",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan elided particle d'Aragó; accent"
  },
  {
    "input": "Calle Triana, 25, 35002 Las Palmas de Gran Canaria",
    "number": "25",
    "street": "Triana",
    "type": "Calle",
    "postal_code": "35002",
    "city": "Las Palmas de Gran Canaria",
    "country": "ES",
    "notes": "long city name; Canary Islands CP 35"
  },
  {
    "input": "Calle del Castillo, 40, 38002 Santa Cruz de Tenerife",
    "number": "40",
    "street": "del Castillo",
    "type": "Calle",
    "postal_code": "38002",
    "city": "Santa Cruz de Tenerife",
    "country": "ES",
    "notes": "long city name; CP 38"
  },
  {
    "input": "Calle Real, 12, 51001 Ceuta",
    "number": "12",
    "street": "Real",
    "type": "Calle",
    "postal_code": "51001",
    "city": "Ceuta",
    "country": "ES",
    "notes": "autonomous city Ceuta, CP prefix 51"
  },
  {
    "input": "Calle General Marina, 5, 52001 Melilla",
    "number": "5",
    "street": "General Marina",
    "type": "Calle",
    "postal_code": "52001",
    "city": "Melilla",
    "country": "ES",
    "notes": "autonomous city Melilla, CP prefix 52"
  },
  {
    "input": "Calle Marqués de Larios, 1, 29005 Málaga, España",
    "number": "1",
    "street": "Marqués de Larios",
    "type": "Calle",
    "postal_code": "29005",
    "city": "Málaga",
    "country": "ES",
    "notes": "explicit country España"
  },
  {
    "input": "Calle Sierpes, 30, 41004 Sevilla, Spain",
    "number": "30",
    "street": "Sierpes",
    "type": "Calle",
    "postal_code": "41004",
    "city": "Sevilla",
    "country": "ES",
    "notes": "explicit country Spain (English)"
  },
  {
    "input": "Avenida del Puerto, 15, 46021 Valencia, ES",
    "number": "15",
    "street": "del Puerto",
    "type": "Avenida",
    "postal_code": "46021",
    "city": "Valencia",
    "country": "ES",
    "notes": "explicit country ES"
  },
  {
    "input": "Calle San Fernando, 4, 41004 Sevilla",
    "number": "4",
    "street": "San Fernando",
    "type": "Calle",
    "postal_code": "41004",
    "city": "Sevilla",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Calle Ruiz de Alda, 9, 30002 Murcia",
    "number": "9",
    "street": "Ruiz de Alda",
    "type": "Calle",
    "postal_code": "30002",
    "city": "Murcia",
    "country": "ES",
    "notes": "name with internal de"
  },
  {
    "input": "Gran Vía de Colón, 10, 18001 Granada",
    "number": "10",
    "street": "de Colón",
    "type": "Gran Vía",
    "postal_code": "18001",
    "city": "Granada",
    "country": "ES",
    "notes": "Gran Vía multiword type + particle de"
  },
  {
    "input": "Calle Reyes Católicos, 40, 18001 Granada",
    "number": "40",
    "street": "Reyes Católicos",
    "type": "Calle",
    "postal_code": "18001",
    "city": "Granada",
    "country": "ES",
    "notes": "accent in Católicos"
  },
  {
    "input": "Calle Elvira, 22, Bajo A, 18010 Granada",
    "number": "22",
    "street": "Elvira",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Bajo A",
    "postal_code": "18010",
    "city": "Granada",
    "country": "ES",
    "notes": "word-floor Bajo + door A"
  },
  {
    "input": "Avenida de la Constitución, 24, 4.º Izquierda, 41001 Sevilla",
    "number": "24",
    "street": "de la Constitución",
    "type": "Avenida",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4.º Izquierda",
    "postal_code": "41001",
    "city": "Sevilla",
    "country": "ES",
    "notes": "full word Izquierda for door side"
  },
  {
    "input": "Calle del Pez, 21, Sótano, 28004 Madrid",
    "number": "21",
    "street": "del Pez",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Sótano",
    "postal_code": "28004",
    "city": "Madrid",
    "country": "ES",
    "notes": "word-floor Sótano (basement)"
  },
  {
    "input": "Pasaje de Doña Carlota, 8, 28019 Madrid",
    "number": "8",
    "street": "de Doña Carlota",
    "type": "Pasaje",
    "postal_code": "28019",
    "city": "Madrid",
    "country": "ES",
    "notes": "Pasaje type; ñ in Doña"
  },
  {
    "input": "Psje. Permanyer, 4, 08009 Barcelona",
    "number": "4",
    "street": "Permanyer",
    "type": "Psje.",
    "postal_code": "08009",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Psje. abbreviation for Pasaje/Passatge"
  },
  {
    "input": "Callejón del Gato, 3, 28012 Madrid",
    "number": "3",
    "street": "del Gato",
    "type": "Callejón",
    "postal_code": "28012",
    "city": "Madrid",
    "country": "ES",
    "notes": "Callejón type; accent"
  },
  {
    "input": "Polígono Industrial Las Mercedes, Calle A, 12, 28022 Madrid",
    "__skip": "industrial estate with nested vía",
    "number": "12",
    "street": "Industrial Las Mercedes, Calle A",
    "type": "Polígono",
    "postal_code": "28022",
    "city": "Madrid",
    "country": "ES",
    "notes": "industrial estate Polígono; nested street reference"
  },
  {
    "input": "Urbanización Los Naranjos, 45, 29660 Marbella (Málaga)",
    "number": "45",
    "street": "Los Naranjos",
    "type": "Urbanización",
    "postal_code": "29660",
    "city": "Marbella",
    "state": "Málaga",
    "country": "ES",
    "notes": "Urbanización (housing estate); province in parens"
  },
  {
    "input": "Calle del Mar, s/n, 03002 Alicante",
    "street": "del Mar",
    "type": "Calle",
    "postal_code": "03002",
    "city": "Alicante",
    "country": "ES",
    "notes": "s/n with leading-zero CP 03002"
  },
  {
    "input": "Explanada de España, s/n, 03002 Alicante",
    "street": "de España",
    "type": "Explanada",
    "postal_code": "03002",
    "city": "Alicante",
    "country": "ES",
    "notes": "Explanada type; s/n; ñ"
  },
  {
    "input": "Avinguda del Cid, 12, 03201 Elx (Alacant)",
    "number": "12",
    "street": "del Cid",
    "type": "Avinguda",
    "postal_code": "03201",
    "city": "Elx",
    "state": "Alacant",
    "country": "ES",
    "notes": "Valencian city Elx and province Alacant in parens"
  },
  {
    "input": "Calle Colón, 15, 03500 Benidorm (Alicante)",
    "number": "15",
    "street": "Colón",
    "type": "Calle",
    "postal_code": "03500",
    "city": "Benidorm",
    "state": "Alicante",
    "country": "ES",
    "notes": "province in parens; leading-zero CP"
  },
  {
    "input": "Carrer Major, 30, 2n, 25007 Lleida",
    "number": "30",
    "street": "Major",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "2n",
    "postal_code": "25007",
    "city": "Lleida",
    "country": "ES",
    "notes": "Catalan city Lleida; ordinal 2n floor only"
  },
  {
    "input": "Carrer Nou, 8, 17001 Girona",
    "number": "8",
    "street": "Nou",
    "type": "Carrer",
    "postal_code": "17001",
    "city": "Girona",
    "country": "ES",
    "notes": "Catalan city Girona (province 17)"
  },
  {
    "input": "Carrer de la Rambla, 25, 43201 Reus (Tarragona)",
    "number": "25",
    "street": "de la Rambla",
    "type": "Carrer",
    "postal_code": "43201",
    "city": "Reus",
    "state": "Tarragona",
    "country": "ES",
    "notes": "Catalan; province in parens"
  },
  {
    "input": "Rambla del Poblenou, 100, 08018 Barcelona",
    "number": "100",
    "street": "del Poblenou",
    "type": "Rambla",
    "postal_code": "08018",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Rambla with particle del"
  },
  {
    "input": "Avinguda Meridiana, 350, 5è 2a, 08027 Barcelona",
    "number": "350",
    "street": "Meridiana",
    "type": "Avinguda",
    "sec_unit_type": "Piso",
    "sec_unit_num": "5è 2a",
    "postal_code": "08027",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan ordinal 5è (cinquè) 2a"
  },
  {
    "input": "Calle Portales, 60, 26001 Logroño (La Rioja)",
    "number": "60",
    "street": "Portales",
    "type": "Calle",
    "postal_code": "26001",
    "city": "Logroño",
    "state": "La Rioja",
    "country": "ES",
    "notes": "province La Rioja (code 26, name != capital); ñ"
  },
  {
    "input": "Calle Mayor, 33, 31001 Pamplona (Navarra)",
    "number": "33",
    "street": "Mayor",
    "type": "Calle",
    "postal_code": "31001",
    "city": "Pamplona",
    "state": "Navarra",
    "country": "ES",
    "notes": "province Navarra (code 31, != capital)"
  },
  {
    "input": "Calle Estafeta, 15, 31001 Pamplona / Iruña",
    "number": "15",
    "street": "Estafeta",
    "type": "Calle",
    "postal_code": "31001",
    "city": "Pamplona / Iruña",
    "country": "ES",
    "notes": "bilingual city name Pamplona / Iruña"
  },
  {
    "input": "Calle Dato, 20, 01005 Vitoria-Gasteiz (Araba)",
    "number": "20",
    "street": "Dato",
    "type": "Calle",
    "postal_code": "01005",
    "city": "Vitoria-Gasteiz",
    "state": "Araba",
    "country": "ES",
    "notes": "hyphenated bilingual city; province Araba (code 01); leading-zero CP"
  },
  {
    "input": "Boulevard, 5, 20005 Donostia / San Sebastián (Gipuzkoa)",
    "number": "5",
    "type": "Boulevard",
    "postal_code": "20005",
    "city": "Donostia / San Sebastián",
    "state": "Gipuzkoa",
    "country": "ES",
    "notes": "bilingual city Donostia / San Sebastián; province Gipuzkoa"
  },
  {
    "input": "Avenida de la Libertad, 15, 20004 Donostia / San Sebastián (Gipuzkoa)",
    "number": "15",
    "street": "de la Libertad",
    "type": "Avenida",
    "postal_code": "20004",
    "city": "Donostia / San Sebastián",
    "state": "Gipuzkoa",
    "country": "ES",
    "notes": "bilingual city; province in parens"
  },
  {
    "input": "Kale Nagusia, 12, 48005 Bilbao",
    "__skip": "Basque suffix-placed type (Kale)",
    "number": "12",
    "street": "Nagusia",
    "type": "Kalea",
    "postal_code": "48005",
    "city": "Bilbao",
    "country": "ES",
    "notes": "Basque Kale Nagusia (Calle Mayor); type word Kale/Kalea"
  },
  {
    "input": "Calle Uribitarte, 6, 48001 Bilbao (Bizkaia)",
    "number": "6",
    "street": "Uribitarte",
    "type": "Calle",
    "postal_code": "48001",
    "city": "Bilbao",
    "state": "Bizkaia",
    "country": "ES",
    "notes": "province Bizkaia (code 48) in parens"
  },
  {
    "input": "Calle Mayor, 4, 48930 Getxo (Bizkaia)",
    "number": "4",
    "street": "Mayor",
    "type": "Calle",
    "postal_code": "48930",
    "city": "Getxo",
    "state": "Bizkaia",
    "country": "ES",
    "notes": "town Getxo, province Bizkaia in parens"
  },
  {
    "input": "Carrer de Barcelona, 5, 3r 1a, 08901 L'Hospitalet de Llobregat (Barcelona)",
    "number": "5",
    "street": "de Barcelona",
    "type": "Carrer",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3r 1a",
    "postal_code": "08901",
    "city": "L'Hospitalet de Llobregat",
    "state": "Barcelona",
    "country": "ES",
    "notes": "apostrophe city name L'Hospitalet; province in parens; Catalan floor"
  },
  {
    "input": "Avenida de la Constitución, 22, 28850 Torrejón de Ardoz (Madrid)",
    "number": "22",
    "street": "de la Constitución",
    "type": "Avenida",
    "postal_code": "28850",
    "city": "Torrejón de Ardoz",
    "state": "Madrid",
    "country": "ES",
    "notes": "province in parens; multiword city with accent"
  },
  {
    "input": "Calle de Bravo Murillo, 377, 5.º D, 28020 Madrid",
    "number": "377",
    "street": "de Bravo Murillo",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "5.º D",
    "postal_code": "28020",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor+door 5.º D"
  },
  {
    "input": "Calle de Embajadores, 110, 1º Izda, 28012 Madrid",
    "number": "110",
    "street": "de Embajadores",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "1º Izda",
    "postal_code": "28012",
    "city": "Madrid",
    "country": "ES",
    "notes": "1º Izda without periods (real-world messy variant)"
  },
  {
    "input": "C/ Gran de Sant Andreu, 200, 08030 Barcelona",
    "number": "200",
    "street": "Gran de Sant Andreu",
    "type": "C/",
    "postal_code": "08030",
    "city": "Barcelona",
    "country": "ES",
    "notes": "C/ used for Catalan carrer name"
  },
  {
    "input": "C/Alcalá 100, 28009 Madrid",
    "number": "100",
    "street": "Alcalá",
    "type": "C/",
    "postal_code": "28009",
    "city": "Madrid",
    "country": "ES",
    "notes": "no space after C/ and no comma before number (messy)"
  },
  {
    "input": "Avda Diagonal 211, 08018 Barcelona",
    "number": "211",
    "street": "Diagonal",
    "type": "Avda",
    "postal_code": "08018",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Avda without period, no comma before number"
  },
  {
    "input": "Plaza del Ayuntamiento, 1, 46002 Valencia",
    "number": "1",
    "street": "del Ayuntamiento",
    "type": "Plaza",
    "postal_code": "46002",
    "city": "Valencia",
    "country": "ES",
    "notes": "Castilian Plaza del Ayuntamiento"
  },
  {
    "input": "Plaza Nueva, 1, 48005 Bilbao",
    "number": "1",
    "street": "Nueva",
    "type": "Plaza",
    "postal_code": "48005",
    "city": "Bilbao",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Calle Ganivet, 5, 18009 Granada",
    "number": "5",
    "street": "Ganivet",
    "type": "Calle",
    "postal_code": "18009",
    "city": "Granada",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Calle del Coso, 100, 50001 Zaragoza",
    "number": "100",
    "street": "del Coso",
    "type": "Calle",
    "postal_code": "50001",
    "city": "Zaragoza",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Paseo de la Independencia, 24, 4.º A, 50004 Zaragoza",
    "number": "24",
    "street": "de la Independencia",
    "type": "Paseo",
    "sec_unit_type": "Piso",
    "sec_unit_num": "4.º A",
    "postal_code": "50004",
    "city": "Zaragoza",
    "country": "ES",
    "notes": "Paseo + floor/door"
  },
  {
    "input": "Calle Toro, 18, 37002 Salamanca",
    "number": "18",
    "street": "Toro",
    "type": "Calle",
    "postal_code": "37002",
    "city": "Salamanca",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Rúa do Franco, 10, 15702 Santiago de Compostela (A Coruña)",
    "number": "10",
    "street": "do Franco",
    "type": "Rúa",
    "postal_code": "15702",
    "city": "Santiago de Compostela",
    "state": "A Coruña",
    "country": "ES",
    "notes": "Galician Rúa; province in parens"
  },
  {
    "input": "Rúa do Príncipe, 22, 36202 Vigo (Pontevedra)",
    "number": "22",
    "street": "do Príncipe",
    "type": "Rúa",
    "postal_code": "36202",
    "city": "Vigo",
    "state": "Pontevedra",
    "country": "ES",
    "notes": "Galician; Vigo in Pontevedra province (code 36); accent"
  },
  {
    "input": "Rúa do Paseo, 33, 32003 Ourense",
    "number": "33",
    "street": "do Paseo",
    "type": "Rúa",
    "postal_code": "32003",
    "city": "Ourense",
    "country": "ES",
    "notes": "Galician city Ourense (code 32)"
  },
  {
    "input": "Avenida de Roma, 8, 3.º 4ª, 08015 Barcelona",
    "number": "8",
    "street": "de Roma",
    "type": "Avenida",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3.º 4ª",
    "postal_code": "08015",
    "city": "Barcelona",
    "country": "ES",
    "notes": "floor+door 3.º 4ª"
  },
  {
    "input": "Calle Ausiàs March, 20, 46004 Valencia",
    "number": "20",
    "street": "Ausiàs March",
    "type": "Calle",
    "postal_code": "46004",
    "city": "Valencia",
    "country": "ES",
    "notes": "grave accent à in Ausiàs"
  },
  {
    "input": "Carrer del Císter, 20, 08022 Barcelona",
    "number": "20",
    "street": "del Císter",
    "type": "Carrer",
    "postal_code": "08022",
    "city": "Barcelona",
    "country": "ES",
    "notes": "accent in Císter"
  },
  {
    "input": "Calle de Alcalá, 42, 3º B, Esc. Izda., 28014 Madrid",
    "__skip": "stacked multiple secondary units",
    "number": "42",
    "street": "de Alcalá",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3º B, Esc. Izda.",
    "postal_code": "28014",
    "city": "Madrid",
    "country": "ES",
    "notes": "floor+door plus escalera side; complex tail"
  },
  {
    "input": "Camino Viejo, s/n, 45001 Toledo",
    "street": "Viejo",
    "type": "Camino",
    "postal_code": "45001",
    "city": "Toledo",
    "country": "ES",
    "notes": "s/n on a Camino"
  },
  {
    "input": "Calle Ancha, 15, 5, 06001 Badajoz",
    "__skip": "bare trailing number as door (ambiguous)",
    "number": "15",
    "street": "Ancha",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "5",
    "postal_code": "06001",
    "city": "Badajoz",
    "country": "ES",
    "notes": "second bare number after comma is the door; leading-zero CP 06"
  },
  {
    "input": "Calle Nueva, 8, 10003 Cáceres",
    "number": "8",
    "street": "Nueva",
    "type": "Calle",
    "postal_code": "10003",
    "city": "Cáceres",
    "country": "ES",
    "notes": "accent in Cáceres"
  },
  {
    "input": "Avenida de Portugal, 3, 06005 Badajoz",
    "number": "3",
    "street": "de Portugal",
    "type": "Avenida",
    "postal_code": "06005",
    "city": "Badajoz",
    "country": "ES",
    "notes": "leading-zero CP 06"
  },
  {
    "input": "Calle Mayor, 12, 07001 Palma",
    "number": "12",
    "street": "Mayor",
    "type": "Calle",
    "postal_code": "07001",
    "city": "Palma",
    "country": "ES",
    "notes": "Illes Balears CP 07 (leading zero)"
  },
  {
    "input": "Carrer de Sant Miquel, 40, 07002 Palma (Illes Balears)",
    "number": "40",
    "street": "de Sant Miquel",
    "type": "Carrer",
    "postal_code": "07002",
    "city": "Palma",
    "state": "Illes Balears",
    "country": "ES",
    "notes": "Catalan/Balearic; province Illes Balears in parens"
  },
  {
    "input": "Carrer d'Eivissa, 5, 07800 Eivissa (Illes Balears)",
    "number": "5",
    "street": "d'Eivissa",
    "type": "Carrer",
    "postal_code": "07800",
    "city": "Eivissa",
    "state": "Illes Balears",
    "country": "ES",
    "notes": "Ibiza in Catalan (Eivissa); elided d'"
  },
  {
    "input": "Calle San Francisco, 10, Bajo, 04001 Almería",
    "number": "10",
    "street": "San Francisco",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Bajo",
    "postal_code": "04001",
    "city": "Almería",
    "country": "ES",
    "notes": "leading-zero CP 04; word-floor Bajo; accent"
  },
  {
    "input": "Paseo de Almería, 50, 04001 Almería",
    "number": "50",
    "street": "de Almería",
    "type": "Paseo",
    "postal_code": "04001",
    "city": "Almería",
    "country": "ES",
    "notes": "Paseo; leading-zero CP 04"
  },
  {
    "input": "Calle Nervión, 12, 41005 Sevilla",
    "number": "12",
    "street": "Nervión",
    "type": "Calle",
    "postal_code": "41005",
    "city": "Sevilla",
    "country": "ES",
    "notes": "accent in Nervión"
  },
  {
    "input": "Calle del Puig, 3, 08922 Santa Coloma de Gramenet (Barcelona)",
    "number": "3",
    "street": "del Puig",
    "type": "Calle",
    "postal_code": "08922",
    "city": "Santa Coloma de Gramenet",
    "state": "Barcelona",
    "country": "ES",
    "notes": "long multiword city; province in parens"
  },
  {
    "input": "Avenida Blasco Ibáñez, 21, 46010 Valencia",
    "number": "21",
    "street": "Blasco Ibáñez",
    "type": "Avenida",
    "postal_code": "46010",
    "city": "Valencia",
    "country": "ES",
    "notes": "ñ and accent in Ibáñez"
  },
  {
    "input": "Calle Doctor Fleming, 8, 3.º Centro, 30204 Cartagena (Murcia)",
    "number": "8",
    "street": "Doctor Fleming",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3.º Centro",
    "postal_code": "30204",
    "city": "Cartagena",
    "state": "Murcia",
    "country": "ES",
    "notes": "floor + Centro door position; province in parens"
  },
  {
    "input": "Calle de Génova, 13, 28004 Madrid",
    "number": "13",
    "street": "de Génova",
    "type": "Calle",
    "postal_code": "28004",
    "city": "Madrid",
    "country": "ES",
    "notes": "accent in Génova"
  },
  {
    "input": "Calle Colón, 1, Bloque 2, 4.º A, 29016 Málaga",
    "__skip": "stacked multiple secondary units",
    "number": "1",
    "street": "Colón",
    "type": "Calle",
    "sec_unit_type": "Bloque",
    "sec_unit_num": "2, 4.º A",
    "postal_code": "29016",
    "city": "Málaga",
    "country": "ES",
    "notes": "bloque + floor + door chain"
  },
  {
    "input": "Avenida Andalucía, 5, 5, 23003 Jaén",
    "__skip": "bare trailing number as door (ambiguous)",
    "number": "5",
    "street": "Andalucía",
    "type": "Avenida",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "5",
    "postal_code": "23003",
    "city": "Jaén",
    "country": "ES",
    "notes": "ambiguous: number then bare door number both 5; accent"
  },
  {
    "input": "Plaza de los Naranjos, 1, 29601 Marbella (Málaga)",
    "number": "1",
    "street": "de los Naranjos",
    "type": "Plaza",
    "postal_code": "29601",
    "city": "Marbella",
    "state": "Málaga",
    "country": "ES",
    "notes": "particle de los; province in parens"
  },
  {
    "input": "Calle Cronista Carreres, 9, 46003 València",
    "number": "9",
    "street": "Cronista Carreres",
    "type": "Calle",
    "postal_code": "46003",
    "city": "València",
    "country": "ES",
    "notes": "Castilian Calle with Valencian city spelling"
  },
  {
    "input": "Calle Real, s/n, Edificio A, 39001 Santander (Cantabria)",
    "__skip": "stacked unit (s/n + edificio)",
    "street": "Real",
    "type": "Calle",
    "sec_unit_type": "Edificio",
    "sec_unit_num": "A",
    "postal_code": "39001",
    "city": "Santander",
    "state": "Cantabria",
    "country": "ES",
    "notes": "s/n + Edificio; province Cantabria (code 39, != capital)"
  },
  {
    "input": "Calle Burgos, 5, 09003 Burgos",
    "number": "5",
    "street": "Burgos",
    "type": "Calle",
    "postal_code": "09003",
    "city": "Burgos",
    "country": "ES",
    "notes": "leading-zero CP 09; city == province, no parens"
  },
  {
    "input": "Avenida de la Ilustración, 2, 5.º, 28010 Madrid",
    "number": "2",
    "street": "de la Ilustración",
    "type": "Avenida",
    "sec_unit_type": "Piso",
    "sec_unit_num": "5.º",
    "postal_code": "28010",
    "city": "Madrid",
    "country": "ES",
    "notes": "accent; floor only"
  },
  {
    "input": "Calle San Jerónimo, 22, 4, 14003 Córdoba",
    "__skip": "bare trailing number as door (ambiguous)",
    "number": "22",
    "street": "San Jerónimo",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "4",
    "postal_code": "14003",
    "city": "Córdoba",
    "country": "ES",
    "notes": "bare door number after comma; accents"
  },
  {
    "input": "Calle Cruz Conde, 15, 14008 Córdoba",
    "number": "15",
    "street": "Cruz Conde",
    "type": "Calle",
    "postal_code": "14008",
    "city": "Córdoba",
    "country": "ES",
    "notes": "normal"
  },
  {
    "input": "Plaça del Mercadal, 1, 43201 Reus (Tarragona)",
    "number": "1",
    "street": "del Mercadal",
    "type": "Plaça",
    "postal_code": "43201",
    "city": "Reus",
    "state": "Tarragona",
    "country": "ES",
    "notes": "Catalan Plaça; province in parens"
  },
  {
    "input": "Calle Sol, 2, 2º dcha, 47002 Valladolid",
    "number": "2",
    "street": "Sol",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "2º dcha",
    "postal_code": "47002",
    "city": "Valladolid",
    "country": "ES",
    "notes": "lowercase dcha, degree-style ordinal without period"
  },
  {
    "input": "Avenida Juan Carlos I, 12, 30008 Murcia",
    "number": "12",
    "street": "Juan Carlos I",
    "type": "Avenida",
    "postal_code": "30008",
    "city": "Murcia",
    "country": "ES",
    "notes": "Roman numeral I in name (not a floor)"
  },
  {
    "input": "Calle Alfonso XII, 30, 41002 Sevilla",
    "number": "30",
    "street": "Alfonso XII",
    "type": "Calle",
    "postal_code": "41002",
    "city": "Sevilla",
    "country": "ES",
    "notes": "Roman numeral XII part of name"
  },
  {
    "input": "Calle 2 de Mayo, 15, 28935 Móstoles (Madrid)",
    "__skip": "leading digit inside name in street-first order",
    "number": "15",
    "street": "2 de Mayo",
    "type": "Calle",
    "postal_code": "28935",
    "city": "Móstoles",
    "state": "Madrid",
    "country": "ES",
    "notes": "leading digit in street NAME (2 de Mayo); real civic number is 15"
  },
  {
    "input": "Calle Primero de Mayo, 8, 28850 Torrejón de Ardoz (Madrid)",
    "number": "8",
    "street": "Primero de Mayo",
    "type": "Calle",
    "postal_code": "28850",
    "city": "Torrejón de Ardoz",
    "state": "Madrid",
    "country": "ES",
    "notes": "number-word in name; province in parens"
  },
  {
    "input": "Avenida del Mediterráneo, 42, 8.º, 46023 Valencia",
    "number": "42",
    "street": "del Mediterráneo",
    "type": "Avenida",
    "sec_unit_type": "Piso",
    "sec_unit_num": "8.º",
    "postal_code": "46023",
    "city": "Valencia",
    "country": "ES",
    "notes": "accent; floor only"
  },
  {
    "input": "Calle del Turia, 5, 12001 Castelló de la Plana (Castelló)",
    "number": "5",
    "street": "del Turia",
    "type": "Calle",
    "postal_code": "12001",
    "city": "Castelló de la Plana",
    "state": "Castelló",
    "country": "ES",
    "notes": "Valencian city/province Castelló (code 12); multiword city"
  },
  {
    "input": "Carrer Major, 20, 12001 Castelló de la Plana",
    "number": "20",
    "street": "Major",
    "type": "Carrer",
    "postal_code": "12001",
    "city": "Castelló de la Plana",
    "country": "ES",
    "notes": "Valencian Carrer; multiword city"
  },
  {
    "input": "Avenida de los Reyes Católicos, s/n, 28040 Madrid",
    "street": "de los Reyes Católicos",
    "type": "Avenida",
    "postal_code": "28040",
    "city": "Madrid",
    "country": "ES",
    "notes": "s/n; particle de los; accent"
  },
  {
    "input": "Calle Mayor, 1, 5.º izq., 42001 Soria",
    "number": "1",
    "street": "Mayor",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "5.º izq.",
    "postal_code": "42001",
    "city": "Soria",
    "country": "ES",
    "notes": "izq. short form for izquierda"
  },
  {
    "input": "Calle Obispo, 10, 5, 24003 León",
    "__skip": "bare trailing number as door (ambiguous)",
    "number": "10",
    "street": "obispo",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "5",
    "postal_code": "24003",
    "city": "León",
    "country": "ES",
    "notes": "lowercase name (messy); bare door; accent in León"
  },
  {
    "input": "Avinguda Catedral, 6, Bxs, 08002 Barcelona",
    "number": "6",
    "street": "Catedral",
    "type": "Avinguda",
    "sec_unit_type": "Piso",
    "sec_unit_num": "Bxs",
    "postal_code": "08002",
    "city": "Barcelona",
    "country": "ES",
    "notes": "Catalan Baixos abbreviated Bxs (ground floor)"
  },
  {
    "input": "Calle San Bernardo, 62, 2, 28015 Madrid",
    "__skip": "bare trailing number as door (ambiguous)",
    "number": "62",
    "street": "San Bernardo",
    "type": "Calle",
    "sec_unit_type": "Puerta",
    "sec_unit_num": "2",
    "postal_code": "28015",
    "city": "Madrid",
    "country": "ES",
    "notes": "number then bare unit number"
  },
  {
    "input": "Calle Larios 5 3 D, 29005 Málaga",
    "number": "5",
    "street": "Larios",
    "type": "Calle",
    "sec_unit_type": "Piso",
    "sec_unit_num": "3 D",
    "postal_code": "29005",
    "city": "Málaga",
    "country": "ES",
    "notes": "no commas at all; number 5, floor 3, door D (space separated)"
  }
];
