// AUTO-GENERATED from research sub-agent corpus (samples-fi.json).
// Ground-truth field breakdowns for FI addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const fiSamples: EuSample[] = [
  {
    "input": "Mannerheimintie 12, 00100 Helsinki",
    "number": "12",
    "street": "Mannerheimin",
    "type": "tie",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tie"
  },
  {
    "input": "Aleksanterinkatu 52, 00100 Helsinki",
    "number": "52",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu (Stockmann)"
  },
  {
    "input": "Mannerheimintie 9, 00100 Helsinki",
    "number": "9",
    "street": "Mannerheimin",
    "type": "tie",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tie"
  },
  {
    "input": "Keskuskatu 3, 00100 Helsinki",
    "number": "3",
    "street": "Keskus",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Yliopistonkatu 5, 00100 Helsinki",
    "number": "5",
    "street": "Yliopiston",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Fabianinkatu 14, 00100 Helsinki",
    "number": "14",
    "street": "Fabianin",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Unioninkatu 20, 00170 Helsinki",
    "number": "20",
    "street": "Unionin",
    "type": "katu",
    "postal_code": "00170",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Yrjönkatu 27, 00100 Helsinki",
    "number": "27",
    "street": "Yrjön",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu, o-with-umlaut? no"
  },
  {
    "input": "Kaisaniemenkatu 3, 00100 Helsinki",
    "number": "3",
    "street": "Kaisaniemen",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu, long compound"
  },
  {
    "input": "Bulevardi 12, 00120 Helsinki",
    "number": "12",
    "street": "Bulevardi",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "single-word name, no fused type -> type null"
  },
  {
    "input": "Simonkatu 6, 00100 Helsinki",
    "number": "6",
    "street": "Simon",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Runeberginkatu 5, 00100 Helsinki",
    "number": "5",
    "street": "Runebergin",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Museokatu 10, 00100 Helsinki",
    "number": "10",
    "street": "Museo",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Hämeentie 19, 00530 Helsinki",
    "number": "19",
    "street": "Hämeen",
    "type": "tie",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "a-umlaut in name, fused -tie"
  },
  {
    "input": "Töölönkatu 4, 00100 Helsinki",
    "number": "4",
    "street": "Töölön",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "o-umlaut in name, fused -katu"
  },
  {
    "input": "Mäkelänkatu 25, 00550 Helsinki",
    "number": "25",
    "street": "Mäkelän",
    "type": "katu",
    "postal_code": "00550",
    "city": "Helsinki",
    "country": "FI",
    "notes": "a-umlaut, fused -katu"
  },
  {
    "input": "Näkinkuja 2, 00530 Helsinki",
    "number": "2",
    "street": "Näkin",
    "type": "kuja",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "a-umlaut, fused -kuja"
  },
  {
    "input": "Läntinen Brahenkatu 2, 00510 Helsinki",
    "number": "2",
    "street": "Läntinen Brahen",
    "type": "katu",
    "postal_code": "00510",
    "city": "Helsinki",
    "country": "FI",
    "notes": "multiword with leading adjective, a-umlaut"
  },
  {
    "input": "Fredrikinkatu 63, 00100 Helsinki",
    "number": "63",
    "street": "Fredrikin",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu"
  },
  {
    "input": "Mannerheimintie 12 A 5, 00100 Helsinki",
    "number": "12",
    "street": "Mannerheimin",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 5",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell A + apartment 5"
  },
  {
    "input": "Mäkelänkatu 25 B 13, 00550 Helsinki",
    "number": "25",
    "street": "Mäkelän",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 13",
    "postal_code": "00550",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell B + apartment 13"
  },
  {
    "input": "Hämeentie 19 C 44, 00530 Helsinki",
    "number": "19",
    "street": "Hämeen",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "C 44",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell C + apartment"
  },
  {
    "input": "Runeberginkatu 5 A 2, 00100 Helsinki",
    "number": "5",
    "street": "Runebergin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 2",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell A + apartment"
  },
  {
    "input": "Fabianinkatu 14 D 7, 00100 Helsinki",
    "number": "14",
    "street": "Fabianin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "D 7",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell D + apartment"
  },
  {
    "input": "Bulevardi 12 A 1, 00120 Helsinki",
    "number": "12",
    "street": "Bulevardi",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 1",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "type null + stairwell/apartment"
  },
  {
    "input": "Koekatu 5 as. 4, 00520 Helsinki",
    "number": "5",
    "street": "Koe",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "4",
    "postal_code": "00520",
    "city": "Helsinki",
    "country": "FI",
    "notes": "as. apartment marker, no stairwell"
  },
  {
    "input": "Kuusikkotie 1 as. 12, 00630 Helsinki",
    "number": "1",
    "street": "Kuusikko",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "12",
    "postal_code": "00630",
    "city": "Helsinki",
    "country": "FI",
    "notes": "as. apartment marker"
  },
  {
    "input": "Metsäpolku 3 as 8, 00630 Helsinki",
    "number": "3",
    "street": "Metsä",
    "type": "polku",
    "sec_unit_type": "as.",
    "sec_unit_num": "8",
    "postal_code": "00630",
    "city": "Helsinki",
    "country": "FI",
    "notes": "as (no dot) apartment marker, fused -polku"
  },
  {
    "input": "Pihakuja 7 as. 3, 00840 Helsinki",
    "number": "7",
    "street": "Piha",
    "type": "kuja",
    "sec_unit_type": "as.",
    "sec_unit_num": "3",
    "postal_code": "00840",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -kuja + as. apartment"
  },
  {
    "input": "Kalliotie 11 as. 5, 00760 Helsinki",
    "number": "11",
    "street": "Kallio",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "5",
    "postal_code": "00760",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tie + as. apartment"
  },
  {
    "input": "Kehrääjänkatu 6-8, 33100 Tampere",
    "number": "6-8",
    "street": "Kehrääjän",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "house number range 6-8, a-umlaut"
  },
  {
    "input": "Aleksanterinkatu 12-14, 00170 Helsinki",
    "number": "12-14",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "00170",
    "city": "Helsinki",
    "country": "FI",
    "notes": "house number range"
  },
  {
    "input": "Kalliotie 11a, 00760 Helsinki",
    "number": "11",
    "civic_number_suffix": "a",
    "street": "Kallio",
    "type": "tie",
    "postal_code": "00760",
    "city": "Helsinki",
    "country": "FI",
    "notes": "civic-number suffix lowercase a"
  },
  {
    "input": "Museokatu 8 b, 00100 Helsinki",
    "number": "8",
    "civic_number_suffix": "b",
    "street": "Museo",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "civic suffix lowercase b with space"
  },
  {
    "input": "Majankulmantie 160/10, 00890 Helsinki",
    "number": "160/10",
    "street": "Majankulman",
    "type": "tie",
    "postal_code": "00890",
    "city": "Helsinki",
    "country": "FI",
    "notes": "slash block form 160/10"
  },
  {
    "input": "Hämeenkatu 6-8 B 12, 33200 Tampere",
    "number": "6-8",
    "street": "Hämeen",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 12",
    "postal_code": "33200",
    "city": "Tampere",
    "country": "FI",
    "notes": "range + stairwell/apartment combined"
  },
  {
    "input": "Itäväylä 3, 00930 Helsinki",
    "number": "3",
    "street": "Itä",
    "type": "väylä",
    "postal_code": "00930",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -väylä, a-umlaut"
  },
  {
    "input": "Kaisaniemenranta 4, 00100 Helsinki",
    "number": "4",
    "street": "Kaisaniemen",
    "type": "ranta",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -ranta"
  },
  {
    "input": "Eteläranta 10, 00130 Helsinki",
    "number": "10",
    "street": "Etelä",
    "type": "ranta",
    "postal_code": "00130",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -ranta"
  },
  {
    "input": "Siltasaarenkatu 18, 00530 Helsinki",
    "number": "18",
    "street": "Siltasaaren",
    "type": "katu",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -katu, long compound"
  },
  {
    "input": "Kauppatori 1, 00170 Helsinki",
    "number": "1",
    "street": "Kauppa",
    "type": "tori",
    "postal_code": "00170",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tori (square)"
  },
  {
    "input": "Rautatientori 2, 00100 Helsinki",
    "number": "2",
    "street": "Rautatien",
    "type": "tori",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tori, long compound"
  },
  {
    "input": "Kirkkoraitti 5, 00700 Helsinki",
    "number": "5",
    "street": "Kirkko",
    "type": "raitti",
    "postal_code": "00700",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -raitti (W. Finland)"
  },
  {
    "input": "Töölönlahdenkatu 3, 00100 Helsinki",
    "number": "3",
    "street": "Töölönlahden",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "very long fused compound + o-umlaut"
  },
  {
    "input": "Untamonrinne 4, 00610 Helsinki",
    "number": "4",
    "street": "Untamon",
    "type": "rinne",
    "postal_code": "00610",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -rinne (slope)"
  },
  {
    "input": "Siltasaarenpenger 1, 00530 Helsinki",
    "number": "1",
    "street": "Siltasaaren",
    "type": "penger",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -penger (embankment)"
  },
  {
    "input": "Merikaari 8, 00980 Helsinki",
    "number": "8",
    "street": "Meri",
    "type": "kaari",
    "postal_code": "00980",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -kaari (arc)"
  },
  {
    "input": "Kaunispolku 6, 00760 Helsinki",
    "number": "6",
    "street": "Kaunis",
    "type": "polku",
    "postal_code": "00760",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -polku (path)"
  },
  {
    "input": "Kalevankuja 2, 00100 Helsinki",
    "number": "2",
    "street": "Kalevan",
    "type": "kuja",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -kuja (alley)"
  },
  {
    "input": "Pitkäsilta 1, 00530 Helsinki",
    "number": "1",
    "street": "Pitkä",
    "type": "silta",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -silta (bridge)"
  },
  {
    "input": "Makasiinilaituri 4, 00130 Helsinki",
    "number": "4",
    "street": "Makasiini",
    "type": "laituri",
    "postal_code": "00130",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -laituri (quay)"
  },
  {
    "input": "Toinen linja 7, 00530 Helsinki",
    "number": "7",
    "street": "Toinen linja",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "separate-word type 'linja', ordinal name -> keep whole, type null"
  },
  {
    "input": "Neljäs linja 3, 00530 Helsinki",
    "number": "3",
    "street": "Neljäs linja",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "separate-word type, a-umlaut, type null"
  },
  {
    "input": "Viides linja 12, 00530 Helsinki",
    "number": "12",
    "street": "Viides linja",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "separate-word 'linja'"
  },
  {
    "input": "Aleksis Kiven katu 17, 00500 Helsinki",
    "number": "17",
    "street": "Aleksis Kiven",
    "type": "katu",
    "postal_code": "00500",
    "city": "Helsinki",
    "country": "FI",
    "notes": "multiword name, separate 'katu' token"
  },
  {
    "input": "Iso Roobertinkatu 21, 00120 Helsinki",
    "number": "21",
    "street": "Iso Roobertin",
    "type": "katu",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "leading adjective 'Iso' + fused -katu"
  },
  {
    "input": "Pohjoinen Rautatiekatu 25, 00100 Helsinki",
    "number": "25",
    "street": "Pohjoinen Rautatie",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "multiword with fused -katu on final word"
  },
  {
    "input": "Kolmen sepän aukio 1, 00100 Helsinki",
    "number": "1",
    "street": "Kolmen sepän aukio",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "multiword 'aukio' separate -> keep whole"
  },
  {
    "input": "Tapiontori 3, 02100 Espoo",
    "number": "3",
    "street": "Tapion",
    "type": "tori",
    "postal_code": "02100",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo, fused -tori"
  },
  {
    "input": "Länsituulentie 10, 02100 Espoo",
    "number": "10",
    "street": "Länsituulen",
    "type": "tie",
    "postal_code": "02100",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo, a-umlaut, fused -tie"
  },
  {
    "input": "Merituulentie 24 A 3, 02100 Espoo",
    "number": "24",
    "street": "Merituulen",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 3",
    "postal_code": "02100",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo, stairwell+apartment"
  },
  {
    "input": "Kauppamiehentie 1, 02100 Espoo",
    "number": "1",
    "street": "Kauppamiehen",
    "type": "tie",
    "postal_code": "02100",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo, long fused compound"
  },
  {
    "input": "Piispansilta 11, 02230 Espoo",
    "number": "11",
    "street": "Piispan",
    "type": "silta",
    "postal_code": "02230",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo, fused -silta"
  },
  {
    "input": "Otakaari 1, 02150 Espoo",
    "number": "1",
    "street": "Ota",
    "type": "kaari",
    "postal_code": "02150",
    "city": "Espoo",
    "country": "FI",
    "notes": "Espoo Otaniemi, fused -kaari"
  },
  {
    "input": "Tikkurilantie 44, 01300 Vantaa",
    "number": "44",
    "street": "Tikkurilan",
    "type": "tie",
    "postal_code": "01300",
    "city": "Vantaa",
    "country": "FI",
    "notes": "Vantaa, fused -tie"
  },
  {
    "input": "Peltolantie 2 B 8, 01300 Vantaa",
    "number": "2",
    "street": "Peltolan",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 8",
    "postal_code": "01300",
    "city": "Vantaa",
    "country": "FI",
    "notes": "Vantaa, stairwell+apartment"
  },
  {
    "input": "Unikkotie 5, 01300 Vantaa",
    "number": "5",
    "street": "Unikko",
    "type": "tie",
    "postal_code": "01300",
    "city": "Vantaa",
    "country": "FI",
    "notes": "Vantaa, fused -tie"
  },
  {
    "input": "Lummetie 3 as. 14, 01300 Vantaa",
    "number": "3",
    "street": "Lumme",
    "type": "tie",
    "sec_unit_type": "as.",
    "sec_unit_num": "14",
    "postal_code": "01300",
    "city": "Vantaa",
    "country": "FI",
    "notes": "Vantaa, as. apartment"
  },
  {
    "input": "Hämeenkatu 14, 33100 Tampere",
    "number": "14",
    "street": "Hämeen",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere main street, a-umlaut"
  },
  {
    "input": "Hämeenkatu 14 A 5, 33100 Tampere",
    "number": "14",
    "street": "Hämeen",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 5",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere, stairwell+apartment"
  },
  {
    "input": "Satakunnankatu 18, 33210 Tampere",
    "number": "18",
    "street": "Satakunnan",
    "type": "katu",
    "postal_code": "33210",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere, fused -katu"
  },
  {
    "input": "Pyynikintie 25, 33230 Tampere",
    "number": "25",
    "street": "Pyynikin",
    "type": "tie",
    "postal_code": "33230",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere, fused -tie"
  },
  {
    "input": "Aleksanterinkatu 20, 33100 Tampere",
    "number": "20",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere, fused -katu"
  },
  {
    "input": "Rautatienkatu 10, 33100 Tampere",
    "number": "10",
    "street": "Rautatien",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "Tampere, fused -katu"
  },
  {
    "input": "Yliopistonkatu 29, 20100 Turku",
    "number": "29",
    "street": "Yliopiston",
    "type": "katu",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, fused -katu"
  },
  {
    "input": "Aurakatu 12, 20100 Turku",
    "number": "12",
    "street": "Aura",
    "type": "katu",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, fused -katu"
  },
  {
    "input": "Kauppiaskatu 5 B 22, 20100 Turku",
    "number": "5",
    "street": "Kauppias",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 22",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, stairwell+apartment"
  },
  {
    "input": "Hämeenkatu 8, 20500 Turku",
    "number": "8",
    "street": "Hämeen",
    "type": "katu",
    "postal_code": "20500",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, fused -katu, a-umlaut"
  },
  {
    "input": "Eerikinkatu 15, 20100 Turku",
    "number": "15",
    "street": "Eerikin",
    "type": "katu",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, fused -katu"
  },
  {
    "input": "Alexandersgatan 44, 00100 Helsingfors",
    "number": "44",
    "street": "Alexanders",
    "type": "gatan",
    "postal_code": "00100",
    "city": "Helsingfors",
    "country": "FI",
    "notes": "Swedish fused -gatan, bilingual city Helsingfors"
  },
  {
    "input": "Mannerheimvägen 5, 00100 Helsingfors",
    "number": "5",
    "street": "Mannerheim",
    "type": "vägen",
    "postal_code": "00100",
    "city": "Helsingfors",
    "country": "FI",
    "notes": "Swedish fused -vägen, a-umlaut, Helsingfors"
  },
  {
    "input": "Skillnadsgatan 3, 00130 Helsingfors",
    "number": "3",
    "street": "Skillnads",
    "type": "gatan",
    "postal_code": "00130",
    "city": "Helsingfors",
    "country": "FI",
    "notes": "Swedish fused -gatan"
  },
  {
    "input": "Norra Esplanaden 25, 00100 Helsingfors",
    "number": "25",
    "street": "Norra Esplanaden",
    "postal_code": "00100",
    "city": "Helsingfors",
    "country": "FI",
    "notes": "Swedish esplanade, multiword, type null"
  },
  {
    "input": "Storgatan 12 A 4, 06100 Borgå",
    "number": "12",
    "street": "Stor",
    "type": "gatan",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 4",
    "postal_code": "06100",
    "city": "Borgå",
    "country": "FI",
    "notes": "Swedish -gatan + stairwell/apartment, Borgå (Porvoo)"
  },
  {
    "input": "Strandvägen 8, 22100 Mariehamn",
    "number": "8",
    "street": "Strand",
    "type": "vägen",
    "postal_code": "22100",
    "city": "Mariehamn",
    "country": "FI",
    "notes": "Aland Islands (Swedish), fused -vägen"
  },
  {
    "input": "Torggatan 2, 65100 Vasa",
    "number": "2",
    "street": "Torg",
    "type": "gatan",
    "postal_code": "65100",
    "city": "Vasa",
    "country": "FI",
    "notes": "Vasa (Vaasa), Swedish -gatan"
  },
  {
    "input": "Köpmansgatan 10, 68600 Jakobstad",
    "number": "10",
    "street": "Köpmans",
    "type": "gatan",
    "postal_code": "68600",
    "city": "Jakobstad",
    "country": "FI",
    "notes": "Swedish -gatan, o-umlaut, Jakobstad"
  },
  {
    "input": "Kauppatori 5, 20100 Turku",
    "number": "5",
    "street": "Kauppa",
    "type": "tori",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku (Abo) Finnish form"
  },
  {
    "input": "Pohjoisesplanadi 21, 00100 Helsinki",
    "number": "21",
    "street": "Pohjoisesplanadi",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "esplanadi as name, type null"
  },
  {
    "input": "Rantakatu 9, 65100 Vaasa",
    "number": "9",
    "street": "Ranta",
    "type": "katu",
    "postal_code": "65100",
    "city": "Vaasa",
    "country": "FI",
    "notes": "Vaasa (Vasa) Finnish form"
  },
  {
    "input": "Raatihuoneenkatu 3, 06100 Porvoo",
    "number": "3",
    "street": "Raatihuoneen",
    "type": "katu",
    "postal_code": "06100",
    "city": "Porvoo",
    "country": "FI",
    "notes": "Porvoo (Borga) Finnish form, long compound"
  },
  {
    "input": "Kirkkokatu 3, 90100 Oulu",
    "number": "3",
    "street": "Kirkko",
    "type": "katu",
    "postal_code": "90100",
    "city": "Oulu",
    "country": "FI",
    "notes": "Oulu, fused -katu"
  },
  {
    "input": "Isokatu 22, 90100 Oulu",
    "number": "22",
    "street": "Iso",
    "type": "katu",
    "postal_code": "90100",
    "city": "Oulu",
    "country": "FI",
    "notes": "Oulu, fused -katu"
  },
  {
    "input": "Kauppurienkatu 10 A 3, 90100 Oulu",
    "number": "10",
    "street": "Kauppurien",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 3",
    "postal_code": "90100",
    "city": "Oulu",
    "country": "FI",
    "notes": "Oulu, stairwell+apartment"
  },
  {
    "input": "Kauppakatu 18, 40100 Jyväskylä",
    "number": "18",
    "street": "Kauppa",
    "type": "katu",
    "postal_code": "40100",
    "city": "Jyväskylä",
    "country": "FI",
    "notes": "Jyvaskyla, a-umlaut in city"
  },
  {
    "input": "Yliopistonkatu 38, 40100 Jyväskylä",
    "number": "38",
    "street": "Yliopiston",
    "type": "katu",
    "postal_code": "40100",
    "city": "Jyväskylä",
    "country": "FI",
    "notes": "Jyvaskyla, fused -katu"
  },
  {
    "input": "Vapaudenkatu 48 B 7, 40100 Jyväskylä",
    "number": "48",
    "street": "Vapauden",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 7",
    "postal_code": "40100",
    "city": "Jyväskylä",
    "country": "FI",
    "notes": "Jyvaskyla, stairwell+apartment"
  },
  {
    "input": "Kauppakatu 42, 70100 Kuopio",
    "number": "42",
    "street": "Kauppa",
    "type": "katu",
    "postal_code": "70100",
    "city": "Kuopio",
    "country": "FI",
    "notes": "Kuopio, fused -katu"
  },
  {
    "input": "Puijonkatu 29, 70100 Kuopio",
    "number": "29",
    "street": "Puijon",
    "type": "katu",
    "postal_code": "70100",
    "city": "Kuopio",
    "country": "FI",
    "notes": "Kuopio, fused -katu"
  },
  {
    "input": "Aleksanterinkatu 18, 15110 Lahti",
    "number": "18",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "15110",
    "city": "Lahti",
    "country": "FI",
    "notes": "Lahti, fused -katu"
  },
  {
    "input": "Vesijärvenkatu 11, 15140 Lahti",
    "number": "11",
    "street": "Vesijärven",
    "type": "katu",
    "postal_code": "15140",
    "city": "Lahti",
    "country": "FI",
    "notes": "Lahti, a-umlaut, long compound"
  },
  {
    "input": "Valtakatu 37, 53100 Lappeenranta",
    "number": "37",
    "street": "Valta",
    "type": "katu",
    "postal_code": "53100",
    "city": "Lappeenranta",
    "country": "FI",
    "notes": "Lappeenranta, fused -katu"
  },
  {
    "input": "Kauppakatu 40, 80100 Joensuu",
    "number": "40",
    "street": "Kauppa",
    "type": "katu",
    "postal_code": "80100",
    "city": "Joensuu",
    "country": "FI",
    "notes": "Joensuu, fused -katu"
  },
  {
    "input": "Hallituskatu 7, 96200 Rovaniemi",
    "number": "7",
    "street": "Hallitus",
    "type": "katu",
    "postal_code": "96200",
    "city": "Rovaniemi",
    "country": "FI",
    "notes": "Rovaniemi (Lapland), fused -katu"
  },
  {
    "input": "Koskikatu 9, 96200 Rovaniemi",
    "number": "9",
    "street": "Koski",
    "type": "katu",
    "postal_code": "96200",
    "city": "Rovaniemi",
    "country": "FI",
    "notes": "Rovaniemi, fused -katu"
  },
  {
    "input": "Keskuskatu 15, 28100 Pori",
    "number": "15",
    "street": "Keskus",
    "type": "katu",
    "postal_code": "28100",
    "city": "Pori",
    "country": "FI",
    "notes": "Pori, fused -katu"
  },
  {
    "input": "Kirkkokatu 12 A 8, 48100 Kotka",
    "number": "12",
    "street": "Kirkko",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 8",
    "postal_code": "48100",
    "city": "Kotka",
    "country": "FI",
    "notes": "Kotka, stairwell+apartment"
  },
  {
    "input": "Satamakatu 5, 87100 Kajaani",
    "number": "5",
    "street": "Satama",
    "type": "katu",
    "postal_code": "87100",
    "city": "Kajaani",
    "country": "FI",
    "notes": "Kajaani, fused -katu"
  },
  {
    "input": "Torikatu 20, 90100 Oulu",
    "number": "20",
    "street": "Tori",
    "type": "katu",
    "postal_code": "90100",
    "city": "Oulu",
    "country": "FI",
    "notes": "Oulu, fused -katu"
  },
  {
    "input": "Asemakatu 6, 50100 Mikkeli",
    "number": "6",
    "street": "Asema",
    "type": "katu",
    "postal_code": "50100",
    "city": "Mikkeli",
    "country": "FI",
    "notes": "Mikkeli, fused -katu"
  },
  {
    "input": "Linnankatu 32, 20100 Turku",
    "number": "32",
    "street": "Linnan",
    "type": "katu",
    "postal_code": "20100",
    "city": "Turku",
    "country": "FI",
    "notes": "Turku, fused -katu"
  },
  {
    "input": "Mannerheimintie 100, FI-00250 HELSINKI",
    "number": "100",
    "street": "Mannerheimin",
    "type": "tie",
    "postal_code": "00250",
    "city": "HELSINKI",
    "country": "FI",
    "notes": "FI- postal prefix, UPPERCASE city"
  },
  {
    "input": "Aleksanterinkatu 9, FI-00170 Helsinki",
    "number": "9",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "00170",
    "city": "Helsinki",
    "country": "FI",
    "notes": "FI- postal prefix stripped"
  },
  {
    "input": "Hämeenkatu 25, FIN-33100 TAMPERE",
    "number": "25",
    "street": "Hämeen",
    "type": "katu",
    "postal_code": "33100",
    "city": "TAMPERE",
    "country": "FI",
    "notes": "legacy FIN- prefix, UPPERCASE city"
  },
  {
    "input": "PORTHANINKATU 9 B 2, 00530 HELSINKI",
    "__skip": "all-caps case-normalization stress variant",
    "number": "9",
    "street": "Porthanin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 2",
    "postal_code": "00530",
    "city": "Helsinki",
    "country": "FI",
    "notes": "all-uppercase envelope style"
  },
  {
    "input": "Mannerheimintie 15, 00100 Helsinki, Suomi",
    "number": "15",
    "street": "Mannerheimin",
    "type": "tie",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "country 'Suomi' -> FI"
  },
  {
    "input": "Aleksanterinkatu 30, 00100 Helsinki, Finland",
    "number": "30",
    "street": "Aleksanterin",
    "type": "katu",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "country 'Finland' -> FI"
  },
  {
    "input": "Hämeenkatu 5, 33100 Tampere, FINLAND",
    "number": "5",
    "street": "Hämeen",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "country 'FINLAND' -> FI"
  },
  {
    "input": "Bulevardi 7, 3 krs, 00120 Helsinki",
    "__skip": "floor marker (krs) dropped in ground truth",
    "number": "7",
    "street": "Bulevardi",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "'3 krs' is floor not apartment; ignore as sec unit"
  },
  {
    "input": "Kaisaniemenkatu 1 A, 4 krs, 00100 Helsinki",
    "__skip": "stairwell + separate floor marker (krs)",
    "number": "1",
    "street": "Kaisaniemen",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell A only; krs floor is noise"
  },
  {
    "input": "Storgatan 4 bst 6, 06100 Borgå",
    "number": "4",
    "street": "Stor",
    "type": "gatan",
    "sec_unit_type": "as.",
    "sec_unit_num": "6",
    "postal_code": "06100",
    "city": "Borgå",
    "country": "FI",
    "notes": "Swedish 'bst' (bostad) apartment marker"
  },
  {
    "input": "Strandvägen 2 A bostad 9, 22100 Mariehamn",
    "__skip": "stairwell + bostad stacked unit",
    "number": "2",
    "street": "Strand",
    "type": "vägen",
    "sec_unit_type": "as.",
    "sec_unit_num": "A bostad 9",
    "postal_code": "22100",
    "city": "Mariehamn",
    "country": "FI",
    "notes": "Swedish 'bostad' apartment with stairwell"
  },
  {
    "input": "Vanhanlinnantie 3, 00900 Helsinki",
    "number": "3",
    "street": "Vanhanlinnan",
    "type": "tie",
    "postal_code": "00900",
    "city": "Helsinki",
    "country": "FI",
    "notes": "long single-token compound, fused -tie"
  },
  {
    "input": "Kolmirinteentie 8, 00390 Helsinki",
    "number": "8",
    "street": "Kolmirinteen",
    "type": "tie",
    "postal_code": "00390",
    "city": "Helsinki",
    "country": "FI",
    "notes": "long single-token compound"
  },
  {
    "input": "Ratapihankatu 47, 33100 Tampere",
    "number": "47",
    "street": "Ratapihan",
    "type": "katu",
    "postal_code": "33100",
    "city": "Tampere",
    "country": "FI",
    "notes": "long single-token compound, fused -katu"
  },
  {
    "input": "Pikkukoskenpolku 5, 00650 Helsinki",
    "number": "5",
    "street": "Pikkukosken",
    "type": "polku",
    "postal_code": "00650",
    "city": "Helsinki",
    "country": "FI",
    "notes": "long compound, fused -polku"
  },
  {
    "input": "Kolmisointukuja 2, 00420 Helsinki",
    "number": "2",
    "street": "Kolmisointu",
    "type": "kuja",
    "postal_code": "00420",
    "city": "Helsinki",
    "country": "FI",
    "notes": "long compound, fused -kuja"
  },
  {
    "input": "Esplanadi 4, 00130 Helsinki",
    "number": "4",
    "street": "Esplanadi",
    "postal_code": "00130",
    "city": "Helsinki",
    "country": "FI",
    "notes": "single-word name, no fused type"
  },
  {
    "input": "Kaivopiha 1, 00100 Helsinki",
    "number": "1",
    "street": "Kaivopiha",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "single-word name, type null"
  },
  {
    "input": "Senaatintori 3, 00170 Helsinki",
    "number": "3",
    "street": "Senaatin",
    "type": "tori",
    "postal_code": "00170",
    "city": "Helsinki",
    "country": "FI",
    "notes": "fused -tori"
  },
  {
    "input": "Fredrikinkatu 20 E 55, 00120 Helsinki",
    "number": "20",
    "street": "Fredrikin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "E 55",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell E + apartment"
  },
  {
    "input": "Runeberginkatu 14 C 30, 00100 Helsinki",
    "number": "14",
    "street": "Runebergin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "C 30",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell C + apartment"
  },
  {
    "input": "Vuorikatu 6 A 12, 00100 Helsinki",
    "number": "6",
    "street": "Vuori",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "A 12",
    "postal_code": "00100",
    "city": "Helsinki",
    "country": "FI",
    "notes": "stairwell A + apartment"
  },
  {
    "input": "Lönnrotinkatu 11 B 4, 00120 Helsinki",
    "number": "11",
    "street": "Lönnrotin",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "B 4",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "o-umlaut, stairwell+apartment"
  },
  {
    "input": "Annankatu 16 as. 7, 00120 Helsinki",
    "number": "16",
    "street": "Annan",
    "type": "katu",
    "sec_unit_type": "as.",
    "sec_unit_num": "7",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "as. apartment marker"
  },
  {
    "input": "Kehrääjänkatu 6–8, 33720 Tampere",
    "number": "6–8",
    "street": "Kehrääjän",
    "type": "katu",
    "postal_code": "33720",
    "city": "Tampere",
    "country": "FI",
    "notes": "en-dash range 6-8"
  },
  {
    "input": "Bulevardi 2–4, 00120 Helsinki",
    "number": "2–4",
    "street": "Bulevardi",
    "postal_code": "00120",
    "city": "Helsinki",
    "country": "FI",
    "notes": "en-dash range, type null"
  }
];
