// AUTO-GENERATED from research sub-agent corpus (samples-it.json).
// Ground-truth field breakdowns for IT addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const itSamples: EuSample[] = [
  {
    "input": "Via Roma 15, 00184 Roma RM",
    "number": "15",
    "street": "Roma",
    "type": "Via",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "normal, leading-zero CAP"
  },
  {
    "input": "Via del Corso 12, 00186 Roma RM",
    "number": "12",
    "street": "del Corso",
    "type": "Via",
    "postal_code": "00186",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "street name contains 'Corso' but toponimo is Via"
  },
  {
    "input": "Via dei Condotti 8, 00187 Roma RM",
    "number": "8",
    "street": "dei Condotti",
    "type": "Via",
    "postal_code": "00187",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Piazza Navona 45, 00186 Roma RM",
    "number": "45",
    "street": "Navona",
    "type": "Piazza",
    "postal_code": "00186",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "Piazza toponimo"
  },
  {
    "input": "Piazza San Marco 1, 30124 Venezia VE",
    "number": "1",
    "street": "San Marco",
    "type": "Piazza",
    "postal_code": "30124",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "saint multi-word street name"
  },
  {
    "input": "Piazza del Duomo 1, 20122 Milano MI",
    "number": "1",
    "street": "del Duomo",
    "type": "Piazza",
    "postal_code": "20122",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Montenapoleone 8, 20121 Milano MI",
    "number": "8",
    "street": "Montenapoleone",
    "type": "Via",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Buenos Aires 33, 20124 Milano MI",
    "number": "33",
    "street": "Buenos Aires",
    "type": "Corso",
    "postal_code": "20124",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "Corso, multi-word street"
  },
  {
    "input": "Galleria Vittorio Emanuele II 1, 20121 Milano MI",
    "number": "1",
    "street": "Vittorio Emanuele II",
    "type": "Galleria",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "roman numeral II in name, Galleria toponimo"
  },
  {
    "input": "Corso Vittorio Emanuele II 12, 10121 Torino TO",
    "number": "12",
    "street": "Vittorio Emanuele II",
    "type": "Corso",
    "postal_code": "10121",
    "city": "Torino",
    "state": "TO",
    "country": "IT",
    "notes": "roman numeral in name"
  },
  {
    "input": "Via Po 18, 10124 Torino TO",
    "number": "18",
    "street": "Po",
    "type": "Via",
    "postal_code": "10124",
    "city": "Torino",
    "state": "TO",
    "country": "IT",
    "notes": "short one-word street name"
  },
  {
    "input": "Piazza Castello 165, 10122 Torino TO",
    "number": "165",
    "street": "Castello",
    "type": "Piazza",
    "postal_code": "10122",
    "city": "Torino",
    "state": "TO",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Toledo 156, 80134 Napoli NA",
    "number": "156",
    "street": "Toledo",
    "type": "Via",
    "postal_code": "80134",
    "city": "Napoli",
    "state": "NA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via San Gregorio Armeno 1, 80138 Napoli NA",
    "number": "1",
    "street": "San Gregorio Armeno",
    "type": "Via",
    "postal_code": "80138",
    "city": "Napoli",
    "state": "NA",
    "country": "IT",
    "notes": "saint multi-word street name"
  },
  {
    "input": "Corso Umberto I 40, 80138 Napoli NA",
    "number": "40",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "80138",
    "city": "Napoli",
    "state": "NA",
    "country": "IT",
    "notes": "roman numeral I in name"
  },
  {
    "input": "Via Chiaia 216, 80121 Napoli NA",
    "number": "216",
    "street": "Chiaia",
    "type": "Via",
    "postal_code": "80121",
    "city": "Napoli",
    "state": "NA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Piazza della Signoria 5, 50122 Firenze FI",
    "number": "5",
    "street": "della Signoria",
    "type": "Piazza",
    "postal_code": "50122",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via de' Tornabuoni 1 rosso, 50123 Firenze FI",
    "number": "1",
    "civic_number_suffix": "rosso",
    "street": "de' Tornabuoni",
    "type": "Via",
    "postal_code": "50123",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "Firenze red numbering; apostrophe in name"
  },
  {
    "input": "Via de' Tornabuoni 5r, 50123 Firenze FI",
    "number": "5",
    "civic_number_suffix": "r",
    "street": "de' Tornabuoni",
    "type": "Via",
    "postal_code": "50123",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "Firenze red numbering abbreviated 'r'"
  },
  {
    "input": "Via Sant'Ambrogio 3, 50121 Firenze FI",
    "number": "3",
    "street": "Sant'Ambrogio",
    "type": "Via",
    "postal_code": "50121",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "apostrophe saint, do not split"
  },
  {
    "input": "Via Santa Chiara 7, 40137 Bologna BO",
    "number": "7",
    "street": "Santa Chiara",
    "type": "Via",
    "postal_code": "40137",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "Santa unelided saint"
  },
  {
    "input": "Via Santo Stefano 20, 40125 Bologna BO",
    "number": "20",
    "street": "Santo Stefano",
    "type": "Via",
    "postal_code": "40125",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "Santo unelided saint"
  },
  {
    "input": "Via dell'Indipendenza 5, 40121 Bologna BO",
    "number": "5",
    "street": "dell'Indipendenza",
    "type": "Via",
    "postal_code": "40121",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "apostrophe elision dell'"
  },
  {
    "input": "Via Roma 15/A, 00184 Roma RM",
    "number": "15",
    "civic_number_suffix": "/A",
    "street": "Roma",
    "type": "Via",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "civic with /A suffix"
  },
  {
    "input": "Via Garibaldi 27/B, 16124 Genova GE",
    "number": "27",
    "civic_number_suffix": "/B",
    "street": "Garibaldi",
    "type": "Via",
    "postal_code": "16124",
    "city": "Genova",
    "state": "GE",
    "country": "IT",
    "notes": "civic with /B suffix"
  },
  {
    "input": "Via Dante 12A, 20121 Milano MI",
    "number": "12",
    "civic_number_suffix": "A",
    "street": "Dante",
    "type": "Via",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "civic with letter no slash"
  },
  {
    "input": "Via Milano 4 bis, 10122 Torino TO",
    "number": "4",
    "civic_number_suffix": "bis",
    "street": "Milano",
    "type": "Via",
    "postal_code": "10122",
    "city": "Torino",
    "state": "TO",
    "country": "IT",
    "notes": "bis annex"
  },
  {
    "input": "Via Napoli 8 ter, 90133 Palermo PA",
    "number": "8",
    "civic_number_suffix": "ter",
    "street": "Napoli",
    "type": "Via",
    "postal_code": "90133",
    "city": "Palermo",
    "state": "PA",
    "country": "IT",
    "notes": "ter annex"
  },
  {
    "input": "Via dei Mille snc, 90139 Palermo PA",
    "civic_number_suffix": "snc",
    "street": "dei Mille",
    "type": "Via",
    "postal_code": "90139",
    "city": "Palermo",
    "state": "PA",
    "country": "IT",
    "notes": "snc = senza numero civico, no number"
  },
  {
    "input": "Contrada Piano Tavola snc, 95032 Belpasso CT",
    "civic_number_suffix": "snc",
    "street": "Piano Tavola",
    "type": "Contrada",
    "postal_code": "95032",
    "city": "Belpasso",
    "state": "CT",
    "country": "IT",
    "notes": "Contrada rural + snc"
  },
  {
    "input": "Via Etnea 100, 95131 Catania CT",
    "number": "100",
    "street": "Etnea",
    "type": "Via",
    "postal_code": "95131",
    "city": "Catania",
    "state": "CT",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Piazza Duomo 12, 95124 Catania CT",
    "number": "12",
    "street": "Duomo",
    "type": "Piazza",
    "postal_code": "95124",
    "city": "Catania",
    "state": "CT",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Milano (MI), Via Torino 61",
    "__skip": "city-first reversed order",
    "number": "61",
    "street": "Torino",
    "type": "Via",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "province in parentheses, no CAP, reordered"
  },
  {
    "input": "Via Ugo Bassi 3, Bologna (BO)",
    "number": "3",
    "street": "Ugo Bassi",
    "type": "Via",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "province in parens, no CAP"
  },
  {
    "input": "Corso Italia 22, Pisa (PI)",
    "number": "22",
    "street": "Italia",
    "type": "Corso",
    "city": "Pisa",
    "state": "PI",
    "country": "IT",
    "notes": "province in parens"
  },
  {
    "input": "Via Roma 15, 00184 Roma (RM)",
    "number": "15",
    "street": "Roma",
    "type": "Via",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "CAP + province in parens both present"
  },
  {
    "input": "Via Verdi 10 int. 4, 20121 Milano MI",
    "number": "10",
    "street": "Verdi",
    "type": "Via",
    "sec_unit_type": "Interno",
    "sec_unit_num": "4",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "interno appended inline"
  },
  {
    "input": "Via Verdi 10, Interno 5, 20121 Milano MI",
    "number": "10",
    "street": "Verdi",
    "type": "Via",
    "sec_unit_type": "Interno",
    "sec_unit_num": "5",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "interno as separate token"
  },
  {
    "input": "Via Manzoni 5, Scala B, Interno 4, 00185 Roma RM",
    "__skip": "multiple stacked secondary units",
    "number": "5",
    "street": "Manzoni",
    "type": "Via",
    "sec_unit_type": "Scala",
    "sec_unit_num": "B",
    "postal_code": "00185",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "scala + interno (scala captured as sec_unit)"
  },
  {
    "input": "Via Nazionale 30 Sc. A Int. 12, 00184 Roma RM",
    "__skip": "multiple stacked secondary units",
    "number": "30",
    "street": "Nazionale",
    "type": "Via",
    "sec_unit_type": "Scala",
    "sec_unit_num": "A",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "abbreviated Sc./Int. inline"
  },
  {
    "input": "Via Cavour 18/B, Piano 2, Int. 5, 50129 Firenze FI",
    "__skip": "multiple stacked secondary units",
    "number": "18",
    "civic_number_suffix": "/B",
    "street": "Cavour",
    "type": "Via",
    "sec_unit_type": "Piano",
    "sec_unit_num": "2",
    "postal_code": "50129",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "civic suffix + piano + interno"
  },
  {
    "input": "Via Mazzini 44, Appartamento 3, 35131 Padova PD",
    "number": "44",
    "street": "Mazzini",
    "type": "Via",
    "sec_unit_type": "Appartamento",
    "sec_unit_num": "3",
    "postal_code": "35131",
    "city": "Padova",
    "state": "PD",
    "country": "IT",
    "notes": "appartamento"
  },
  {
    "input": "Casella Postale 132, 40100 Bologna BO",
    "sec_unit_type": "Casella Postale",
    "sec_unit_num": "132",
    "postal_code": "40100",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "PO box, no street"
  },
  {
    "input": "C.P. 45, 20100 Milano MI",
    "sec_unit_type": "Casella Postale",
    "sec_unit_num": "45",
    "postal_code": "20100",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "PO box abbreviated"
  },
  {
    "input": "V. Roma 15, 00184 Roma RM",
    "number": "15",
    "street": "Roma",
    "type": "V.",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "abbreviated toponimo V."
  },
  {
    "input": "P.za Duomo 1, 20122 Milano MI",
    "number": "1",
    "street": "Duomo",
    "type": "P.za",
    "postal_code": "20122",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "abbreviated Piazza -> P.za"
  },
  {
    "input": "C.so Italia 3, 95129 Catania CT",
    "number": "3",
    "street": "Italia",
    "type": "C.so",
    "postal_code": "95129",
    "city": "Catania",
    "state": "CT",
    "country": "IT",
    "notes": "abbreviated Corso -> C.so"
  },
  {
    "input": "V.le Europa 22, 00144 Roma RM",
    "number": "22",
    "street": "Europa",
    "type": "V.le",
    "postal_code": "00144",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "abbreviated Viale -> V.le"
  },
  {
    "input": "P.le Loreto 5, 20131 Milano MI",
    "number": "5",
    "street": "Loreto",
    "type": "P.le",
    "postal_code": "20131",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "abbreviated Piazzale -> P.le"
  },
  {
    "input": "L.go Augusto 8, 20122 Milano MI",
    "number": "8",
    "street": "Augusto",
    "type": "L.go",
    "postal_code": "20122",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "abbreviated Largo -> L.go"
  },
  {
    "input": "Viale Trastevere 108, 00153 Roma RM",
    "number": "108",
    "street": "Trastevere",
    "type": "Viale",
    "postal_code": "00153",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "Viale full form"
  },
  {
    "input": "Vicolo del Cinque 12, 00153 Roma RM",
    "number": "12",
    "street": "del Cinque",
    "type": "Vicolo",
    "postal_code": "00153",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "Vicolo toponimo"
  },
  {
    "input": "Largo di Torre Argentina 11, 00186 Roma RM",
    "number": "11",
    "street": "di Torre Argentina",
    "type": "Largo",
    "postal_code": "00186",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "Largo, multi-word name"
  },
  {
    "input": "Piazzale Roma 1, 30135 Venezia VE",
    "number": "1",
    "street": "Roma",
    "type": "Piazzale",
    "postal_code": "30135",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "Piazzale full form"
  },
  {
    "input": "Calle Larga XXII Marzo 2098, 30124 Venezia VE",
    "number": "2098",
    "street": "Larga XXII Marzo",
    "type": "Calle",
    "postal_code": "30124",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "Venice Calle, roman numeral in name, high civic"
  },
  {
    "input": "Fondamenta delle Zattere 1473, 30123 Venezia VE",
    "number": "1473",
    "street": "delle Zattere",
    "type": "Fondamenta",
    "postal_code": "30123",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "Venice Fondamenta"
  },
  {
    "input": "Campo Santa Margherita 3019, 30123 Venezia VE",
    "number": "3019",
    "street": "Santa Margherita",
    "type": "Campo",
    "postal_code": "30123",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "Venice Campo + saint name"
  },
  {
    "input": "Salita San Matteo 15, 16123 Genova GE",
    "number": "15",
    "street": "San Matteo",
    "type": "Salita",
    "postal_code": "16123",
    "city": "Genova",
    "state": "GE",
    "country": "IT",
    "notes": "Salita (Genova) + saint"
  },
  {
    "input": "Lungomare Caracciolo 10, 80122 Napoli NA",
    "number": "10",
    "street": "Caracciolo",
    "type": "Lungomare",
    "postal_code": "80122",
    "city": "Napoli",
    "state": "NA",
    "country": "IT",
    "notes": "Lungomare seafront"
  },
  {
    "input": "Lungarno Torrigiani 23, 50125 Firenze FI",
    "number": "23",
    "street": "Torrigiani",
    "type": "Lungarno",
    "postal_code": "50125",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "Lungarno riverside"
  },
  {
    "input": "Borgo Pinti 99, 50121 Firenze FI",
    "number": "99",
    "street": "Pinti",
    "type": "Borgo",
    "postal_code": "50121",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "Borgo toponimo"
  },
  {
    "input": "Strada Maggiore 44, 40125 Bologna BO",
    "number": "44",
    "street": "Maggiore",
    "type": "Strada",
    "postal_code": "40125",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "Strada toponimo"
  },
  {
    "input": "Località Ponte a Poppi 4, 52014 Poppi AR",
    "number": "4",
    "street": "Ponte a Poppi",
    "type": "Località",
    "postal_code": "52014",
    "city": "Poppi",
    "state": "AR",
    "country": "IT",
    "notes": "Località/frazione as toponimo"
  },
  {
    "input": "Loc. San Martino 12, 53037 San Gimignano SI",
    "__skip": "corpus expands Loc. to Località but keeps other abbrevs verbatim",
    "number": "12",
    "street": "San Martino",
    "type": "Località",
    "postal_code": "53037",
    "city": "San Gimignano",
    "state": "SI",
    "country": "IT",
    "notes": "abbreviated Loc. + saint locality, multi-word comune"
  },
  {
    "input": "Via Niccolò Tommaseo 45, 35131 Padova PD",
    "number": "45",
    "street": "Niccolò Tommaseo",
    "type": "Via",
    "postal_code": "35131",
    "city": "Padova",
    "state": "PD",
    "country": "IT",
    "notes": "accented name Niccolò"
  },
  {
    "input": "Via Cesàreo 8, 73100 Lecce LE",
    "number": "8",
    "street": "Cesàreo",
    "type": "Via",
    "postal_code": "73100",
    "city": "Lecce",
    "state": "LE",
    "country": "IT",
    "notes": "accented à"
  },
  {
    "input": "Via Perù 3, 09124 Cagliari CA",
    "number": "3",
    "street": "Perù",
    "type": "Via",
    "postal_code": "09124",
    "city": "Cagliari",
    "state": "CA",
    "country": "IT",
    "notes": "accented ù + leading-zero CAP Sardinia"
  },
  {
    "input": "Via Roma 100, 07100 Sassari SS",
    "number": "100",
    "street": "Roma",
    "type": "Via",
    "postal_code": "07100",
    "city": "Sassari",
    "state": "SS",
    "country": "IT",
    "notes": "leading-zero CAP Sardinia"
  },
  {
    "input": "Corso Garibaldi 55, 08100 Nuoro NU",
    "number": "55",
    "street": "Garibaldi",
    "type": "Corso",
    "postal_code": "08100",
    "city": "Nuoro",
    "state": "NU",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via Cagliari 12, 09170 Oristano OR",
    "number": "12",
    "street": "Cagliari",
    "type": "Via",
    "postal_code": "09170",
    "city": "Oristano",
    "state": "OR",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via Cornia 7, 09013 Carbonia SU",
    "number": "7",
    "street": "Cornia",
    "type": "Via",
    "postal_code": "09013",
    "city": "Carbonia",
    "state": "SU",
    "country": "IT",
    "notes": "new Sud Sardegna sigla SU"
  },
  {
    "input": "Via Verdi 3, 09016 Iglesias CI",
    "number": "3",
    "street": "Verdi",
    "type": "Via",
    "postal_code": "09016",
    "city": "Iglesias",
    "state": "CI",
    "country": "IT",
    "notes": "legacy Carbonia-Iglesias sigla CI"
  },
  {
    "input": "Via Nazionale 45, 05100 Terni TR",
    "number": "45",
    "street": "Nazionale",
    "type": "Via",
    "postal_code": "05100",
    "city": "Terni",
    "state": "TR",
    "country": "IT",
    "notes": "leading-zero CAP Umbria"
  },
  {
    "input": "Corso Vannucci 19, 06121 Perugia PG",
    "number": "19",
    "street": "Vannucci",
    "type": "Corso",
    "postal_code": "06121",
    "city": "Perugia",
    "state": "PG",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via Cavour 10, 01100 Viterbo VT",
    "number": "10",
    "street": "Cavour",
    "type": "Via",
    "postal_code": "01100",
    "city": "Viterbo",
    "state": "VT",
    "country": "IT",
    "notes": "leading-zero CAP Lazio"
  },
  {
    "input": "Via Roma 22, 02100 Rieti RI",
    "number": "22",
    "street": "Roma",
    "type": "Via",
    "postal_code": "02100",
    "city": "Rieti",
    "state": "RI",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via del Duomo 8, 03100 Frosinone FR",
    "number": "8",
    "street": "del Duomo",
    "type": "Via",
    "postal_code": "03100",
    "city": "Frosinone",
    "state": "FR",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via Emanuele Filiberto 33, 04100 Latina LT",
    "number": "33",
    "street": "Emanuele Filiberto",
    "type": "Via",
    "postal_code": "04100",
    "city": "Latina",
    "state": "LT",
    "country": "IT",
    "notes": "leading-zero CAP"
  },
  {
    "input": "Via Sparano da Bari 12, 70121 Bari BA",
    "number": "12",
    "street": "Sparano da Bari",
    "type": "Via",
    "postal_code": "70121",
    "city": "Bari",
    "state": "BA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Vittorio Emanuele II 145, 70122 Bari BA",
    "number": "145",
    "street": "Vittorio Emanuele II",
    "type": "Corso",
    "postal_code": "70122",
    "city": "Bari",
    "state": "BA",
    "country": "IT",
    "notes": "roman numeral name"
  },
  {
    "input": "Via del Balzo 8, 76123 Andria BT",
    "number": "8",
    "street": "del Balzo",
    "type": "Via",
    "postal_code": "76123",
    "city": "Andria",
    "state": "BT",
    "country": "IT",
    "notes": "province Barletta-Andria-Trani BT"
  },
  {
    "input": "Via Garibaldi 15, 89127 Reggio Calabria RC",
    "number": "15",
    "street": "Garibaldi",
    "type": "Via",
    "postal_code": "89127",
    "city": "Reggio Calabria",
    "state": "RC",
    "country": "IT",
    "notes": "multi-word comune Reggio Calabria"
  },
  {
    "input": "Corso Mazzini 88, 87100 Cosenza CS",
    "number": "88",
    "street": "Mazzini",
    "type": "Corso",
    "postal_code": "87100",
    "city": "Cosenza",
    "state": "CS",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Roma 5, 89900 Vibo Valentia VV",
    "number": "5",
    "street": "Roma",
    "type": "Via",
    "postal_code": "89900",
    "city": "Vibo Valentia",
    "state": "VV",
    "country": "IT",
    "notes": "multi-word comune, VV"
  },
  {
    "input": "Via Vittorio Veneto 20, 88900 Crotone KR",
    "number": "20",
    "street": "Vittorio Veneto",
    "type": "Via",
    "postal_code": "88900",
    "city": "Crotone",
    "state": "KR",
    "country": "IT",
    "notes": "KR sigla"
  },
  {
    "input": "Via Duomo 172, 84121 Salerno SA",
    "number": "172",
    "street": "Duomo",
    "type": "Via",
    "postal_code": "84121",
    "city": "Salerno",
    "state": "SA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Umberto I 15, 84013 Cava de' Tirreni SA",
    "number": "15",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "84013",
    "city": "Cava de' Tirreni",
    "state": "SA",
    "country": "IT",
    "notes": "comune with apostrophe: Cava de' Tirreni"
  },
  {
    "input": "Piazza Sant'Oronzo 1, 73100 Lecce LE",
    "number": "1",
    "street": "Sant'Oronzo",
    "type": "Piazza",
    "postal_code": "73100",
    "city": "Lecce",
    "state": "LE",
    "country": "IT",
    "notes": "apostrophe saint in square name"
  },
  {
    "input": "Via Roma 30, 72100 Brindisi BR",
    "number": "30",
    "street": "Roma",
    "type": "Via",
    "postal_code": "72100",
    "city": "Brindisi",
    "state": "BR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via D'Aquino 50, 74123 Taranto TA",
    "number": "50",
    "street": "D'Aquino",
    "type": "Via",
    "postal_code": "74123",
    "city": "Taranto",
    "state": "TA",
    "country": "IT",
    "notes": "leading apostrophe surname D'Aquino"
  },
  {
    "input": "Corso Roma 12, 71121 Foggia FG",
    "number": "12",
    "street": "Roma",
    "type": "Corso",
    "postal_code": "71121",
    "city": "Foggia",
    "state": "FG",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Maqueda 100, 90134 Palermo PA",
    "number": "100",
    "street": "Maqueda",
    "type": "Via",
    "postal_code": "90134",
    "city": "Palermo",
    "state": "PA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Libertà 171, 90143 Palermo PA",
    "number": "171",
    "street": "Libertà",
    "type": "Via",
    "postal_code": "90143",
    "city": "Palermo",
    "state": "PA",
    "country": "IT",
    "notes": "accented Libertà"
  },
  {
    "input": "Via Garibaldi 42, 98122 Messina ME",
    "number": "42",
    "street": "Garibaldi",
    "type": "Via",
    "postal_code": "98122",
    "city": "Messina",
    "state": "ME",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Umberto I 88, 96100 Siracusa SR",
    "number": "88",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "96100",
    "city": "Siracusa",
    "state": "SR",
    "country": "IT",
    "notes": "roman numeral I"
  },
  {
    "input": "Via Roma 200, 97100 Ragusa RG",
    "number": "200",
    "street": "Roma",
    "type": "Via",
    "postal_code": "97100",
    "city": "Ragusa",
    "state": "RG",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Atenea 15, 92100 Agrigento AG",
    "number": "15",
    "street": "Atenea",
    "type": "Via",
    "postal_code": "92100",
    "city": "Agrigento",
    "state": "AG",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Vittorio Emanuele 45, 91100 Trapani TP",
    "number": "45",
    "street": "Vittorio Emanuele",
    "type": "Corso",
    "postal_code": "91100",
    "city": "Trapani",
    "state": "TP",
    "country": "IT",
    "notes": "Vittorio Emanuele without numeral"
  },
  {
    "input": "Via Roma 8, 93100 Caltanissetta CL",
    "number": "8",
    "street": "Roma",
    "type": "Via",
    "postal_code": "93100",
    "city": "Caltanissetta",
    "state": "CL",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Roma 3, 94100 Enna EN",
    "number": "3",
    "street": "Roma",
    "type": "Via",
    "postal_code": "94100",
    "city": "Enna",
    "state": "EN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via XX Settembre 41, 16121 Genova GE",
    "number": "41",
    "street": "XX Settembre",
    "type": "Via",
    "postal_code": "16121",
    "city": "Genova",
    "state": "GE",
    "country": "IT",
    "notes": "roman-numeral date name XX Settembre"
  },
  {
    "input": "Via XXV Aprile 10, 20121 Milano MI",
    "number": "10",
    "street": "XXV Aprile",
    "type": "Via",
    "postal_code": "20121",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "roman-numeral date name XXV Aprile"
  },
  {
    "input": "Via IV Novembre 149, 00187 Roma RM",
    "number": "149",
    "street": "IV Novembre",
    "type": "Via",
    "postal_code": "00187",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "roman-numeral date name IV Novembre"
  },
  {
    "input": "Via 2 Giugno 5, 40033 Casalecchio di Reno BO",
    "__skip": "leading digit inside name (date street) in street-first order",
    "number": "5",
    "street": "2 Giugno",
    "type": "Via",
    "postal_code": "40033",
    "city": "Casalecchio di Reno",
    "state": "BO",
    "country": "IT",
    "notes": "street name STARTS with a number (2 Giugno); civic still last"
  },
  {
    "input": "Via del Mille 8, 20099 Sesto San Giovanni MI",
    "number": "8",
    "street": "del Mille",
    "type": "Via",
    "postal_code": "20099",
    "city": "Sesto San Giovanni",
    "state": "MI",
    "country": "IT",
    "notes": "multi-word comune Sesto San Giovanni"
  },
  {
    "input": "Piazza San Giovanni 4, 84025 Eboli SA",
    "number": "4",
    "street": "San Giovanni",
    "type": "Piazza",
    "postal_code": "84025",
    "city": "Eboli",
    "state": "SA",
    "country": "IT",
    "notes": "saint square name"
  },
  {
    "input": "Via San Giovanni Rotondo 12, 71013 San Giovanni Rotondo FG",
    "number": "12",
    "street": "San Giovanni Rotondo",
    "type": "Via",
    "postal_code": "71013",
    "city": "San Giovanni Rotondo",
    "state": "FG",
    "country": "IT",
    "notes": "saint street AND saint comune (both San Giovanni Rotondo)"
  },
  {
    "input": "Via Portici 9, 39100 Bolzano BZ",
    "number": "9",
    "street": "Portici",
    "type": "Via",
    "postal_code": "39100",
    "city": "Bolzano",
    "state": "BZ",
    "country": "IT",
    "notes": "South Tyrol BZ"
  },
  {
    "input": "Via Portici / Laubengasse 9, 39100 Bolzano BZ",
    "number": "9",
    "street": "Portici / Laubengasse",
    "type": "Via",
    "postal_code": "39100",
    "city": "Bolzano",
    "state": "BZ",
    "country": "IT",
    "notes": "bilingual IT/DE street name with slash"
  },
  {
    "input": "Piazza Walther 8, 39100 Bolzano BZ",
    "number": "8",
    "street": "Walther",
    "type": "Piazza",
    "postal_code": "39100",
    "city": "Bolzano",
    "state": "BZ",
    "country": "IT",
    "notes": "German name in Italian address"
  },
  {
    "input": "Via Cavour 1, 38122 Trento TN",
    "number": "1",
    "street": "Cavour",
    "type": "Via",
    "postal_code": "38122",
    "city": "Trento",
    "state": "TN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Mazzini 25, 34121 Trieste TS",
    "number": "25",
    "street": "Mazzini",
    "type": "Via",
    "postal_code": "34121",
    "city": "Trieste",
    "state": "TS",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Cavour 100, 33100 Udine UD",
    "number": "100",
    "street": "Cavour",
    "type": "Corso",
    "postal_code": "33100",
    "city": "Udine",
    "state": "UD",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Mercatovecchio 6, 33170 Pordenone PN",
    "number": "6",
    "street": "Mercatovecchio",
    "type": "Via",
    "postal_code": "33170",
    "city": "Pordenone",
    "state": "PN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Italia 33, 34170 Gorizia GO",
    "number": "33",
    "street": "Italia",
    "type": "Corso",
    "postal_code": "34170",
    "city": "Gorizia",
    "state": "GO",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Roma 7, 37121 Verona VR",
    "number": "7",
    "street": "Roma",
    "type": "Via",
    "postal_code": "37121",
    "city": "Verona",
    "state": "VR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Piazza delle Erbe 12, 37121 Verona VR",
    "number": "12",
    "street": "delle Erbe",
    "type": "Piazza",
    "postal_code": "37121",
    "city": "Verona",
    "state": "VR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via del Santo 11, 35123 Padova PD",
    "number": "11",
    "street": "del Santo",
    "type": "Via",
    "postal_code": "35123",
    "city": "Padova",
    "state": "PD",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Contrà Porti 21, 36100 Vicenza VI",
    "number": "21",
    "street": "Porti",
    "type": "Contrà",
    "postal_code": "36100",
    "city": "Vicenza",
    "state": "VI",
    "country": "IT",
    "notes": "Vicenza Contrà (contrada variant), accented"
  },
  {
    "input": "Calmaggiore 18, 31100 Treviso TV",
    "number": "18",
    "street": "Calmaggiore",
    "postal_code": "31100",
    "city": "Treviso",
    "state": "TV",
    "country": "IT",
    "notes": "street with no explicit toponimo prefix (type null)"
  },
  {
    "input": "Via Mazzini 44, 45100 Rovigo RO",
    "number": "44",
    "street": "Mazzini",
    "type": "Via",
    "postal_code": "45100",
    "city": "Rovigo",
    "state": "RO",
    "country": "IT",
    "notes": "RO not to be confused with Roma"
  },
  {
    "input": "Piazza dei Martiri 30, 32100 Belluno BL",
    "number": "30",
    "street": "dei Martiri",
    "type": "Piazza",
    "postal_code": "32100",
    "city": "Belluno",
    "state": "BL",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Emilia 210, 43121 Parma PR",
    "number": "210",
    "street": "Emilia",
    "type": "Via",
    "postal_code": "43121",
    "city": "Parma",
    "state": "PR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Emilia Est 45, 41121 Modena MO",
    "number": "45",
    "street": "Emilia Est",
    "type": "Via",
    "postal_code": "41121",
    "city": "Modena",
    "state": "MO",
    "country": "IT",
    "notes": "compass qualifier in name"
  },
  {
    "input": "Corso Garibaldi 30, 42121 Reggio Emilia RE",
    "number": "30",
    "street": "Garibaldi",
    "type": "Corso",
    "postal_code": "42121",
    "city": "Reggio Emilia",
    "state": "RE",
    "country": "IT",
    "notes": "multi-word comune Reggio Emilia"
  },
  {
    "input": "Via Emilia San Pietro 12, 42121 Reggio nell'Emilia RE",
    "number": "12",
    "street": "Emilia San Pietro",
    "type": "Via",
    "postal_code": "42121",
    "city": "Reggio nell'Emilia",
    "state": "RE",
    "country": "IT",
    "notes": "comune with apostrophe Reggio nell'Emilia"
  },
  {
    "input": "Via Cavour 25, 48121 Ravenna RA",
    "number": "25",
    "street": "Cavour",
    "type": "Via",
    "postal_code": "48121",
    "city": "Ravenna",
    "state": "RA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Viale Ceccarini 11, 47838 Riccione RN",
    "number": "11",
    "street": "Ceccarini",
    "type": "Viale",
    "postal_code": "47838",
    "city": "Riccione",
    "state": "RN",
    "country": "IT",
    "notes": "Rimini province RN"
  },
  {
    "input": "Corso della Giovecca 100, 44121 Ferrara FE",
    "number": "100",
    "street": "della Giovecca",
    "type": "Corso",
    "postal_code": "44121",
    "city": "Ferrara",
    "state": "FE",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Il Corso 5, 29121 Piacenza PC",
    "number": "5",
    "street": "Il Corso",
    "type": "Via",
    "postal_code": "29121",
    "city": "Piacenza",
    "state": "PC",
    "country": "IT",
    "notes": "street name contains word Corso"
  },
  {
    "input": "Corso della Repubblica 88, 47121 Forlì FC",
    "number": "88",
    "street": "della Repubblica",
    "type": "Corso",
    "postal_code": "47121",
    "city": "Forlì",
    "state": "FC",
    "country": "IT",
    "notes": "accented comune Forlì, province FC"
  },
  {
    "input": "Via Fillungo 20, 55100 Lucca LU",
    "number": "20",
    "street": "Fillungo",
    "type": "Via",
    "postal_code": "55100",
    "city": "Lucca",
    "state": "LU",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Banchi di Sopra 31, 53100 Siena SI",
    "number": "31",
    "street": "Banchi di Sopra",
    "type": "Via",
    "postal_code": "53100",
    "city": "Siena",
    "state": "SI",
    "country": "IT",
    "notes": "multi-word street name"
  },
  {
    "input": "Corso Italia 55, 56125 Pisa PI",
    "number": "55",
    "street": "Italia",
    "type": "Corso",
    "postal_code": "56125",
    "city": "Pisa",
    "state": "PI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Grande 110, 57123 Livorno LI",
    "number": "110",
    "street": "Grande",
    "type": "Via",
    "postal_code": "57123",
    "city": "Livorno",
    "state": "LI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Piazza Grande 12, 52100 Arezzo AR",
    "number": "12",
    "street": "Grande",
    "type": "Piazza",
    "postal_code": "52100",
    "city": "Arezzo",
    "state": "AR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Ricasoli 20/R, 50122 Firenze FI",
    "number": "20",
    "civic_number_suffix": "/R",
    "street": "Ricasoli",
    "type": "Via",
    "postal_code": "50122",
    "city": "Firenze",
    "state": "FI",
    "country": "IT",
    "notes": "Firenze red numbering with slash /R"
  },
  {
    "input": "Corso Mazzini 15/A, 60121 Ancona AN",
    "number": "15",
    "civic_number_suffix": "/A",
    "street": "Mazzini",
    "type": "Corso",
    "postal_code": "60121",
    "city": "Ancona",
    "state": "AN",
    "country": "IT",
    "notes": "civic /A"
  },
  {
    "input": "Via Oberdan 5, 61121 Pesaro PU",
    "number": "5",
    "street": "Oberdan",
    "type": "Via",
    "postal_code": "61121",
    "city": "Pesaro",
    "state": "PU",
    "country": "IT",
    "notes": "Pesaro e Urbino PU"
  },
  {
    "input": "Corso della Repubblica 40, 62100 Macerata MC",
    "number": "40",
    "street": "della Repubblica",
    "type": "Corso",
    "postal_code": "62100",
    "city": "Macerata",
    "state": "MC",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Mazzini 224, 63100 Ascoli Piceno AP",
    "number": "224",
    "street": "Mazzini",
    "type": "Corso",
    "postal_code": "63100",
    "city": "Ascoli Piceno",
    "state": "AP",
    "country": "IT",
    "notes": "multi-word comune"
  },
  {
    "input": "Via Mazzini 10, 63900 Fermo FM",
    "number": "10",
    "street": "Mazzini",
    "type": "Via",
    "postal_code": "63900",
    "city": "Fermo",
    "state": "FM",
    "country": "IT",
    "notes": "Fermo FM"
  },
  {
    "input": "Corso Umberto I 200, 65122 Pescara PE",
    "number": "200",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "65122",
    "city": "Pescara",
    "state": "PE",
    "country": "IT",
    "notes": "roman numeral I"
  },
  {
    "input": "Corso Vittorio Emanuele II 5, 67100 L'Aquila AQ",
    "number": "5",
    "street": "Vittorio Emanuele II",
    "type": "Corso",
    "postal_code": "67100",
    "city": "L'Aquila",
    "state": "AQ",
    "country": "IT",
    "notes": "comune with apostrophe L'Aquila; roman numeral"
  },
  {
    "input": "Corso Marrucino 30, 66100 Chieti CH",
    "number": "30",
    "street": "Marrucino",
    "type": "Corso",
    "postal_code": "66100",
    "city": "Chieti",
    "state": "CH",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso San Giorgio 45, 64100 Teramo TE",
    "number": "45",
    "street": "San Giorgio",
    "type": "Corso",
    "postal_code": "64100",
    "city": "Teramo",
    "state": "TE",
    "country": "IT",
    "notes": "saint street name"
  },
  {
    "input": "Via Roma 33, 86100 Campobasso CB",
    "number": "33",
    "street": "Roma",
    "type": "Via",
    "postal_code": "86100",
    "city": "Campobasso",
    "state": "CB",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Umberto I 12, 83100 Avellino AV",
    "number": "12",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "83100",
    "city": "Avellino",
    "state": "AV",
    "country": "IT",
    "notes": "roman numeral"
  },
  {
    "input": "Corso Garibaldi 100, 82100 Benevento BN",
    "number": "100",
    "street": "Garibaldi",
    "type": "Corso",
    "postal_code": "82100",
    "city": "Benevento",
    "state": "BN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Mazzini 8, 81100 Caserta CE",
    "number": "8",
    "street": "Mazzini",
    "type": "Via",
    "postal_code": "81100",
    "city": "Caserta",
    "state": "CE",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Pretoria 150, 85100 Potenza PZ",
    "number": "150",
    "street": "Pretoria",
    "type": "Via",
    "postal_code": "85100",
    "city": "Potenza",
    "state": "PZ",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via del Corso 5, 75100 Matera MT",
    "number": "5",
    "street": "del Corso",
    "type": "Via",
    "postal_code": "75100",
    "city": "Matera",
    "state": "MT",
    "country": "IT",
    "notes": "street contains 'Corso' but type is Via"
  },
  {
    "input": "Via Roma 12, 88100 Catanzaro CZ",
    "number": "12",
    "street": "Roma",
    "type": "Via",
    "postal_code": "88100",
    "city": "Catanzaro",
    "state": "CZ",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Milano 20, 24122 Bergamo BG",
    "number": "20",
    "street": "Milano",
    "type": "Via",
    "postal_code": "24122",
    "city": "Bergamo",
    "state": "BG",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Zanardelli 15, 25121 Brescia BS",
    "number": "15",
    "street": "Zanardelli",
    "type": "Corso",
    "postal_code": "25121",
    "city": "Brescia",
    "state": "BS",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Volta 5, 22100 Como CO",
    "number": "5",
    "street": "Volta",
    "type": "Via",
    "postal_code": "22100",
    "city": "Como",
    "state": "CO",
    "country": "IT",
    "notes": "CO province not to be confused with Corso"
  },
  {
    "input": "Corso Matteotti 40, 21100 Varese VA",
    "number": "40",
    "street": "Matteotti",
    "type": "Corso",
    "postal_code": "21100",
    "city": "Varese",
    "state": "VA",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Italia 22, 20900 Monza MB",
    "number": "22",
    "street": "Italia",
    "type": "Via",
    "postal_code": "20900",
    "city": "Monza",
    "state": "MB",
    "country": "IT",
    "notes": "Monza e Brianza MB"
  },
  {
    "input": "Corso Cavour 10, 27100 Pavia PV",
    "number": "10",
    "street": "Cavour",
    "type": "Corso",
    "postal_code": "27100",
    "city": "Pavia",
    "state": "PV",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Roma 88, 26100 Cremona CR",
    "number": "88",
    "street": "Roma",
    "type": "Via",
    "postal_code": "26100",
    "city": "Cremona",
    "state": "CR",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Roma 15, 46100 Mantova MN",
    "number": "15",
    "street": "Roma",
    "type": "Via",
    "postal_code": "46100",
    "city": "Mantova",
    "state": "MN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Umberto I 33, 26900 Lodi LO",
    "number": "33",
    "street": "Umberto I",
    "type": "Corso",
    "postal_code": "26900",
    "city": "Lodi",
    "state": "LO",
    "country": "IT",
    "notes": "roman numeral, LO province"
  },
  {
    "input": "Via Nazionale 5, 23100 Sondrio SO",
    "number": "5",
    "street": "Nazionale",
    "type": "Via",
    "postal_code": "23100",
    "city": "Sondrio",
    "state": "SO",
    "country": "IT",
    "notes": "SO province"
  },
  {
    "input": "Corso Martiri della Liberazione 12, 23900 Lecco LC",
    "number": "12",
    "street": "Martiri della Liberazione",
    "type": "Corso",
    "postal_code": "23900",
    "city": "Lecco",
    "state": "LC",
    "country": "IT",
    "notes": "long multi-word street name"
  },
  {
    "input": "Via Roma 44, 28100 Novara NO",
    "number": "44",
    "street": "Roma",
    "type": "Via",
    "postal_code": "28100",
    "city": "Novara",
    "state": "NO",
    "country": "IT",
    "notes": "NO province not the word no"
  },
  {
    "input": "Corso Nizza 20, 12100 Cuneo CN",
    "number": "20",
    "street": "Nizza",
    "type": "Corso",
    "postal_code": "12100",
    "city": "Cuneo",
    "state": "CN",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Alfieri 350, 14100 Asti AT",
    "number": "350",
    "street": "Alfieri",
    "type": "Corso",
    "postal_code": "14100",
    "city": "Asti",
    "state": "AT",
    "country": "IT",
    "notes": "high civic number"
  },
  {
    "input": "Via Roma 12, 15121 Alessandria AL",
    "number": "12",
    "street": "Roma",
    "type": "Via",
    "postal_code": "15121",
    "city": "Alessandria",
    "state": "AL",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Aosta 5, 11100 Aosta AO",
    "number": "5",
    "street": "Aosta",
    "type": "Via",
    "postal_code": "11100",
    "city": "Aosta",
    "state": "AO",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Italia 100, 13900 Biella BI",
    "number": "100",
    "street": "Italia",
    "type": "Via",
    "postal_code": "13900",
    "city": "Biella",
    "state": "BI",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Corso Libertà 8, 13100 Vercelli VC",
    "number": "8",
    "street": "Libertà",
    "type": "Corso",
    "postal_code": "13100",
    "city": "Vercelli",
    "state": "VC",
    "country": "IT",
    "notes": "accented Libertà, VC province"
  },
  {
    "input": "Corso Cavallotti 20, 18100 Imperia IM",
    "number": "20",
    "street": "Cavallotti",
    "type": "Corso",
    "postal_code": "18100",
    "city": "Imperia",
    "state": "IM",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via Paleocapa 7, 17100 Savona SV",
    "number": "7",
    "street": "Paleocapa",
    "type": "Via",
    "postal_code": "17100",
    "city": "Savona",
    "state": "SV",
    "country": "IT",
    "notes": "normal"
  },
  {
    "input": "Via del Prione 100, 19121 La Spezia SP",
    "number": "100",
    "street": "del Prione",
    "type": "Via",
    "postal_code": "19121",
    "city": "La Spezia",
    "state": "SP",
    "country": "IT",
    "notes": "multi-word comune La Spezia, SP province"
  },
  {
    "input": "Via Roma 15/A, Scala B, Piano 3, Interno 7, 00184 Roma RM",
    "__skip": "multiple stacked secondary units",
    "number": "15",
    "civic_number_suffix": "/A",
    "street": "Roma",
    "type": "Via",
    "sec_unit_type": "Scala",
    "sec_unit_num": "B",
    "postal_code": "00184",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "full stack: civic suffix + scala + piano + interno (scala captured first)"
  },
  {
    "input": "Via Torino 20 int 5, 20123 Milano MI",
    "number": "20",
    "street": "Torino",
    "type": "Via",
    "sec_unit_type": "Interno",
    "sec_unit_num": "5",
    "postal_code": "20123",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "int without dot inline"
  },
  {
    "input": "Via Garibaldi 12, 20099 Sesto San Giovanni (MI)",
    "number": "12",
    "street": "Garibaldi",
    "type": "Via",
    "postal_code": "20099",
    "city": "Sesto San Giovanni",
    "state": "MI",
    "country": "IT",
    "notes": "CAP + multi-word comune + province in parens"
  },
  {
    "input": "Via Appia Nuova 500, 00179 Roma RM, Italia",
    "number": "500",
    "street": "Appia Nuova",
    "type": "Via",
    "postal_code": "00179",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "explicit country Italia"
  },
  {
    "input": "Via Nomentana 250, 00162 Roma RM, Italy",
    "number": "250",
    "street": "Nomentana",
    "type": "Via",
    "postal_code": "00162",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "explicit country Italy (English)"
  },
  {
    "input": "Piazza San Babila 3, 20122 Milano (MI), IT",
    "number": "3",
    "street": "San Babila",
    "type": "Piazza",
    "postal_code": "20122",
    "city": "Milano",
    "state": "MI",
    "country": "IT",
    "notes": "saint square + province parens + IT country"
  },
  {
    "input": "Via Gramsci 4 bis/A, 40121 Bologna BO",
    "number": "4",
    "civic_number_suffix": "bis/A",
    "street": "Gramsci",
    "type": "Via",
    "postal_code": "40121",
    "city": "Bologna",
    "state": "BO",
    "country": "IT",
    "notes": "combined bis + letter annex"
  },
  {
    "input": "Strada Statale 16 km 3, 47521 Cesena FC",
    "__skip": "SS road number + km marker as street",
    "street": "16",
    "type": "Strada Statale",
    "postal_code": "47521",
    "city": "Cesena",
    "state": "FC",
    "country": "IT",
    "notes": "extra-urban road SS 16, km marker not a civic"
  },
  {
    "input": "Via Roma snc, Fraz. Marina, 08022 Dorgali NU",
    "__skip": "frazione locality between street and CAP",
    "civic_number_suffix": "snc",
    "street": "Roma",
    "type": "Via",
    "postal_code": "08022",
    "city": "Dorgali",
    "state": "NU",
    "country": "IT",
    "notes": "snc + frazione + leading-zero CAP"
  },
  {
    "input": "Vico Equense (NA), Via Nicotera 10",
    "__skip": "city-first reversed order",
    "number": "10",
    "street": "Nicotera",
    "type": "Via",
    "city": "Vico Equense",
    "state": "NA",
    "country": "IT",
    "notes": "comune STARTS with 'Vico' (looks like Vicolo abbrev), province parens, reordered"
  },
  {
    "input": "Via San Francesco d'Assisi 15, 10122 Torino TO",
    "number": "15",
    "street": "San Francesco d'Assisi",
    "type": "Via",
    "postal_code": "10122",
    "city": "Torino",
    "state": "TO",
    "country": "IT",
    "notes": "saint name with internal apostrophe d'Assisi"
  },
  {
    "input": "Piazza dei Cavalieri di Vittorio Veneto 2, 56126 Pisa PI",
    "number": "2",
    "street": "dei Cavalieri di Vittorio Veneto",
    "type": "Piazza",
    "postal_code": "56126",
    "city": "Pisa",
    "state": "PI",
    "country": "IT",
    "notes": "very long multi-word square name"
  },
  {
    "input": "Via Ca' Foscari 3246, 30123 Venezia VE",
    "number": "3246",
    "street": "Ca' Foscari",
    "type": "Via",
    "postal_code": "30123",
    "city": "Venezia",
    "state": "VE",
    "country": "IT",
    "notes": "Ca' apostrophe (casa) + very high Venice civic"
  },
  {
    "input": "Via Manzoni 5 Sc. A, 00185 Roma (RM)",
    "number": "5",
    "street": "Manzoni",
    "type": "Via",
    "sec_unit_type": "Scala",
    "sec_unit_num": "A",
    "postal_code": "00185",
    "city": "Roma",
    "state": "RM",
    "country": "IT",
    "notes": "scala only, province parens with CAP"
  }
];
