// AUTO-GENERATED from research sub-agent corpus (samples-pl.json).
// Ground-truth field breakdowns for PL addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const plSamples: EuSample[] = [
  {
    "input": "ul. Marszałkowska 1, 00-950 Warszawa",
    "number": "1",
    "street": "Marszałkowska",
    "type": "ul.",
    "postal_code": "00-950",
    "city": "Warszawa",
    "country": "PL",
    "notes": "normal ul. + name + number"
  },
  {
    "input": "ul. Piękna 5, 00-539 Warszawa",
    "number": "5",
    "street": "Piękna",
    "type": "ul.",
    "postal_code": "00-539",
    "city": "Warszawa",
    "country": "PL",
    "notes": "normal"
  },
  {
    "input": "ul. Nowy Świat 12/5, 00-372 Warszawa",
    "number": "12",
    "street": "Nowy Świat",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "5",
    "postal_code": "00-372",
    "city": "Warszawa",
    "country": "PL",
    "notes": "slash apartment; multi-word name"
  },
  {
    "input": "ul. Nowy Świat 12 m. 5, 00-372 Warszawa",
    "number": "12",
    "street": "Nowy Świat",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "5",
    "postal_code": "00-372",
    "city": "Warszawa",
    "country": "PL",
    "notes": "m. apartment form"
  },
  {
    "input": "ul. Chmielna 12A, 00-021 Warszawa",
    "number": "12",
    "civic_number_suffix": "A",
    "street": "Chmielna",
    "type": "ul.",
    "postal_code": "00-021",
    "city": "Warszawa",
    "country": "PL",
    "notes": "civic number letter suffix"
  },
  {
    "input": "ul. Wilcza 12A/5, 00-538 Warszawa",
    "number": "12",
    "civic_number_suffix": "A",
    "street": "Wilcza",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "5",
    "postal_code": "00-538",
    "city": "Warszawa",
    "country": "PL",
    "notes": "suffix + apartment 12A/5"
  },
  {
    "input": "ul. Hoża 27 m. 3, 00-521 Warszawa",
    "number": "27",
    "street": "Hoża",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "3",
    "postal_code": "00-521",
    "city": "Warszawa",
    "country": "PL",
    "notes": "m. apartment with diacritic"
  },
  {
    "input": "ul. Żurawia 32 lok. 8, 00-515 Warszawa",
    "number": "32",
    "street": "Żurawia",
    "type": "ul.",
    "sec_unit_type": "lok.",
    "sec_unit_num": "8",
    "postal_code": "00-515",
    "city": "Warszawa",
    "country": "PL",
    "notes": "lok. apartment form"
  },
  {
    "input": "ul. Świętokrzyska 14, 00-050 Warszawa",
    "number": "14",
    "street": "Świętokrzyska",
    "type": "ul.",
    "postal_code": "00-050",
    "city": "Warszawa",
    "country": "PL",
    "notes": "diacritics in name"
  },
  {
    "input": "al. Jerozolimskie 54, 00-024 Warszawa",
    "number": "54",
    "street": "Jerozolimskie",
    "type": "al.",
    "postal_code": "00-024",
    "city": "Warszawa",
    "country": "PL",
    "notes": "al. avenue"
  },
  {
    "input": "al. Jana Pawła II 12, 00-124 Warszawa",
    "number": "12",
    "street": "Jana Pawła II",
    "type": "al.",
    "postal_code": "00-124",
    "city": "Warszawa",
    "country": "PL",
    "notes": "multi-word name with Roman numeral II"
  },
  {
    "input": "aleja Jana Pawła II 23, 00-854 Warszawa",
    "number": "23",
    "street": "Jana Pawła II",
    "type": "al.",
    "postal_code": "00-854",
    "city": "Warszawa",
    "country": "PL",
    "notes": "type spelled in full 'aleja'"
  },
  {
    "input": "al. Solidarności 82, 00-145 Warszawa",
    "number": "82",
    "street": "Solidarności",
    "type": "al.",
    "postal_code": "00-145",
    "city": "Warszawa",
    "country": "PL",
    "notes": "al. avenue"
  },
  {
    "input": "pl. Konstytucji 6, 00-550 Warszawa",
    "number": "6",
    "street": "Konstytucji",
    "type": "pl.",
    "postal_code": "00-550",
    "city": "Warszawa",
    "country": "PL",
    "notes": "pl. square"
  },
  {
    "input": "pl. Konstytucji 3 Maja 1, 00-587 Warszawa",
    "number": "1",
    "street": "Konstytucji 3 Maja",
    "type": "pl.",
    "postal_code": "00-587",
    "city": "Warszawa",
    "country": "PL",
    "notes": "name ends in number-word; house number is final 1"
  },
  {
    "input": "pl. Bankowy 2, 00-095 Warszawa",
    "number": "2",
    "street": "Bankowy",
    "type": "pl.",
    "postal_code": "00-095",
    "city": "Warszawa",
    "country": "PL",
    "notes": "pl. square"
  },
  {
    "input": "plac Zbawiciela 3, 00-573 Warszawa",
    "number": "3",
    "street": "Zbawiciela",
    "type": "pl.",
    "postal_code": "00-573",
    "city": "Warszawa",
    "country": "PL",
    "notes": "type spelled in full 'plac'"
  },
  {
    "input": "rondo Daszyńskiego 1, 00-843 Warszawa",
    "number": "1",
    "street": "Daszyńskiego",
    "type": "rondo",
    "postal_code": "00-843",
    "city": "Warszawa",
    "country": "PL",
    "notes": "rondo type (written in full)"
  },
  {
    "input": "rondo ONZ 1, 00-124 Warszawa",
    "number": "1",
    "street": "ONZ",
    "type": "rondo",
    "postal_code": "00-124",
    "city": "Warszawa",
    "country": "PL",
    "notes": "rondo with acronym name"
  },
  {
    "input": "ul. 3 Maja 5, 00-401 Warszawa",
    "number": "5",
    "street": "3 Maja",
    "type": "ul.",
    "postal_code": "00-401",
    "city": "Warszawa",
    "country": "PL",
    "notes": "numbered street name; leading 3 is part of name"
  },
  {
    "input": "ul. 1 Maja 12, 40-224 Katowice",
    "number": "12",
    "street": "1 Maja",
    "type": "ul.",
    "postal_code": "40-224",
    "city": "Katowice",
    "country": "PL",
    "notes": "numbered street name"
  },
  {
    "input": "ul. 11 Listopada 22, 03-425 Warszawa",
    "number": "22",
    "street": "11 Listopada",
    "type": "ul.",
    "postal_code": "03-425",
    "city": "Warszawa",
    "country": "PL",
    "notes": "numbered street name"
  },
  {
    "input": "ul. 29 Listopada 46, 31-425 Kraków",
    "number": "46",
    "street": "29 Listopada",
    "type": "ul.",
    "postal_code": "31-425",
    "city": "Kraków",
    "country": "PL",
    "notes": "numbered street name in Kraków"
  },
  {
    "input": "Marszałkowska 1, 00-950 Warszawa",
    "number": "1",
    "street": "Marszałkowska",
    "postal_code": "00-950",
    "city": "Warszawa",
    "country": "PL",
    "notes": "missing ul. prefix"
  },
  {
    "input": "Długa 44/50, 00-241 Warszawa",
    "number": "44",
    "street": "Długa",
    "sec_unit_type": "m.",
    "sec_unit_num": "50",
    "postal_code": "00-241",
    "city": "Warszawa",
    "country": "PL",
    "notes": "missing prefix + slash apartment"
  },
  {
    "input": "ul. Floriańska 3, 31-019 Kraków",
    "number": "3",
    "street": "Floriańska",
    "type": "ul.",
    "postal_code": "31-019",
    "city": "Kraków",
    "country": "PL",
    "notes": "Kraków normal"
  },
  {
    "input": "ul. Grodzka 15/2, 31-006 Kraków",
    "number": "15",
    "street": "Grodzka",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "2",
    "postal_code": "31-006",
    "city": "Kraków",
    "country": "PL",
    "notes": "Kraków slash apartment"
  },
  {
    "input": "Rynek Główny 1, 31-042 Kraków",
    "number": "1",
    "street": "Rynek Główny",
    "postal_code": "31-042",
    "city": "Kraków",
    "country": "PL",
    "notes": "square named 'Rynek Główny', no ul."
  },
  {
    "input": "ul. Karmelicka 27, 31-131 Kraków",
    "number": "27",
    "street": "Karmelicka",
    "type": "ul.",
    "postal_code": "31-131",
    "city": "Kraków",
    "country": "PL",
    "notes": "Kraków normal"
  },
  {
    "input": "ul. Piotrkowska 100, 90-006 Łódź",
    "number": "100",
    "street": "Piotrkowska",
    "type": "ul.",
    "postal_code": "90-006",
    "city": "Łódź",
    "country": "PL",
    "notes": "Łódź; diacritics in city"
  },
  {
    "input": "ul. Piotrkowska 104A, 90-926 Łódź",
    "number": "104",
    "civic_number_suffix": "A",
    "street": "Piotrkowska",
    "type": "ul.",
    "postal_code": "90-926",
    "city": "Łódź",
    "country": "PL",
    "notes": "letter suffix in Łódź"
  },
  {
    "input": "al. Kościuszki 1, 90-418 Łódź",
    "number": "1",
    "street": "Kościuszki",
    "type": "al.",
    "postal_code": "90-418",
    "city": "Łódź",
    "country": "PL",
    "notes": "al. avenue Łódź"
  },
  {
    "input": "ul. Świdnicka 40, 50-024 Wrocław",
    "number": "40",
    "street": "Świdnicka",
    "type": "ul.",
    "postal_code": "50-024",
    "city": "Wrocław",
    "country": "PL",
    "notes": "Wrocław; diacritics in city"
  },
  {
    "input": "Rynek 14, 50-101 Wrocław",
    "number": "14",
    "street": "Rynek",
    "postal_code": "50-101",
    "city": "Wrocław",
    "country": "PL",
    "notes": "market square 'Rynek', no prefix"
  },
  {
    "input": "pl. Grunwaldzki 22, 50-363 Wrocław",
    "number": "22",
    "street": "Grunwaldzki",
    "type": "pl.",
    "postal_code": "50-363",
    "city": "Wrocław",
    "country": "PL",
    "notes": "pl. square Wrocław"
  },
  {
    "input": "ul. Legnicka 55/7, 54-203 Wrocław",
    "number": "55",
    "street": "Legnicka",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "7",
    "postal_code": "54-203",
    "city": "Wrocław",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "ul. Święty Marcin 29, 61-806 Poznań",
    "number": "29",
    "street": "Święty Marcin",
    "type": "ul.",
    "postal_code": "61-806",
    "city": "Poznań",
    "country": "PL",
    "notes": "Poznań; multi-word name with diacritics"
  },
  {
    "input": "Stary Rynek 59, 61-772 Poznań",
    "number": "59",
    "street": "Stary Rynek",
    "postal_code": "61-772",
    "city": "Poznań",
    "country": "PL",
    "notes": "'Stary Rynek' square, no prefix"
  },
  {
    "input": "os. Bolesława Chrobrego 32, 60-681 Poznań",
    "number": "32",
    "street": "Bolesława Chrobrego",
    "type": "os.",
    "postal_code": "60-681",
    "city": "Poznań",
    "country": "PL",
    "notes": "os. housing estate, multi-word name"
  },
  {
    "input": "os. Tysiąclecia 20/34, 61-255 Poznań",
    "number": "20",
    "street": "Tysiąclecia",
    "type": "os.",
    "sec_unit_type": "m.",
    "sec_unit_num": "34",
    "postal_code": "61-255",
    "city": "Poznań",
    "country": "PL",
    "notes": "os. estate; block 20 / flat 34"
  },
  {
    "input": "ul. Długa 46/47, 80-831 Gdańsk",
    "number": "46",
    "street": "Długa",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "47",
    "postal_code": "80-831",
    "city": "Gdańsk",
    "country": "PL",
    "notes": "Gdańsk; slash apartment"
  },
  {
    "input": "ul. Długi Targ 20, 80-828 Gdańsk",
    "number": "20",
    "street": "Długi Targ",
    "type": "ul.",
    "postal_code": "80-828",
    "city": "Gdańsk",
    "country": "PL",
    "notes": "multi-word name Gdańsk"
  },
  {
    "input": "ul. Grunwaldzka 82, 80-244 Gdańsk",
    "number": "82",
    "street": "Grunwaldzka",
    "type": "ul.",
    "postal_code": "80-244",
    "city": "Gdańsk",
    "country": "PL",
    "notes": "Gdańsk normal"
  },
  {
    "input": "ul. Świętojańska 43, 81-391 Gdynia",
    "number": "43",
    "street": "Świętojańska",
    "type": "ul.",
    "postal_code": "81-391",
    "city": "Gdynia",
    "country": "PL",
    "notes": "Gdynia; diacritics"
  },
  {
    "input": "al. Wojska Polskiego 30, 70-473 Szczecin",
    "number": "30",
    "street": "Wojska Polskiego",
    "type": "al.",
    "postal_code": "70-473",
    "city": "Szczecin",
    "country": "PL",
    "notes": "Szczecin; al. multi-word"
  },
  {
    "input": "ul. Krzywoustego 7/3, 70-252 Szczecin",
    "number": "7",
    "street": "Krzywoustego",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "3",
    "postal_code": "70-252",
    "city": "Szczecin",
    "country": "PL",
    "notes": "slash apartment Szczecin"
  },
  {
    "input": "ul. Gdańska 15, 85-006 Bydgoszcz",
    "number": "15",
    "street": "Gdańska",
    "type": "ul.",
    "postal_code": "85-006",
    "city": "Bydgoszcz",
    "country": "PL",
    "notes": "Bydgoszcz normal"
  },
  {
    "input": "ul. Krakowskie Przedmieście 5, 20-002 Lublin",
    "number": "5",
    "street": "Krakowskie Przedmieście",
    "type": "ul.",
    "postal_code": "20-002",
    "city": "Lublin",
    "country": "PL",
    "notes": "Lublin; long multi-word name"
  },
  {
    "input": "ul. Narutowicza 12/14, 20-004 Lublin",
    "number": "12",
    "street": "Narutowicza",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "14",
    "postal_code": "20-004",
    "city": "Lublin",
    "country": "PL",
    "notes": "ambiguous 12/14; default to building 12 / apt 14"
  },
  {
    "input": "ul. Mariacka 3 m 8, 40-014 Katowice",
    "number": "3",
    "street": "Mariacka",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "8",
    "postal_code": "40-014",
    "city": "Katowice",
    "country": "PL",
    "notes": "m without dot"
  },
  {
    "input": "ul. Warszawska 19, 40-009 Katowice",
    "number": "19",
    "street": "Warszawska",
    "type": "ul.",
    "postal_code": "40-009",
    "city": "Katowice",
    "country": "PL",
    "notes": "Katowice normal"
  },
  {
    "input": "Rynek 1, 40-003 Katowice",
    "number": "1",
    "street": "Rynek",
    "postal_code": "40-003",
    "city": "Katowice",
    "country": "PL",
    "notes": "Rynek square, no prefix"
  },
  {
    "input": "ul. Lipowa 1, 15-424 Białystok",
    "number": "1",
    "street": "Lipowa",
    "type": "ul.",
    "postal_code": "15-424",
    "city": "Białystok",
    "country": "PL",
    "notes": "Białystok; diacritics in city"
  },
  {
    "input": "ul. Sienkiewicza 4 lok. 2, 15-092 Białystok",
    "number": "4",
    "street": "Sienkiewicza",
    "type": "ul.",
    "sec_unit_type": "lok.",
    "sec_unit_num": "2",
    "postal_code": "15-092",
    "city": "Białystok",
    "country": "PL",
    "notes": "lok. apartment"
  },
  {
    "input": "ul. Sienkiewicza 60, 25-507 Kielce",
    "number": "60",
    "street": "Sienkiewicza",
    "type": "ul.",
    "postal_code": "25-507",
    "city": "Kielce",
    "country": "PL",
    "notes": "Kielce normal"
  },
  {
    "input": "ul. 3 Maja 7, 35-030 Rzeszów",
    "number": "7",
    "street": "3 Maja",
    "type": "ul.",
    "postal_code": "35-030",
    "city": "Rzeszów",
    "country": "PL",
    "notes": "numbered street name Rzeszów"
  },
  {
    "input": "ul. Zwycięstwa 10, 44-100 Gliwice",
    "number": "10",
    "street": "Zwycięstwa",
    "type": "ul.",
    "postal_code": "44-100",
    "city": "Gliwice",
    "country": "PL",
    "notes": "Gliwice normal"
  },
  {
    "input": "al. Racławickie 14, 20-950 Lublin",
    "number": "14",
    "street": "Racławickie",
    "type": "al.",
    "postal_code": "20-950",
    "city": "Lublin",
    "country": "PL",
    "notes": "al. avenue Lublin"
  },
  {
    "input": "ul. Grunwaldzka 5/12, 10-126 Olsztyn",
    "number": "5",
    "street": "Grunwaldzka",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "12",
    "postal_code": "10-126",
    "city": "Olsztyn",
    "country": "PL",
    "notes": "Olsztyn; slash apartment"
  },
  {
    "input": "ul. Wojska Polskiego 3, 45-078 Opole",
    "number": "3",
    "street": "Wojska Polskiego",
    "type": "ul.",
    "postal_code": "45-078",
    "city": "Opole",
    "country": "PL",
    "notes": "Opole; multi-word name"
  },
  {
    "input": "ul. Nadbystrzycka 38D, 20-618 Lublin",
    "number": "38",
    "civic_number_suffix": "D",
    "street": "Nadbystrzycka",
    "type": "ul.",
    "postal_code": "20-618",
    "city": "Lublin",
    "country": "PL",
    "notes": "letter suffix D"
  },
  {
    "input": "ul. Bohaterów Getta 18, 31-038 Kraków",
    "number": "18",
    "street": "Bohaterów Getta",
    "type": "ul.",
    "postal_code": "31-038",
    "city": "Kraków",
    "country": "PL",
    "notes": "multi-word name"
  },
  {
    "input": "ul. Marii Skłodowskiej-Curie 8, 15-097 Białystok",
    "number": "8",
    "street": "Marii Skłodowskiej-Curie",
    "type": "ul.",
    "postal_code": "15-097",
    "city": "Białystok",
    "country": "PL",
    "notes": "hyphenated multi-word name with diacritics"
  },
  {
    "input": "ul. Żółkiewskiego 17, 87-100 Toruń",
    "number": "17",
    "street": "Żółkiewskiego",
    "type": "ul.",
    "postal_code": "87-100",
    "city": "Toruń",
    "country": "PL",
    "notes": "heavy diacritics ż ó"
  },
  {
    "input": "ul. Zolkiewskiego 17, 87-100 Torun",
    "number": "17",
    "street": "Zolkiewskiego",
    "type": "ul.",
    "postal_code": "87-100",
    "city": "Torun",
    "country": "PL",
    "notes": "ASCII fallback (no diacritics) same address"
  },
  {
    "input": "ul. Świętego Ducha 6, 87-100 Toruń",
    "number": "6",
    "street": "Świętego Ducha",
    "type": "ul.",
    "postal_code": "87-100",
    "city": "Toruń",
    "country": "PL",
    "notes": "multi-word name Toruń"
  },
  {
    "input": "ul. Łąkowa 3/5, 80-769 Gdańsk",
    "number": "3",
    "street": "Łąkowa",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "5",
    "postal_code": "80-769",
    "city": "Gdańsk",
    "country": "PL",
    "notes": "ł ą diacritics + slash apartment"
  },
  {
    "input": "ul. Ćmielowska 2, 03-198 Warszawa",
    "number": "2",
    "street": "Ćmielowska",
    "type": "ul.",
    "postal_code": "03-198",
    "city": "Warszawa",
    "country": "PL",
    "notes": "ć diacritic at start"
  },
  {
    "input": "ul. Źródlana 9, 60-642 Poznań",
    "number": "9",
    "street": "Źródlana",
    "type": "ul.",
    "postal_code": "60-642",
    "city": "Poznań",
    "country": "PL",
    "notes": "ź ó diacritics"
  },
  {
    "input": "ul. Ptasia 4 m. 10, 00-138 Warszawa",
    "number": "4",
    "street": "Ptasia",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "10",
    "postal_code": "00-138",
    "city": "Warszawa",
    "country": "PL",
    "notes": "m. apartment"
  },
  {
    "input": "ul. Koszykowa 54, 00-675 Warszawa, Polska",
    "number": "54",
    "street": "Koszykowa",
    "type": "ul.",
    "postal_code": "00-675",
    "city": "Warszawa",
    "country": "PL",
    "notes": "country 'Polska' -> PL"
  },
  {
    "input": "ul. Puławska 12, 02-566 Warszawa, Poland",
    "number": "12",
    "street": "Puławska",
    "type": "ul.",
    "postal_code": "02-566",
    "city": "Warszawa",
    "country": "PL",
    "notes": "country 'Poland' -> PL"
  },
  {
    "input": "ul. Wspólna 62, 00-687 Warszawa, PL",
    "number": "62",
    "street": "Wspólna",
    "type": "ul.",
    "postal_code": "00-687",
    "city": "Warszawa",
    "country": "PL",
    "notes": "country 'PL'"
  },
  {
    "input": "ul. Grzybowska 60, 00-844 Warszawa, POLSKA",
    "number": "60",
    "street": "Grzybowska",
    "type": "ul.",
    "postal_code": "00-844",
    "city": "Warszawa",
    "country": "PL",
    "notes": "uppercase POLSKA -> PL"
  },
  {
    "input": "ul. Twarda 18, 00-105 WARSZAWA",
    "number": "18",
    "street": "Twarda",
    "type": "ul.",
    "postal_code": "00-105",
    "city": "WARSZAWA",
    "country": "PL",
    "notes": "city in uppercase (envelope style)"
  },
  {
    "input": "ul. Emilii Plater 53, 00-113 Warszawa",
    "number": "53",
    "street": "Emilii Plater",
    "type": "ul.",
    "postal_code": "00-113",
    "city": "Warszawa",
    "country": "PL",
    "notes": "multi-word personal name"
  },
  {
    "input": "ul. Tadeusza Kościuszki 10/2, 30-105 Kraków",
    "number": "10",
    "street": "Tadeusza Kościuszki",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "2",
    "postal_code": "30-105",
    "city": "Kraków",
    "country": "PL",
    "notes": "full first+last name + slash apartment"
  },
  {
    "input": "os. Piastów 15, 31-624 Kraków",
    "number": "15",
    "street": "Piastów",
    "type": "os.",
    "postal_code": "31-624",
    "city": "Kraków",
    "country": "PL",
    "notes": "os. estate Kraków (Nowa Huta)"
  },
  {
    "input": "os. Centrum B 5, 31-927 Kraków",
    "number": "5",
    "street": "Centrum B",
    "type": "os.",
    "postal_code": "31-927",
    "city": "Kraków",
    "country": "PL",
    "notes": "os. Nowa Huta estate with letter in name"
  },
  {
    "input": "ul. Kalwaryjska 66/4, 30-504 Kraków",
    "number": "66",
    "street": "Kalwaryjska",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "4",
    "postal_code": "30-504",
    "city": "Kraków",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "ul. Wielka 21, 61-775 Poznań",
    "number": "21",
    "street": "Wielka",
    "type": "ul.",
    "postal_code": "61-775",
    "city": "Poznań",
    "country": "PL",
    "notes": "Poznań normal"
  },
  {
    "input": "ul. Półwiejska 42, 61-888 Poznań",
    "number": "42",
    "street": "Półwiejska",
    "type": "ul.",
    "postal_code": "61-888",
    "city": "Poznań",
    "country": "PL",
    "notes": "ó ł diacritics"
  },
  {
    "input": "ul. Monte Cassino 4, 70-466 Szczecin",
    "number": "4",
    "street": "Monte Cassino",
    "type": "ul.",
    "postal_code": "70-466",
    "city": "Szczecin",
    "country": "PL",
    "notes": "foreign multi-word name"
  },
  {
    "input": "ul. Bohaterów Warszawy 5, 70-370 Szczecin",
    "number": "5",
    "street": "Bohaterów Warszawy",
    "type": "ul.",
    "postal_code": "70-370",
    "city": "Szczecin",
    "country": "PL",
    "notes": "multi-word name"
  },
  {
    "input": "ul. Fordońska 246, 85-766 Bydgoszcz",
    "number": "246",
    "street": "Fordońska",
    "type": "ul.",
    "postal_code": "85-766",
    "city": "Bydgoszcz",
    "country": "PL",
    "notes": "large house number"
  },
  {
    "input": "ul. Dworcowa 81, 85-009 Bydgoszcz",
    "number": "81",
    "street": "Dworcowa",
    "type": "ul.",
    "postal_code": "85-009",
    "city": "Bydgoszcz",
    "country": "PL",
    "notes": "Bydgoszcz normal"
  },
  {
    "input": "ul. Chrobrego 3/1, 87-100 Toruń",
    "number": "3",
    "street": "Chrobrego",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "1",
    "postal_code": "87-100",
    "city": "Toruń",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "ul. Focha 12, 42-217 Częstochowa",
    "number": "12",
    "street": "Focha",
    "type": "ul.",
    "postal_code": "42-217",
    "city": "Częstochowa",
    "country": "PL",
    "notes": "Częstochowa; diacritic in city"
  },
  {
    "input": "al. Najświętszej Maryi Panny 24, 42-202 Częstochowa",
    "number": "24",
    "street": "Najświętszej Maryi Panny",
    "type": "al.",
    "postal_code": "42-202",
    "city": "Częstochowa",
    "country": "PL",
    "notes": "long multi-word al. name (NMP)"
  },
  {
    "input": "ul. Żeromskiego 55, 26-600 Radom",
    "number": "55",
    "street": "Żeromskiego",
    "type": "ul.",
    "postal_code": "26-600",
    "city": "Radom",
    "country": "PL",
    "notes": "Radom; ż diacritic"
  },
  {
    "input": "ul. Tuwima 8/10, 90-002 Łódź",
    "number": "8",
    "street": "Tuwima",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "10",
    "postal_code": "90-002",
    "city": "Łódź",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "al. Politechniki 3A, 93-590 Łódź",
    "number": "3",
    "civic_number_suffix": "A",
    "street": "Politechniki",
    "type": "al.",
    "postal_code": "93-590",
    "city": "Łódź",
    "country": "PL",
    "notes": "al. + letter suffix"
  },
  {
    "input": "ul. Piłsudskiego 40, 50-033 Wrocław",
    "number": "40",
    "street": "Piłsudskiego",
    "type": "ul.",
    "postal_code": "50-033",
    "city": "Wrocław",
    "country": "PL",
    "notes": "ł diacritic"
  },
  {
    "input": "ul. gen. Andersa 14, 00-201 Warszawa",
    "number": "14",
    "street": "gen. Andersa",
    "type": "ul.",
    "postal_code": "00-201",
    "city": "Warszawa",
    "country": "PL",
    "notes": "title 'gen.' inside street name"
  },
  {
    "input": "ul. ks. Skorupki 5, 00-546 Warszawa",
    "number": "5",
    "street": "ks. Skorupki",
    "type": "ul.",
    "postal_code": "00-546",
    "city": "Warszawa",
    "country": "PL",
    "notes": "title 'ks.' (ksiądz) inside name"
  },
  {
    "input": "ul. płk. Dąbka 3, 81-000 Gdynia",
    "number": "3",
    "street": "płk. Dąbka",
    "type": "ul.",
    "postal_code": "81-000",
    "city": "Gdynia",
    "country": "PL",
    "notes": "military rank abbrev 'płk.' in name"
  },
  {
    "input": "ul. Świętokrzyska 20/103, 00-002 Warszawa",
    "number": "20",
    "street": "Świętokrzyska",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "103",
    "postal_code": "00-002",
    "city": "Warszawa",
    "country": "PL",
    "notes": "3-digit apartment number"
  },
  {
    "input": "ul. Prosta 51/9A, 00-838 Warszawa",
    "number": "51",
    "street": "Prosta",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "9A",
    "postal_code": "00-838",
    "city": "Warszawa",
    "country": "PL",
    "notes": "apartment with letter (9A)"
  },
  {
    "input": "ul. Solec 24B/12, 00-403 Warszawa",
    "number": "24",
    "civic_number_suffix": "B",
    "street": "Solec",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "12",
    "postal_code": "00-403",
    "city": "Warszawa",
    "country": "PL",
    "notes": "suffix B + apartment 12"
  },
  {
    "input": "ul. Mokotowska 15 m. 7, 00-640 Warszawa",
    "number": "15",
    "street": "Mokotowska",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "7",
    "postal_code": "00-640",
    "city": "Warszawa",
    "country": "PL",
    "notes": "m. apartment"
  },
  {
    "input": "ul. Rakowiecka 4/20, 02-521 Warszawa",
    "number": "4",
    "street": "Rakowiecka",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "20",
    "postal_code": "02-521",
    "city": "Warszawa",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "ul. Krupnicza 22, 31-123 Kraków",
    "number": "22",
    "street": "Krupnicza",
    "type": "ul.",
    "postal_code": "31-123",
    "city": "Kraków",
    "country": "PL",
    "notes": "Kraków normal"
  },
  {
    "input": "ul. Starowiślna 30/4, 31-038 Kraków",
    "number": "30",
    "street": "Starowiślna",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "4",
    "postal_code": "31-038",
    "city": "Kraków",
    "country": "PL",
    "notes": "ś diacritic + slash apartment"
  },
  {
    "input": "ul. Basztowa 3, 31-134 Kraków",
    "number": "3",
    "street": "Basztowa",
    "type": "ul.",
    "postal_code": "31-134",
    "city": "Kraków",
    "country": "PL",
    "notes": "Kraków normal"
  },
  {
    "input": "ul. Dietla 19/3, 31-070 Kraków",
    "number": "19",
    "street": "Dietla",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "3",
    "postal_code": "31-070",
    "city": "Kraków",
    "country": "PL",
    "notes": "slash apartment"
  },
  {
    "input": "ul. Wały Chrobrego 4, 70-502 Szczecin",
    "number": "4",
    "street": "Wały Chrobrego",
    "type": "ul.",
    "postal_code": "70-502",
    "city": "Szczecin",
    "country": "PL",
    "notes": "multi-word name"
  },
  {
    "input": "ul. Aleja Róż 5, 00-556 Warszawa",
    "number": "5",
    "street": "Aleja Róż",
    "type": "ul.",
    "postal_code": "00-556",
    "city": "Warszawa",
    "country": "PL",
    "notes": "trap: 'Aleja Róż' is the NAME, prefixed by ul."
  },
  {
    "input": "ul. Nowy Świat 6/12 m. 8, 00-400 Warszawa",
    "__skip": "dual building number (6/12) plus explicit apartment",
    "number": "6/12",
    "street": "Nowy Świat",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "8",
    "postal_code": "00-400",
    "city": "Warszawa",
    "country": "PL",
    "notes": "dual civic number 6/12 + explicit m. 8 apartment"
  },
  {
    "input": "Kwiatowa 10/2, 00-001 Warszawa",
    "number": "10",
    "street": "Kwiatowa",
    "sec_unit_type": "m.",
    "sec_unit_num": "2",
    "postal_code": "00-001",
    "city": "Warszawa",
    "country": "PL",
    "notes": "Poczta Polska sample; no prefix + slash apartment"
  },
  {
    "input": "ul. Kwiatowa 10/2, 00-001 Warszawa",
    "number": "10",
    "street": "Kwiatowa",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "2",
    "postal_code": "00-001",
    "city": "Warszawa",
    "country": "PL",
    "notes": "Poczta Polska official example"
  },
  {
    "input": "20 Stycznia 1920 Roku 9/3, 85-000 Bydgoszcz",
    "number": "9",
    "street": "20 Stycznia 1920 Roku",
    "sec_unit_type": "m.",
    "sec_unit_num": "3",
    "postal_code": "85-000",
    "city": "Bydgoszcz",
    "country": "PL",
    "notes": "date-based street name with multiple numbers; house is trailing 9/3"
  },
  {
    "input": "ul. Bydgoska 3A/2, 87-100 Toruń",
    "number": "3",
    "civic_number_suffix": "A",
    "street": "Bydgoska",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "2",
    "postal_code": "87-100",
    "city": "Toruń",
    "country": "PL",
    "notes": "suffix A + slash apartment"
  },
  {
    "input": "skwer Kahla 1, 40-002 Katowice",
    "number": "1",
    "street": "Kahla",
    "type": "skwer",
    "postal_code": "40-002",
    "city": "Katowice",
    "country": "PL",
    "notes": "skwer type"
  },
  {
    "input": "ul. Grunwaldzka 411, 80-309 Gdańsk",
    "number": "411",
    "street": "Grunwaldzka",
    "type": "ul.",
    "postal_code": "80-309",
    "city": "Gdańsk",
    "country": "PL",
    "notes": "large house number Gdańsk"
  },
  {
    "input": "ul. Jana Kilińskiego 2, 90-219 Łódź",
    "number": "2",
    "street": "Jana Kilińskiego",
    "type": "ul.",
    "postal_code": "90-219",
    "city": "Łódź",
    "country": "PL",
    "notes": "first+last multi-word name"
  },
  {
    "input": "ul Piotrkowska 217, 90-451 Łódź",
    "number": "217",
    "street": "Piotrkowska",
    "type": "ul.",
    "postal_code": "90-451",
    "city": "Łódź",
    "country": "PL",
    "notes": "'ul' without dot"
  },
  {
    "input": "Al. Jerozolimskie 65/79, 00-697 Warszawa",
    "number": "65",
    "street": "Jerozolimskie",
    "type": "al.",
    "sec_unit_type": "m.",
    "sec_unit_num": "79",
    "postal_code": "00-697",
    "city": "Warszawa",
    "country": "PL",
    "notes": "capitalized 'Al.' + slash (LIM Center-style dual)"
  },
  {
    "input": "ul. Świętokrzyska 30, 00950 Warszawa",
    "__skip": "malformed dash-less postcode reformatted, defeats token-boundary search",
    "number": "30",
    "street": "Świętokrzyska",
    "type": "ul.",
    "postal_code": "00-950",
    "city": "Warszawa",
    "country": "PL",
    "notes": "malformed bare-digit zip 00950 -> reformat 00-950"
  },
  {
    "input": "ul. Powstańców Śląskich 5, 53-332 Wrocław",
    "number": "5",
    "street": "Powstańców Śląskich",
    "type": "ul.",
    "postal_code": "53-332",
    "city": "Wrocław",
    "country": "PL",
    "notes": "multi-word name with diacritics"
  },
  {
    "input": "ul. gen. Władysława Sikorskiego 2/8, 65-454 Zielona Góra",
    "number": "2",
    "street": "gen. Władysława Sikorskiego",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "8",
    "postal_code": "65-454",
    "city": "Zielona Góra",
    "country": "PL",
    "notes": "rank + full name; multi-word city Zielona Góra"
  },
  {
    "input": "ul. Katowicka 47, 41-500 Chorzów",
    "number": "47",
    "street": "Katowicka",
    "type": "ul.",
    "postal_code": "41-500",
    "city": "Chorzów",
    "country": "PL",
    "notes": "Chorzów normal"
  },
  {
    "input": "ul. 3 Maja 12/4, 43-300 Bielsko-Biała",
    "number": "12",
    "street": "3 Maja",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "4",
    "postal_code": "43-300",
    "city": "Bielsko-Biała",
    "country": "PL",
    "notes": "numbered name + slash apt; hyphenated city"
  },
  {
    "input": "ul. Zamkowa 8, 82-300 Elbląg",
    "number": "8",
    "street": "Zamkowa",
    "type": "ul.",
    "postal_code": "82-300",
    "city": "Elbląg",
    "country": "PL",
    "notes": "Elbląg; ą diacritic in city"
  },
  {
    "input": "ul. Wojska Polskiego 1, 66-400 Gorzów Wielkopolski",
    "number": "1",
    "street": "Wojska Polskiego",
    "type": "ul.",
    "postal_code": "66-400",
    "city": "Gorzów Wielkopolski",
    "country": "PL",
    "notes": "multi-word city name"
  },
  {
    "input": "ul. Krakowska 24/6, 33-300 Nowy Sącz",
    "number": "24",
    "street": "Krakowska",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "6",
    "postal_code": "33-300",
    "city": "Nowy Sącz",
    "country": "PL",
    "notes": "multi-word city Nowy Sącz + slash apt"
  },
  {
    "input": "ul. Sikorskiego 3, 44-330 Jastrzębie-Zdrój",
    "number": "3",
    "street": "Sikorskiego",
    "type": "ul.",
    "postal_code": "44-330",
    "city": "Jastrzębie-Zdrój",
    "country": "PL",
    "notes": "hyphenated city with diacritic"
  },
  {
    "input": "ul. Niepodległości 14, 41-700 Ruda Śląska",
    "number": "14",
    "street": "Niepodległości",
    "type": "ul.",
    "postal_code": "41-700",
    "city": "Ruda Śląska",
    "country": "PL",
    "notes": "multi-word city Ruda Śląska"
  },
  {
    "input": "ul. Kościuszki 20 m 4, 41-300 Dąbrowa Górnicza",
    "number": "20",
    "street": "Kościuszki",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "4",
    "postal_code": "41-300",
    "city": "Dąbrowa Górnicza",
    "country": "PL",
    "notes": "m without dot + multi-word city"
  },
  {
    "input": "ul. 1 Maja 45, 58-300 Wałbrzych",
    "number": "45",
    "street": "1 Maja",
    "type": "ul.",
    "postal_code": "58-300",
    "city": "Wałbrzych",
    "country": "PL",
    "notes": "numbered street name Wałbrzych"
  },
  {
    "input": "ul. Tumska 6, 09-402 Płock",
    "number": "6",
    "street": "Tumska",
    "type": "ul.",
    "postal_code": "09-402",
    "city": "Płock",
    "country": "PL",
    "notes": "leading-zero zip 09-; Płock"
  },
  {
    "input": "ul. Piłsudskiego 2/17, 08-110 Siedlce",
    "number": "2",
    "street": "Piłsudskiego",
    "type": "ul.",
    "sec_unit_type": "m.",
    "sec_unit_num": "17",
    "postal_code": "08-110",
    "city": "Siedlce",
    "country": "PL",
    "notes": "leading-zero zip 08-; slash apartment"
  },
  {
    "input": "ul. Kolejowa 3, 22-400 Zamość",
    "number": "3",
    "street": "Kolejowa",
    "type": "ul.",
    "postal_code": "22-400",
    "city": "Zamość",
    "country": "PL",
    "notes": "Zamość; ś diacritic in city"
  },
  {
    "input": "os. Słoneczne 12/3, 71-518 Szczecin",
    "number": "12",
    "street": "Słoneczne",
    "type": "os.",
    "sec_unit_type": "m.",
    "sec_unit_num": "3",
    "postal_code": "71-518",
    "city": "Szczecin",
    "country": "PL",
    "notes": "os. estate + block/flat slash"
  },
  {
    "input": "bulw. Nadmorski 8, 81-772 Sopot",
    "number": "8",
    "street": "Nadmorski",
    "type": "bulw.",
    "postal_code": "81-772",
    "city": "Sopot",
    "country": "PL",
    "notes": "bulwar (boulevard) type"
  },
  {
    "input": "ul. Bohaterów Monte Cassino 53, 81-767 Sopot",
    "number": "53",
    "street": "Bohaterów Monte Cassino",
    "type": "ul.",
    "postal_code": "81-767",
    "city": "Sopot",
    "country": "PL",
    "notes": "long multi-word name (Monciak), Sopot"
  }
];
