// AUTO-GENERATED from research sub-agent corpus (samples-pt.json).
// Ground-truth field breakdowns for PT addresses; consumed by __tests__/eu.spec.ts.
import type { EuSample } from "./types";

export const ptSamples: EuSample[] = [
  {
    "input": "Rua Augusta 100, 1100-053 Lisboa",
    "number": "100",
    "street": "Augusta",
    "type": "Rua",
    "postal_code": "1100-053",
    "city": "Lisboa",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Avenida da Liberdade 200, 1250-096 Lisboa",
    "number": "200",
    "street": "da Liberdade",
    "type": "Avenida",
    "postal_code": "1250-096",
    "city": "Lisboa",
    "country": "PT",
    "notes": "particle da kept"
  },
  {
    "input": "Praça do Comércio 5, 1100-148 Lisboa",
    "number": "5",
    "street": "do Comércio",
    "type": "Praça",
    "postal_code": "1100-148",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented type, particle do"
  },
  {
    "input": "Largo do Chiado 12, 1200-108 Lisboa",
    "number": "12",
    "street": "do Chiado",
    "type": "Largo",
    "postal_code": "1200-108",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Largo type"
  },
  {
    "input": "Travessa da Queimada 30, 1200-365 Lisboa",
    "number": "30",
    "street": "da Queimada",
    "type": "Travessa",
    "postal_code": "1200-365",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Travessa type"
  },
  {
    "input": "Rua Garrett 50, 3º Esq, 1200-203 Lisboa",
    "number": "50",
    "street": "Garrett",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Esq",
    "postal_code": "1200-203",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side left"
  },
  {
    "input": "Rua Garrett 50 3º Dto, 1200-203 Lisboa",
    "number": "50",
    "street": "Garrett",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Dto",
    "postal_code": "1200-203",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side right"
  },
  {
    "input": "Rua do Ouro 100 R/C, 1100-063 Lisboa",
    "number": "100",
    "street": "do Ouro",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C",
    "postal_code": "1100-063",
    "city": "Lisboa",
    "country": "PT",
    "notes": "ground floor R/C"
  },
  {
    "input": "Rua da Prata 80 1º, 1100-415 Lisboa",
    "number": "80",
    "street": "da Prata",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º",
    "postal_code": "1100-415",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor only 1º"
  },
  {
    "input": "Avenida da Liberdade nº 245, 1250-142 Lisboa",
    "number": "245",
    "street": "da Liberdade",
    "type": "Avenida",
    "postal_code": "1250-142",
    "city": "Lisboa",
    "country": "PT",
    "notes": "nº marker"
  },
  {
    "input": "R. Augusta 100, 1100-053 Lisboa",
    "number": "100",
    "street": "Augusta",
    "type": "R.",
    "postal_code": "1100-053",
    "city": "Lisboa",
    "country": "PT",
    "notes": "abbrev R."
  },
  {
    "input": "Av. da Liberdade 200, 1250-096 Lisboa",
    "number": "200",
    "street": "da Liberdade",
    "type": "Av.",
    "postal_code": "1250-096",
    "city": "Lisboa",
    "country": "PT",
    "notes": "abbrev Av."
  },
  {
    "input": "Pç. do Comércio 5, 1100-148 Lisboa",
    "number": "5",
    "street": "do Comércio",
    "type": "Pç.",
    "postal_code": "1100-148",
    "city": "Lisboa",
    "country": "PT",
    "notes": "abbrev Praça"
  },
  {
    "input": "Tv. da Queimada 30, 1200-365 Lisboa",
    "number": "30",
    "street": "da Queimada",
    "type": "Tv.",
    "postal_code": "1200-365",
    "city": "Lisboa",
    "country": "PT",
    "notes": "abbrev Travessa"
  },
  {
    "input": "Calçada da Glória 47, 1250-096 Lisboa",
    "number": "47",
    "street": "da Glória",
    "type": "Calçada",
    "postal_code": "1250-096",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented Calçada type"
  },
  {
    "input": "Beco do Carneiro 8, 1100-140 Lisboa",
    "number": "8",
    "street": "do Carneiro",
    "type": "Beco",
    "postal_code": "1100-140",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Beco type"
  },
  {
    "input": "Alameda dos Oceanos 15, 1990-203 Lisboa",
    "number": "15",
    "street": "dos Oceanos",
    "type": "Alameda",
    "postal_code": "1990-203",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Alameda type, particle dos"
  },
  {
    "input": "Estrada de Benfica 500, 1500-108 Lisboa",
    "number": "500",
    "street": "de Benfica",
    "type": "Estrada",
    "postal_code": "1500-108",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Estrada type, particle de"
  },
  {
    "input": "Praceta João de Deus 4, 2775-598 Carcavelos",
    "number": "4",
    "street": "João de Deus",
    "type": "Praceta",
    "postal_code": "2775-598",
    "city": "Carcavelos",
    "country": "PT",
    "notes": "Praceta type"
  },
  {
    "input": "Rua de Santa Catarina 100, 4000-447 Porto",
    "number": "100",
    "street": "de Santa Catarina",
    "type": "Rua",
    "postal_code": "4000-447",
    "city": "Porto",
    "country": "PT",
    "notes": "Rua de particle, Porto"
  },
  {
    "input": "Rua dos Clérigos 32, 4050-204 Porto",
    "number": "32",
    "street": "dos Clérigos",
    "type": "Rua",
    "postal_code": "4050-204",
    "city": "Porto",
    "country": "PT",
    "notes": "particle dos, Porto"
  },
  {
    "input": "Avenida dos Aliados 150, 4000-064 Porto",
    "number": "150",
    "street": "dos Aliados",
    "type": "Avenida",
    "postal_code": "4000-064",
    "city": "Porto",
    "country": "PT",
    "notes": "Porto avenue"
  },
  {
    "input": "Rua de Cedofeita 245, 4050-181 Porto",
    "number": "245",
    "street": "de Cedofeita",
    "type": "Rua",
    "postal_code": "4050-181",
    "city": "Porto",
    "country": "PT",
    "notes": "Rua de Porto"
  },
  {
    "input": "Rua de Santa Catarina 100, 2º Dto, 4000-447 Porto",
    "number": "100",
    "street": "de Santa Catarina",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Dto",
    "postal_code": "4000-447",
    "city": "Porto",
    "country": "PT",
    "notes": "particle + floor+side"
  },
  {
    "input": "Rua Alexandre Ferreira 24B, 1750-011 Lisboa",
    "number": "24",
    "civic_number_suffix": "B",
    "street": "Alexandre Ferreira",
    "type": "Rua",
    "postal_code": "1750-011",
    "city": "Lisboa",
    "country": "PT",
    "notes": "civic number alpha suffix"
  },
  {
    "input": "Avenida Marconi 4C, 1000-205 Lisboa",
    "number": "4",
    "civic_number_suffix": "C",
    "street": "Marconi",
    "type": "Avenida",
    "postal_code": "1000-205",
    "city": "Lisboa",
    "country": "PT",
    "notes": "civic suffix C"
  },
  {
    "input": "Rua do Poço dos Negros 53, 2º, 1200-336 Lisboa",
    "number": "53",
    "street": "do Poço dos Negros",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º",
    "postal_code": "1200-336",
    "city": "Lisboa",
    "country": "PT",
    "notes": "multi-word name, floor"
  },
  {
    "input": "Praça do Município 6, 1100-365 Lisboa",
    "number": "6",
    "street": "do Município",
    "type": "Praça",
    "postal_code": "1100-365",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented type"
  },
  {
    "input": "Beco da Rua do Mercado 10, 3020-879 Souselas",
    "number": "10",
    "street": "da Rua do Mercado",
    "type": "Beco",
    "postal_code": "3020-879",
    "city": "Souselas",
    "country": "PT",
    "notes": "long name, Coimbra region"
  },
  {
    "input": "Rua Ferreira Borges 78, 3000-180 Coimbra",
    "number": "78",
    "street": "Ferreira Borges",
    "type": "Rua",
    "postal_code": "3000-180",
    "city": "Coimbra",
    "country": "PT",
    "notes": "Coimbra"
  },
  {
    "input": "Avenida Sá da Bandeira 90, 3000-350 Coimbra",
    "number": "90",
    "street": "Sá da Bandeira",
    "type": "Avenida",
    "postal_code": "3000-350",
    "city": "Coimbra",
    "country": "PT",
    "notes": "accented name Sá"
  },
  {
    "input": "Rua da Sofia 120, 3000-389 Coimbra",
    "number": "120",
    "street": "da Sofia",
    "type": "Rua",
    "postal_code": "3000-389",
    "city": "Coimbra",
    "country": "PT",
    "notes": "Rua da Coimbra"
  },
  {
    "input": "Rua do Souto 55, 4700-328 Braga",
    "number": "55",
    "street": "do Souto",
    "type": "Rua",
    "postal_code": "4700-328",
    "city": "Braga",
    "country": "PT",
    "notes": "Braga"
  },
  {
    "input": "Avenida Central 40, 4710-229 Braga",
    "number": "40",
    "street": "Central",
    "type": "Avenida",
    "postal_code": "4710-229",
    "city": "Braga",
    "country": "PT",
    "notes": "Braga avenue"
  },
  {
    "input": "Largo do Paço 1, 4704-514 Braga",
    "number": "1",
    "street": "do Paço",
    "type": "Largo",
    "postal_code": "4704-514",
    "city": "Braga",
    "country": "PT",
    "notes": "Largo, accented Paço"
  },
  {
    "input": "Rua de Santo António 200, 8000-308 Faro",
    "number": "200",
    "street": "de Santo António",
    "type": "Rua",
    "postal_code": "8000-308",
    "city": "Faro",
    "country": "PT",
    "notes": "Algarve, Rua de"
  },
  {
    "input": "Rua Conselheiro Bívar 55, 8000-255 Faro",
    "number": "55",
    "street": "Conselheiro Bívar",
    "type": "Rua",
    "postal_code": "8000-255",
    "city": "Faro",
    "country": "PT",
    "notes": "accented Bívar"
  },
  {
    "input": "Avenida 5 de Outubro 30, 8000-076 Faro",
    "number": "30",
    "street": "5 de Outubro",
    "type": "Avenida",
    "postal_code": "8000-076",
    "city": "Faro",
    "country": "PT",
    "notes": "numeric street name plus door number"
  },
  {
    "input": "Rua Direita 12, 2900-401 Setúbal",
    "number": "12",
    "street": "Direita",
    "type": "Rua",
    "postal_code": "2900-401",
    "city": "Setúbal",
    "country": "PT",
    "notes": "accented locality Setúbal; Direita is name not side"
  },
  {
    "input": "Avenida Luísa Todi 300, 2900-462 Setúbal",
    "number": "300",
    "street": "Luísa Todi",
    "type": "Avenida",
    "postal_code": "2900-462",
    "city": "Setúbal",
    "country": "PT",
    "notes": "accented name"
  },
  {
    "input": "Rua de Aveiro 20, 3800-102 Aveiro",
    "number": "20",
    "street": "de Aveiro",
    "type": "Rua",
    "postal_code": "3800-102",
    "city": "Aveiro",
    "country": "PT",
    "notes": "Aveiro"
  },
  {
    "input": "Rua Direita 45, 4º Esq, 3800-072 Aveiro",
    "number": "45",
    "street": "Direita",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "4º Esq",
    "postal_code": "3800-072",
    "city": "Aveiro",
    "country": "PT",
    "notes": "name Direita + floor+side"
  },
  {
    "input": "Rua João de Deus 88, 9000-039 Funchal",
    "number": "88",
    "street": "João de Deus",
    "type": "Rua",
    "postal_code": "9000-039",
    "city": "Funchal",
    "country": "PT",
    "notes": "Madeira, region 9"
  },
  {
    "input": "Avenida do Mar 25, 9000-054 Funchal",
    "number": "25",
    "street": "do Mar",
    "type": "Avenida",
    "postal_code": "9000-054",
    "city": "Funchal",
    "country": "PT",
    "notes": "Madeira"
  },
  {
    "input": "Rua de Lisboa 10, 9500-049 Ponta Delgada",
    "number": "10",
    "street": "de Lisboa",
    "type": "Rua",
    "postal_code": "9500-049",
    "city": "Ponta Delgada",
    "country": "PT",
    "notes": "Azores, multi-word locality"
  },
  {
    "input": "Rua Direita 15, 1º Dto, 9700-167 Angra do Heroísmo",
    "number": "15",
    "street": "Direita",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Dto",
    "postal_code": "9700-167",
    "city": "Angra do Heroísmo",
    "country": "PT",
    "notes": "Azores, long locality, accented"
  },
  {
    "input": "Rua Cândido dos Reis 60, 4400-071 Vila Nova de Gaia",
    "number": "60",
    "street": "Cândido dos Reis",
    "type": "Rua",
    "postal_code": "4400-071",
    "city": "Vila Nova de Gaia",
    "country": "PT",
    "notes": "multi-word locality"
  },
  {
    "input": "Avenida da República 200, 4430-190 Vila Nova de Gaia",
    "number": "200",
    "street": "da República",
    "type": "Avenida",
    "postal_code": "4430-190",
    "city": "Vila Nova de Gaia",
    "country": "PT",
    "notes": "multi-word locality, accented República"
  },
  {
    "input": "Rua do Comércio 33, 4900-321 Viana do Castelo",
    "number": "33",
    "street": "do Comércio",
    "type": "Rua",
    "postal_code": "4900-321",
    "city": "Viana do Castelo",
    "country": "PT",
    "notes": "multi-word locality"
  },
  {
    "input": "Praça da República 5, 4990-062 Ponte de Lima",
    "number": "5",
    "street": "da República",
    "type": "Praça",
    "postal_code": "4990-062",
    "city": "Ponte de Lima",
    "country": "PT",
    "notes": "multi-word locality Ponte de Lima"
  },
  {
    "input": "Rua Bernardo Ribeiro 18, 4480-809 Vila do Conde",
    "number": "18",
    "street": "Bernardo Ribeiro",
    "type": "Rua",
    "postal_code": "4480-809",
    "city": "Vila do Conde",
    "country": "PT",
    "notes": "multi-word locality"
  },
  {
    "input": "Rua 5 de Outubro 44, 2670-478 Loures",
    "number": "44",
    "street": "5 de Outubro",
    "type": "Rua",
    "postal_code": "2670-478",
    "city": "Loures",
    "country": "PT",
    "notes": "numeric-date street name"
  },
  {
    "input": "Rua 1º de Maio 10, 2830-355 Barreiro",
    "number": "10",
    "street": "1º de Maio",
    "type": "Rua",
    "postal_code": "2830-355",
    "city": "Barreiro",
    "country": "PT",
    "notes": "ordinal in name, not floor"
  },
  {
    "input": "Rua 25 de Abril 200, 2765-273 Estoril",
    "number": "200",
    "street": "25 de Abril",
    "type": "Rua",
    "postal_code": "2765-273",
    "city": "Estoril",
    "country": "PT",
    "notes": "date name plus door number"
  },
  {
    "input": "Avenida 25 de Abril 88, 2750-511 Cascais",
    "number": "88",
    "street": "25 de Abril",
    "type": "Avenida",
    "postal_code": "2750-511",
    "city": "Cascais",
    "country": "PT",
    "notes": "Cascais"
  },
  {
    "input": "Rua do Mercado 7, R/C Dto, 2750-368 Cascais",
    "number": "7",
    "street": "do Mercado",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C Dto",
    "postal_code": "2750-368",
    "city": "Cascais",
    "country": "PT",
    "notes": "ground floor + side"
  },
  {
    "input": "Rua da Junqueira 295, 1300-343 Lisboa",
    "number": "295",
    "street": "da Junqueira",
    "type": "Rua",
    "postal_code": "1300-343",
    "city": "Lisboa",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Rua do Alecrim 70, 1200-018 Lisboa",
    "number": "70",
    "street": "do Alecrim",
    "type": "Rua",
    "postal_code": "1200-018",
    "city": "Lisboa",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Rua da Misericórdia 14, 1249-038 Lisboa",
    "number": "14",
    "street": "da Misericórdia",
    "type": "Rua",
    "postal_code": "1249-038",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented Misericórdia"
  },
  {
    "input": "Rua de São Bento 300, 1200-821 Lisboa",
    "number": "300",
    "street": "de São Bento",
    "type": "Rua",
    "postal_code": "1200-821",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Rua de São, accented"
  },
  {
    "input": "Rua da Escola Politécnica 58, 1250-102 Lisboa",
    "number": "58",
    "street": "da Escola Politécnica",
    "type": "Rua",
    "postal_code": "1250-102",
    "city": "Lisboa",
    "country": "PT",
    "notes": "long name, accented"
  },
  {
    "input": "Avenida Almirante Reis 100, 4º Dto, 1150-020 Lisboa",
    "number": "100",
    "street": "Almirante Reis",
    "type": "Avenida",
    "sec_unit_type": "Andar",
    "sec_unit_num": "4º Dto",
    "postal_code": "1150-020",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Avenida de Roma 45, 2º Esq, 1000-265 Lisboa",
    "number": "45",
    "street": "de Roma",
    "type": "Avenida",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Esq",
    "postal_code": "1000-265",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Avenida de + floor+side"
  },
  {
    "input": "Rua Castilho 65, 5º, 1250-068 Lisboa",
    "number": "65",
    "street": "Castilho",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "5º",
    "postal_code": "1250-068",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor only"
  },
  {
    "input": "Rua Braamcamp 40, 6º Dto, 1250-050 Lisboa",
    "number": "40",
    "street": "Braamcamp",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "6º Dto",
    "postal_code": "1250-050",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Rua Rodrigo da Fonseca 88, R/C, 1250-190 Lisboa",
    "number": "88",
    "street": "Rodrigo da Fonseca",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C",
    "postal_code": "1250-190",
    "city": "Lisboa",
    "country": "PT",
    "notes": "name with da, ground floor"
  },
  {
    "input": "Rua Alexandre Herculano 25, 1º Esq, 1250-008 Lisboa",
    "number": "25",
    "street": "Alexandre Herculano",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Esq",
    "postal_code": "1250-008",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Avenida António Augusto de Aguiar 120, 1050-016 Lisboa",
    "number": "120",
    "street": "António Augusto de Aguiar",
    "type": "Avenida",
    "postal_code": "1050-016",
    "city": "Lisboa",
    "country": "PT",
    "notes": "long name with de"
  },
  {
    "input": "Avenida Fontes Pereira de Melo 19, 1050-116 Lisboa",
    "number": "19",
    "street": "Fontes Pereira de Melo",
    "type": "Avenida",
    "postal_code": "1050-116",
    "city": "Lisboa",
    "country": "PT",
    "notes": "long name with de"
  },
  {
    "input": "Rua Pascoal de Melo 50, 3º Dto, 1000-232 Lisboa",
    "number": "50",
    "street": "Pascoal de Melo",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Dto",
    "postal_code": "1000-232",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor+side right"
  },
  {
    "input": "Rua da Beneficência 200, 1600-018 Lisboa",
    "number": "200",
    "street": "da Beneficência",
    "type": "Rua",
    "postal_code": "1600-018",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented"
  },
  {
    "input": "Avenida de Berna 26, 1069-061 Lisboa",
    "number": "26",
    "street": "de Berna",
    "type": "Avenida",
    "postal_code": "1069-061",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Avenida de"
  },
  {
    "input": "Rua Marquês de Fronteira 8, 2º, 1070-296 Lisboa",
    "number": "8",
    "street": "Marquês de Fronteira",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º",
    "postal_code": "1070-296",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented Marquês, floor"
  },
  {
    "input": "Rua de Campolide 100, 1070-030 Lisboa",
    "number": "100",
    "street": "de Campolide",
    "type": "Rua",
    "postal_code": "1070-030",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Rua de"
  },
  {
    "input": "Rua Gonçalves Zarco 15, 1400-183 Lisboa",
    "number": "15",
    "street": "Gonçalves Zarco",
    "type": "Rua",
    "postal_code": "1400-183",
    "city": "Lisboa",
    "country": "PT",
    "notes": "accented Gonçalves"
  },
  {
    "input": "Praça de Londres 3, 1000-192 Lisboa",
    "number": "3",
    "street": "de Londres",
    "type": "Praça",
    "postal_code": "1000-192",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Praça de"
  },
  {
    "input": "Praça de Espanha 12, 1500-289 Lisboa",
    "number": "12",
    "street": "de Espanha",
    "type": "Praça",
    "postal_code": "1500-289",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Praça de"
  },
  {
    "input": "Largo de São Domingos 20, 1150-320 Lisboa",
    "number": "20",
    "street": "de São Domingos",
    "type": "Largo",
    "postal_code": "1150-320",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Largo de São"
  },
  {
    "input": "Travessa do Carmo 1, 1200-092 Lisboa",
    "number": "1",
    "street": "do Carmo",
    "type": "Travessa",
    "postal_code": "1200-092",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Travessa"
  },
  {
    "input": "Calçada do Combro 55, 1200-114 Lisboa",
    "number": "55",
    "street": "do Combro",
    "type": "Calçada",
    "postal_code": "1200-114",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Calçada"
  },
  {
    "input": "Estrada da Luz 90, 1600-159 Lisboa",
    "number": "90",
    "street": "da Luz",
    "type": "Estrada",
    "postal_code": "1600-159",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Estrada"
  },
  {
    "input": "Alameda Dom Afonso Henriques 7, 1000-123 Lisboa",
    "number": "7",
    "street": "Dom Afonso Henriques",
    "type": "Alameda",
    "postal_code": "1000-123",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Alameda long name"
  },
  {
    "input": "Rua de Cedofeita 100, 3º Esq, 4050-181 Porto",
    "number": "100",
    "street": "de Cedofeita",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Esq",
    "postal_code": "4050-181",
    "city": "Porto",
    "country": "PT",
    "notes": "Rua de + floor+side"
  },
  {
    "input": "Rua Miguel Bombarda 285, 4050-377 Porto",
    "number": "285",
    "street": "Miguel Bombarda",
    "type": "Rua",
    "postal_code": "4050-377",
    "city": "Porto",
    "country": "PT",
    "notes": "Porto"
  },
  {
    "input": "Rua da Boavista 100, R/C, 4050-107 Porto",
    "number": "100",
    "street": "da Boavista",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C",
    "postal_code": "4050-107",
    "city": "Porto",
    "country": "PT",
    "notes": "ground floor"
  },
  {
    "input": "Avenida da Boavista 1200, 4100-130 Porto",
    "number": "1200",
    "street": "da Boavista",
    "type": "Avenida",
    "postal_code": "4100-130",
    "city": "Porto",
    "country": "PT",
    "notes": "large door number"
  },
  {
    "input": "Rua de Sá da Bandeira 400, 4000-431 Porto",
    "number": "400",
    "street": "de Sá da Bandeira",
    "type": "Rua",
    "postal_code": "4000-431",
    "city": "Porto",
    "country": "PT",
    "notes": "Rua de, accented"
  },
  {
    "input": "Praça da Liberdade 25, 4000-322 Porto",
    "number": "25",
    "street": "da Liberdade",
    "type": "Praça",
    "postal_code": "4000-322",
    "city": "Porto",
    "country": "PT",
    "notes": "Praça"
  },
  {
    "input": "Rua de Santa Catarina 200, 1º Dto, 4000-447 Porto",
    "number": "200",
    "street": "de Santa Catarina",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Dto",
    "postal_code": "4000-447",
    "city": "Porto",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Rua Formosa 300, 4000-249 Porto",
    "number": "300",
    "street": "Formosa",
    "type": "Rua",
    "postal_code": "4000-249",
    "city": "Porto",
    "country": "PT",
    "notes": "Porto"
  },
  {
    "input": "Rua do Almada 150, 4050-036 Porto",
    "number": "150",
    "street": "do Almada",
    "type": "Rua",
    "postal_code": "4050-036",
    "city": "Porto",
    "country": "PT",
    "notes": "Porto"
  },
  {
    "input": "Rua do Bonfim 500, 4300-069 Porto",
    "number": "500",
    "street": "do Bonfim",
    "type": "Rua",
    "postal_code": "4300-069",
    "city": "Porto",
    "country": "PT",
    "notes": "Porto"
  },
  {
    "input": "Rua Direita de Francos 88, 2º Esq, 4250-194 Porto",
    "number": "88",
    "street": "Direita de Francos",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Esq",
    "postal_code": "4250-194",
    "city": "Porto",
    "country": "PT",
    "notes": "Direita in name, floor+side"
  },
  {
    "input": "Rua Visconde da Luz 30, 3000-414 Coimbra",
    "number": "30",
    "street": "Visconde da Luz",
    "type": "Rua",
    "postal_code": "3000-414",
    "city": "Coimbra",
    "country": "PT",
    "notes": "Coimbra"
  },
  {
    "input": "Praça 8 de Maio 15, 3000-300 Coimbra",
    "number": "15",
    "street": "8 de Maio",
    "type": "Praça",
    "postal_code": "3000-300",
    "city": "Coimbra",
    "country": "PT",
    "notes": "numeric-date name"
  },
  {
    "input": "Rua Larga 40, 3004-504 Coimbra",
    "number": "40",
    "street": "Larga",
    "type": "Rua",
    "postal_code": "3004-504",
    "city": "Coimbra",
    "country": "PT",
    "notes": "Coimbra"
  },
  {
    "input": "Rua do Brasil 200, 1º Dto, 3030-175 Coimbra",
    "number": "200",
    "street": "do Brasil",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Dto",
    "postal_code": "3030-175",
    "city": "Coimbra",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Avenida Emídio Navarro 70, 3000-150 Coimbra",
    "number": "70",
    "street": "Emídio Navarro",
    "type": "Avenida",
    "postal_code": "3000-150",
    "city": "Coimbra",
    "country": "PT",
    "notes": "accented Emídio"
  },
  {
    "input": "Rua do Taxa 12, 4715-459 Braga",
    "number": "12",
    "street": "do Taxa",
    "type": "Rua",
    "postal_code": "4715-459",
    "city": "Braga",
    "country": "PT",
    "notes": "Braga"
  },
  {
    "input": "Rua dos Chãos 55, 3º, 4700-376 Braga",
    "number": "55",
    "street": "dos Chãos",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º",
    "postal_code": "4700-376",
    "city": "Braga",
    "country": "PT",
    "notes": "accented Chãos, floor"
  },
  {
    "input": "Avenida João XXI 8, 4715-036 Braga",
    "number": "8",
    "street": "João XXI",
    "type": "Avenida",
    "postal_code": "4715-036",
    "city": "Braga",
    "country": "PT",
    "notes": "roman numeral in name"
  },
  {
    "input": "Rua de São João 20, R/C Esq, 4700-227 Braga",
    "number": "20",
    "street": "de São João",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C Esq",
    "postal_code": "4700-227",
    "city": "Braga",
    "country": "PT",
    "notes": "ground floor + side"
  },
  {
    "input": "Rua de Vale de Cavalos 3, 8005-146 Faro",
    "number": "3",
    "street": "de Vale de Cavalos",
    "type": "Rua",
    "postal_code": "8005-146",
    "city": "Faro",
    "country": "PT",
    "notes": "multiple particles in name"
  },
  {
    "input": "Rua de Portugal 45, 8000-281 Faro",
    "number": "45",
    "street": "de Portugal",
    "type": "Rua",
    "postal_code": "8000-281",
    "city": "Faro",
    "country": "PT",
    "notes": "Rua de"
  },
  {
    "input": "Rua Pé da Cruz 30, 2º, 8000-407 Faro",
    "number": "30",
    "street": "Pé da Cruz",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º",
    "postal_code": "8000-407",
    "city": "Faro",
    "country": "PT",
    "notes": "accented Pé, floor"
  },
  {
    "input": "Avenida Tomás Cabreira 50, 8500-802 Portimão",
    "number": "50",
    "street": "Tomás Cabreira",
    "type": "Avenida",
    "postal_code": "8500-802",
    "city": "Portimão",
    "country": "PT",
    "notes": "accented Tomás and Portimão"
  },
  {
    "input": "Rua Direita 22, 8600-701 Lagos",
    "number": "22",
    "street": "Direita",
    "type": "Rua",
    "postal_code": "8600-701",
    "city": "Lagos",
    "country": "PT",
    "notes": "Algarve Lagos"
  },
  {
    "input": "Rua 5 de Outubro 88, 8100-594 Loulé",
    "number": "88",
    "street": "5 de Outubro",
    "type": "Rua",
    "postal_code": "8100-594",
    "city": "Loulé",
    "country": "PT",
    "notes": "accented Loulé"
  },
  {
    "input": "Rua Serpa Pinto 12, 3º Dto, 2900-579 Setúbal",
    "number": "12",
    "street": "Serpa Pinto",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Dto",
    "postal_code": "2900-579",
    "city": "Setúbal",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Praça do Bocage 40, 2900-322 Setúbal",
    "number": "40",
    "street": "do Bocage",
    "type": "Praça",
    "postal_code": "2900-322",
    "city": "Setúbal",
    "country": "PT",
    "notes": "Praça"
  },
  {
    "input": "Rua Combatentes da Grande Guerra 100, 2910-353 Setúbal",
    "number": "100",
    "street": "Combatentes da Grande Guerra",
    "type": "Rua",
    "postal_code": "2910-353",
    "city": "Setúbal",
    "country": "PT",
    "notes": "long name"
  },
  {
    "input": "Rua de Aveiro 15, 2º Esq, 3800-102 Aveiro",
    "number": "15",
    "street": "de Aveiro",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Esq",
    "postal_code": "3800-102",
    "city": "Aveiro",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Rua João Mendonça 8, 3800-200 Aveiro",
    "number": "8",
    "street": "João Mendonça",
    "type": "Rua",
    "postal_code": "3800-200",
    "city": "Aveiro",
    "country": "PT",
    "notes": "Aveiro"
  },
  {
    "input": "Avenida Dr. Lourenço Peixinho 90, 3800-164 Aveiro",
    "number": "90",
    "street": "Dr. Lourenço Peixinho",
    "type": "Avenida",
    "postal_code": "3800-164",
    "city": "Aveiro",
    "country": "PT",
    "notes": "title Dr. in name, accented"
  },
  {
    "input": "Rua Marquês de Pombal 30, R/C, 3810-124 Aveiro",
    "number": "30",
    "street": "Marquês de Pombal",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C",
    "postal_code": "3810-124",
    "city": "Aveiro",
    "country": "PT",
    "notes": "ground floor"
  },
  {
    "input": "Rua da Carreira 45, 9000-042 Funchal",
    "number": "45",
    "street": "da Carreira",
    "type": "Rua",
    "postal_code": "9000-042",
    "city": "Funchal",
    "country": "PT",
    "notes": "Madeira"
  },
  {
    "input": "Rua Fernão de Ornelas 56, 2º Dto, 9050-024 Funchal",
    "number": "56",
    "street": "Fernão de Ornelas",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Dto",
    "postal_code": "9050-024",
    "city": "Funchal",
    "country": "PT",
    "notes": "accented Fernão, floor+side"
  },
  {
    "input": "Avenida Arriaga 30, 9000-064 Funchal",
    "number": "30",
    "street": "Arriaga",
    "type": "Avenida",
    "postal_code": "9000-064",
    "city": "Funchal",
    "country": "PT",
    "notes": "Madeira"
  },
  {
    "input": "Rua da Boa Vista 10, 1º Esq, 9500-089 Ponta Delgada",
    "number": "10",
    "street": "da Boa Vista",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Esq",
    "postal_code": "9500-089",
    "city": "Ponta Delgada",
    "country": "PT",
    "notes": "Azores, floor+side"
  },
  {
    "input": "Rua do Rego 25, 3020-451 Coimbra",
    "number": "25",
    "street": "do Rego",
    "type": "Rua",
    "postal_code": "3020-451",
    "city": "Coimbra",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Rua da Estação 5, 2005-183 Santarém",
    "number": "5",
    "street": "da Estação",
    "type": "Rua",
    "postal_code": "2005-183",
    "city": "Santarém",
    "country": "PT",
    "notes": "accented Estação and Santarém"
  },
  {
    "input": "Rua Serpa Pinto 44, 3º Dto, 2000-045 Santarém",
    "number": "44",
    "street": "Serpa Pinto",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Dto",
    "postal_code": "2000-045",
    "city": "Santarém",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Praça Sá Carneiro 8, 2410-108 Leiria",
    "number": "8",
    "street": "Sá Carneiro",
    "type": "Praça",
    "postal_code": "2410-108",
    "city": "Leiria",
    "country": "PT",
    "notes": "accented Sá"
  },
  {
    "input": "Rua Barão de Viamonte 100, 2400-127 Leiria",
    "number": "100",
    "street": "Barão de Viamonte",
    "type": "Rua",
    "postal_code": "2400-127",
    "city": "Leiria",
    "country": "PT",
    "notes": "accented Barão"
  },
  {
    "input": "Rua de Diu 20, R/C Dto, 2410-125 Leiria",
    "number": "20",
    "street": "de Diu",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C Dto",
    "postal_code": "2410-125",
    "city": "Leiria",
    "country": "PT",
    "notes": "ground floor + side"
  },
  {
    "input": "Rua Nova 30, 7000-537 Évora",
    "number": "30",
    "street": "Nova",
    "type": "Rua",
    "postal_code": "7000-537",
    "city": "Évora",
    "country": "PT",
    "notes": "accented locality Évora, region 7"
  },
  {
    "input": "Praça do Giraldo 50, 7000-508 Évora",
    "number": "50",
    "street": "do Giraldo",
    "type": "Praça",
    "postal_code": "7000-508",
    "city": "Évora",
    "country": "PT",
    "notes": "Praça, Évora"
  },
  {
    "input": "Rua 5 de Outubro 15, 2º Esq, 7000-854 Évora",
    "number": "15",
    "street": "5 de Outubro",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Esq",
    "postal_code": "7000-854",
    "city": "Évora",
    "country": "PT",
    "notes": "date name, floor+side"
  },
  {
    "input": "Rua de Serpa Pinto 22, 7800-241 Beja",
    "number": "22",
    "street": "de Serpa Pinto",
    "type": "Rua",
    "postal_code": "7800-241",
    "city": "Beja",
    "country": "PT",
    "notes": "Rua de, Beja"
  },
  {
    "input": "Avenida Miguel Fernandes 30, 7800-303 Beja",
    "number": "30",
    "street": "Miguel Fernandes",
    "type": "Avenida",
    "postal_code": "7800-303",
    "city": "Beja",
    "country": "PT",
    "notes": "Beja"
  },
  {
    "input": "Rua Direita 5, 5000-661 Vila Real",
    "number": "5",
    "street": "Direita",
    "type": "Rua",
    "postal_code": "5000-661",
    "city": "Vila Real",
    "country": "PT",
    "notes": "region 5, multi-word locality"
  },
  {
    "input": "Avenida Carvalho Araújo 60, 3º, 5000-657 Vila Real",
    "number": "60",
    "street": "Carvalho Araújo",
    "type": "Avenida",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º",
    "postal_code": "5000-657",
    "city": "Vila Real",
    "country": "PT",
    "notes": "accented Araújo, floor"
  },
  {
    "input": "Rua Direita de São Pedro 15, 5300-093 Bragança",
    "number": "15",
    "street": "Direita de São Pedro",
    "type": "Rua",
    "postal_code": "5300-093",
    "city": "Bragança",
    "country": "PT",
    "notes": "accented Bragança, name with de São"
  },
  {
    "input": "Rua Combatentes da Grande Guerra 40, 5300-088 Bragança",
    "number": "40",
    "street": "Combatentes da Grande Guerra",
    "type": "Rua",
    "postal_code": "5300-088",
    "city": "Bragança",
    "country": "PT",
    "notes": "long name"
  },
  {
    "input": "Rua da Sé 3, 2º Dto, 6000-458 Castelo Branco",
    "number": "3",
    "street": "da Sé",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Dto",
    "postal_code": "6000-458",
    "city": "Castelo Branco",
    "country": "PT",
    "notes": "region 6, accented Sé, multi-word locality"
  },
  {
    "input": "Avenida Nuno Álvares 100, 6000-083 Castelo Branco",
    "number": "100",
    "street": "Nuno Álvares",
    "type": "Avenida",
    "postal_code": "6000-083",
    "city": "Castelo Branco",
    "country": "PT",
    "notes": "accented Álvares"
  },
  {
    "input": "Rua Marquês de Pombal 12, 6200-051 Covilhã",
    "number": "12",
    "street": "Marquês de Pombal",
    "type": "Rua",
    "postal_code": "6200-051",
    "city": "Covilhã",
    "country": "PT",
    "notes": "accented Covilhã"
  },
  {
    "input": "Rua Dr. Francisco Sá Carneiro 88, 4470-197 Maia",
    "number": "88",
    "street": "Dr. Francisco Sá Carneiro",
    "type": "Rua",
    "postal_code": "4470-197",
    "city": "Maia",
    "country": "PT",
    "notes": "title Dr. + accented"
  },
  {
    "input": "Rua Central da Gandra 50, R/C, 4585-116 Paredes",
    "number": "50",
    "street": "Central da Gandra",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "R/C",
    "postal_code": "4585-116",
    "city": "Paredes",
    "country": "PT",
    "notes": "ground floor"
  },
  {
    "input": "Praceta das Flores 3, 2º Esq, 2825-410 Costa da Caparica",
    "number": "3",
    "street": "das Flores",
    "type": "Praceta",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º Esq",
    "postal_code": "2825-410",
    "city": "Costa da Caparica",
    "country": "PT",
    "notes": "Praceta, particle das, multi-word locality"
  },
  {
    "input": "Praceta Fernando Pessoa 10, 2745-833 Queluz",
    "number": "10",
    "street": "Fernando Pessoa",
    "type": "Praceta",
    "postal_code": "2745-833",
    "city": "Queluz",
    "country": "PT",
    "notes": "Praceta"
  },
  {
    "input": "Rua da Liberdade 200, 3º Dto, 2795-145 Linda-a-Velha",
    "number": "200",
    "street": "da Liberdade",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "3º Dto",
    "postal_code": "2795-145",
    "city": "Linda-a-Velha",
    "country": "PT",
    "notes": "hyphenated locality, floor+side"
  },
  {
    "input": "Rua Elias Garcia 90, 5º Esq, 2700-327 Amadora",
    "number": "90",
    "street": "Elias Garcia",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "5º Esq",
    "postal_code": "2700-327",
    "city": "Amadora",
    "country": "PT",
    "notes": "floor+side"
  },
  {
    "input": "Avenida Dom João II 45, 1990-095 Lisboa",
    "number": "45",
    "street": "Dom João II",
    "type": "Avenida",
    "postal_code": "1990-095",
    "city": "Lisboa",
    "country": "PT",
    "notes": "roman numeral II in name"
  },
  {
    "input": "Rua Damião de Góis 8, 4050-225 Porto",
    "number": "8",
    "street": "Damião de Góis",
    "type": "Rua",
    "postal_code": "4050-225",
    "city": "Porto",
    "country": "PT",
    "notes": "accented Damião and Góis"
  },
  {
    "input": "Rua Nova do Almada 95, 1200-288 Lisboa",
    "number": "95",
    "street": "Nova do Almada",
    "type": "Rua",
    "postal_code": "1200-288",
    "city": "Lisboa",
    "country": "PT",
    "notes": "multi-word name with do"
  },
  {
    "input": "Rua de Entrecampos 1, 6º Dto, 1000-151 Lisboa",
    "number": "1",
    "street": "de Entrecampos",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "6º Dto",
    "postal_code": "1000-151",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Rua de + high floor+side"
  },
  {
    "input": "Avenida da Igreja 42, 1700-239 Lisboa",
    "number": "42",
    "street": "da Igreja",
    "type": "Avenida",
    "postal_code": "1700-239",
    "city": "Lisboa",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Rua Cidade de Cardiff 12, 4º Esq, 1000-096 Lisboa",
    "number": "12",
    "street": "Cidade de Cardiff",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "4º Esq",
    "postal_code": "1000-096",
    "city": "Lisboa",
    "country": "PT",
    "notes": "name with de, floor+side"
  },
  {
    "input": "Rua do Salitre 118, 1269-065 Lisboa",
    "number": "118",
    "street": "do Salitre",
    "type": "Rua",
    "postal_code": "1269-065",
    "city": "Lisboa",
    "country": "PT",
    "notes": "normal"
  },
  {
    "input": "Calçada de Santana 180, 1150-289 Lisboa",
    "number": "180",
    "street": "de Santana",
    "type": "Calçada",
    "postal_code": "1150-289",
    "city": "Lisboa",
    "country": "PT",
    "notes": "Calçada de"
  },
  {
    "input": "Rua do Norte 90, 2º, 1200-286 Lisboa",
    "number": "90",
    "street": "do Norte",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "2º",
    "postal_code": "1200-286",
    "city": "Lisboa",
    "country": "PT",
    "notes": "floor only"
  },
  {
    "input": "Rua dos Douradores 16, 1100-207 Lisboa",
    "number": "16",
    "street": "dos Douradores",
    "type": "Rua",
    "postal_code": "1100-207",
    "city": "Lisboa",
    "country": "PT",
    "notes": "particle dos"
  },
  {
    "input": "Rua Augusta 25A, 1º Dto, 1100-053 Lisboa",
    "number": "25",
    "civic_number_suffix": "A",
    "street": "Augusta",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Dto",
    "postal_code": "1100-053",
    "city": "Lisboa",
    "country": "PT",
    "notes": "civic suffix + floor+side together"
  },
  {
    "input": "Rua Augusta 100, 1100-053 Lisboa, Portugal",
    "number": "100",
    "street": "Augusta",
    "type": "Rua",
    "postal_code": "1100-053",
    "city": "Lisboa",
    "country": "PT",
    "notes": "explicit Portugal country word"
  },
  {
    "input": "Av. da Liberdade nº 245, 1250-142 Lisboa",
    "number": "245",
    "street": "da Liberdade",
    "type": "Av.",
    "postal_code": "1250-142",
    "city": "Lisboa",
    "country": "PT",
    "notes": "abbrev type + nº marker"
  },
  {
    "input": "R. de Santa Catarina 100, 4000-447 Porto",
    "number": "100",
    "street": "de Santa Catarina",
    "type": "R.",
    "postal_code": "4000-447",
    "city": "Porto",
    "country": "PT",
    "notes": "abbrev R. + Rua de"
  },
  {
    "input": "Estrada Nacional 125 Km 5, 8125-507 Quarteira",
    "__skip": "national road number as street with Km marker",
    "street": "125",
    "type": "Estrada Nacional",
    "sec_unit_num": "Km 5",
    "postal_code": "8125-507",
    "city": "Quarteira",
    "country": "PT",
    "notes": "two-word type Estrada Nacional, road number as name, Km marker"
  },
  {
    "input": "Rua do Comércio 100, 1º Frt, 1100-150 Lisboa",
    "number": "100",
    "street": "do Comércio",
    "type": "Rua",
    "sec_unit_type": "Andar",
    "sec_unit_num": "1º Frt",
    "postal_code": "1100-150",
    "city": "Lisboa",
    "country": "PT",
    "notes": "front side Frt"
  }
];
