// AUTO-GENERATED from research sub-agent corpus (samples-tr.json).
// __skip marks documented out-of-scope address forms.
import type { EuSample } from "./types";

export const trSamples: EuSample[] = [
  {
    "input": "Atatürk Bulvarı No:191 D:5, 06420 Çankaya/Ankara",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "İstiklal Caddesi No:12, 34433 Beyoğlu/İstanbul",
    "number": "12",
    "street": "İstiklal",
    "type": "Caddesi",
    "postal_code": "34433",
    "city": "Beyoğlu",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Bağdat Caddesi No:200 D:3, 34728 Kadıköy/İstanbul",
    "number": "200",
    "street": "Bağdat",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "34728",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Tunalı Hilmi Caddesi No:88 D:12, 06680 Çankaya/Ankara",
    "number": "88",
    "street": "Tunalı Hilmi",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "12",
    "postal_code": "06680",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Cumhuriyet Caddesi No:47, 34367 Şişli/İstanbul",
    "number": "47",
    "street": "Cumhuriyet",
    "type": "Caddesi",
    "postal_code": "34367",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Barbaros Bulvarı No:145 D:8, 34349 Beşiktaş/İstanbul",
    "number": "145",
    "street": "Barbaros",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "8",
    "postal_code": "34349",
    "city": "Beşiktaş",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Gazi Mustafa Kemal Bulvarı No:23, 06570 Çankaya/Ankara",
    "number": "23",
    "street": "Gazi Mustafa Kemal",
    "type": "Bulvarı",
    "postal_code": "06570",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "İnönü Caddesi No:65 D:4, 35220 Konak/İzmir",
    "number": "65",
    "street": "İnönü",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "4",
    "postal_code": "35220",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "Kıbrıs Şehitleri Caddesi No:12, 35210 Konak/İzmir",
    "number": "12",
    "street": "Kıbrıs Şehitleri",
    "type": "Caddesi",
    "postal_code": "35210",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "Abdi İpekçi Caddesi No:8 D:2, 34367 Nişantaşı/İstanbul",
    "number": "8",
    "street": "Abdi İpekçi",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "2",
    "postal_code": "34367",
    "city": "Nişantaşı",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Bağdat Caddesi No:350, 34740 Kadıköy/İstanbul",
    "number": "350",
    "street": "Bağdat",
    "type": "Caddesi",
    "postal_code": "34740",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Fevzi Çakmak Sokak No:5 D:3, 06430 Çankaya/Ankara",
    "number": "5",
    "street": "Fevzi Çakmak",
    "type": "Sokak",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "06430",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Mesa Sokak No:14, 34710 Kadıköy/İstanbul",
    "number": "14",
    "street": "Mesa",
    "type": "Sokak",
    "postal_code": "34710",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Atatürk Caddesi No:100 D:6, 07040 Muratpaşa/Antalya",
    "number": "100",
    "street": "Atatürk",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "6",
    "postal_code": "07040",
    "city": "Muratpaşa",
    "state": "Antalya",
    "country": "TR"
  },
  {
    "input": "Işıklar Caddesi No:22, 07100 Muratpaşa/Antalya",
    "number": "22",
    "street": "Işıklar",
    "type": "Caddesi",
    "postal_code": "07100",
    "city": "Muratpaşa",
    "state": "Antalya",
    "country": "TR"
  },
  {
    "input": "Fatih Sultan Mehmet Caddesi No:9 D:1, 16110 Nilüfer/Bursa",
    "number": "9",
    "street": "Fatih Sultan Mehmet",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "1",
    "postal_code": "16110",
    "city": "Nilüfer",
    "state": "Bursa",
    "country": "TR"
  },
  {
    "input": "Çekirge Caddesi No:55, 16070 Osmangazi/Bursa",
    "number": "55",
    "street": "Çekirge",
    "type": "Caddesi",
    "postal_code": "16070",
    "city": "Osmangazi",
    "state": "Bursa",
    "country": "TR"
  },
  {
    "input": "Ziyapaşa Bulvarı No:33 D:7, 01120 Seyhan/Adana",
    "number": "33",
    "street": "Ziyapaşa",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "7",
    "postal_code": "01120",
    "city": "Seyhan",
    "state": "Adana",
    "country": "TR"
  },
  {
    "input": "Mevlana Caddesi No:18, 42060 Selçuklu/Konya",
    "number": "18",
    "street": "Mevlana",
    "type": "Caddesi",
    "postal_code": "42060",
    "city": "Selçuklu",
    "state": "Konya",
    "country": "TR"
  },
  {
    "input": "Kordon Caddesi No:2 D:10, 35210 Konak/İzmir",
    "number": "2",
    "street": "Kordon",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "10",
    "postal_code": "35210",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "Atatürk Bulvarı No:191/A D:5, 06420 Çankaya/Ankara",
    "number": "191",
    "civic_number_suffix": "A",
    "street": "Atatürk",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "İstiklal Caddesi No:10-12, 34433 Beyoğlu/İstanbul",
    "number": "10-12",
    "street": "İstiklal",
    "type": "Caddesi",
    "postal_code": "34433",
    "city": "Beyoğlu",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "1234. Sokak No:5 D:3, 35530 Bornova/İzmir",
    "number": "5",
    "street": "1234.",
    "type": "Sokak",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "35530",
    "city": "Bornova",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "8. Cadde No:14, 06510 Çankaya/Ankara",
    "number": "14",
    "street": "8.",
    "type": "Cadde",
    "postal_code": "06510",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "100. Yıl Bulvarı No:40 D:2, 06374 Yenimahalle/Ankara",
    "number": "40",
    "street": "100. Yıl",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "2",
    "postal_code": "06374",
    "city": "Yenimahalle",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Atatürk Caddesi Cad. No:12, 34710 Kadıköy/İstanbul",
    "number": "12",
    "street": "Atatürk",
    "type": "Cad.",
    "postal_code": "34710",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Bahariye Sok. No:7 D:4, 34714 Kadıköy/İstanbul",
    "number": "7",
    "street": "Bahariye",
    "type": "Sok.",
    "sec_unit_type": "D",
    "sec_unit_num": "4",
    "postal_code": "34714",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Barbaros Bulv. No:5, 34349 Beşiktaş/İstanbul",
    "number": "5",
    "street": "Barbaros",
    "type": "Bulv.",
    "postal_code": "34349",
    "city": "Beşiktaş",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Cinnah Caddesi No:60 Kat:3 D:7, 06690 Çankaya/Ankara",
    "number": "60",
    "street": "Cinnah",
    "type": "Caddesi",
    "sec_unit_type": "Kat",
    "sec_unit_num": "3",
    "postal_code": "06690",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Halaskargazi Caddesi No:2 D:5, 34371 Şişli/İstanbul",
    "number": "2",
    "street": "Halaskargazi",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "34371",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Vali Konağı Caddesi No:20, 34365 Şişli/İstanbul",
    "number": "20",
    "street": "Vali Konağı",
    "type": "Caddesi",
    "postal_code": "34365",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Nispetiye Caddesi No:19 D:11, 34340 Beşiktaş/İstanbul",
    "number": "19",
    "street": "Nispetiye",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "11",
    "postal_code": "34340",
    "city": "Beşiktaş",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Bağdat Caddesi No:100 A Blok D:3, 34738 Kadıköy/İstanbul",
    "number": "100",
    "street": "Bağdat",
    "type": "Caddesi",
    "sec_unit_type": "Blok",
    "sec_unit_num": "A",
    "postal_code": "34738",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Alsancak Mah., Kıbrıs Şehitleri Caddesi No:12, 35220 Konak/İzmir",
    "number": "12",
    "street": "Kıbrıs Şehitleri",
    "type": "Caddesi",
    "postal_code": "35220",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Kızılay Mah., Atatürk Bulvarı No:191 D:5, 06420 Çankaya/Ankara",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Atatürk Bulvarı No:191 D:5, Kızılay Mah., 06420 Çankaya/Ankara",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Caddebostan Mah., Bağdat Caddesi No:200 D:3, 34728 Kadıköy/İstanbul",
    "number": "200",
    "street": "Bağdat",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "34728",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "İstiklal Caddesi No:12, 34433 İstanbul",
    "number": "12",
    "street": "İstiklal",
    "type": "Caddesi",
    "postal_code": "34433",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Bağdat Caddesi No:200, 34728 İstanbul",
    "number": "200",
    "street": "Bağdat",
    "type": "Caddesi",
    "postal_code": "34728",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Atatürk Bulvarı No:191 D:5, 06420 Çankaya, Ankara",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Atatürk Bulvarı No 191 Kızılay 06420 Çankaya Ankara",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "İstiklal Caddesi No:12, 34433 Beyoğlu/İstanbul, Türkiye",
    "number": "12",
    "street": "İstiklal",
    "type": "Caddesi",
    "postal_code": "34433",
    "city": "Beyoğlu",
    "state": "İstanbul",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Bağdat Caddesi No:200, 34728 Kadıköy/İstanbul, Turkey",
    "number": "200",
    "street": "Bağdat",
    "type": "Caddesi",
    "postal_code": "34728",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Atatürk Bulvarı No:191, 06420 Çankaya/Ankara, TR",
    "number": "191",
    "street": "Atatürk",
    "type": "Bulvarı",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "İnönü Caddesi No:65, 35220 Konak/İzmir, TUR",
    "number": "65",
    "street": "İnönü",
    "type": "Caddesi",
    "postal_code": "35220",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR",
    "__skip": "documented address-form limitation (multi-locality / stacked unit / non-standard order)"
  },
  {
    "input": "Gül Apartmanı, Atatürk Caddesi No:25 D:7, 34180 Bahçelievler/İstanbul",
    "number": "25",
    "building": "Gül Apartmanı",
    "street": "Atatürk",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "7",
    "postal_code": "34180",
    "city": "Bahçelievler",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Yeşil Vadi Sitesi, Cinnah Caddesi No:60 D:3, 06690 Çankaya/Ankara",
    "number": "60",
    "building": "Yeşil Vadi Sitesi",
    "street": "Cinnah",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "06690",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Moda Caddesi No:44 D:2, 34710 Kadıköy/İstanbul",
    "number": "44",
    "street": "Moda",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "2",
    "postal_code": "34710",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Bahariye Caddesi No:56, 34714 Kadıköy/İstanbul",
    "number": "56",
    "street": "Bahariye",
    "type": "Caddesi",
    "postal_code": "34714",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Rumeli Caddesi No:8 D:5, 34371 Şişli/İstanbul",
    "number": "8",
    "street": "Rumeli",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "34371",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Teşvikiye Caddesi No:19, 34365 Şişli/İstanbul",
    "number": "19",
    "street": "Teşvikiye",
    "type": "Caddesi",
    "postal_code": "34365",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Meşrutiyet Caddesi No:98 D:4, 34430 Beyoğlu/İstanbul",
    "number": "98",
    "street": "Meşrutiyet",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "4",
    "postal_code": "34430",
    "city": "Beyoğlu",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Sıraselviler Caddesi No:12, 34433 Beyoğlu/İstanbul",
    "number": "12",
    "street": "Sıraselviler",
    "type": "Caddesi",
    "postal_code": "34433",
    "city": "Beyoğlu",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Ergenekon Caddesi No:75 D:6, 34373 Şişli/İstanbul",
    "number": "75",
    "street": "Ergenekon",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "6",
    "postal_code": "34373",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Büyükdere Caddesi No:255 D:14, 34398 Sarıyer/İstanbul",
    "number": "255",
    "street": "Büyükdere",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "14",
    "postal_code": "34398",
    "city": "Sarıyer",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Büyükdere Caddesi No:127, 34394 Şişli/İstanbul",
    "number": "127",
    "street": "Büyükdere",
    "type": "Caddesi",
    "postal_code": "34394",
    "city": "Şişli",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Eski Büyükdere Caddesi No:9 D:3, 34467 Sarıyer/İstanbul",
    "number": "9",
    "street": "Eski Büyükdere",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "34467",
    "city": "Sarıyer",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Kennedy Caddesi No:30, 34710 Kadıköy/İstanbul",
    "number": "30",
    "street": "Kennedy",
    "type": "Caddesi",
    "postal_code": "34710",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Cemal Gürsel Caddesi No:112 D:8, 35590 Karşıyaka/İzmir",
    "number": "112",
    "street": "Cemal Gürsel",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "8",
    "postal_code": "35590",
    "city": "Karşıyaka",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "Gazi Bulvarı No:5, 35230 Konak/İzmir",
    "number": "5",
    "street": "Gazi",
    "type": "Bulvarı",
    "postal_code": "35230",
    "city": "Konak",
    "state": "İzmir",
    "country": "TR"
  },
  {
    "input": "Mustafa Kemal Caddesi No:66 D:2, 16200 Osmangazi/Bursa",
    "number": "66",
    "street": "Mustafa Kemal",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "2",
    "postal_code": "16200",
    "city": "Osmangazi",
    "state": "Bursa",
    "country": "TR"
  },
  {
    "input": "Yeşilyayla Caddesi No:3, 16130 Nilüfer/Bursa",
    "number": "3",
    "street": "Yeşilyayla",
    "type": "Caddesi",
    "postal_code": "16130",
    "city": "Nilüfer",
    "state": "Bursa",
    "country": "TR"
  },
  {
    "input": "Lara Caddesi No:88 D:9, 07230 Muratpaşa/Antalya",
    "number": "88",
    "street": "Lara",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "9",
    "postal_code": "07230",
    "city": "Muratpaşa",
    "state": "Antalya",
    "country": "TR"
  },
  {
    "input": "Güllük Caddesi No:14, 07050 Muratpaşa/Antalya",
    "number": "14",
    "street": "Güllük",
    "type": "Caddesi",
    "postal_code": "07050",
    "city": "Muratpaşa",
    "state": "Antalya",
    "country": "TR"
  },
  {
    "input": "Kışla Caddesi No:22 D:4, 07040 Muratpaşa/Antalya",
    "number": "22",
    "street": "Kışla",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "4",
    "postal_code": "07040",
    "city": "Muratpaşa",
    "state": "Antalya",
    "country": "TR"
  },
  {
    "input": "Alaaddin Caddesi No:7, 42030 Meram/Konya",
    "number": "7",
    "street": "Alaaddin",
    "type": "Caddesi",
    "postal_code": "42030",
    "city": "Meram",
    "state": "Konya",
    "country": "TR"
  },
  {
    "input": "İsmet Paşa Caddesi No:19 D:3, 42060 Selçuklu/Konya",
    "number": "19",
    "street": "İsmet Paşa",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "42060",
    "city": "Selçuklu",
    "state": "Konya",
    "country": "TR"
  },
  {
    "input": "Turhan Cemal Beriker Bulvarı No:45, 01170 Seyhan/Adana",
    "number": "45",
    "street": "Turhan Cemal Beriker",
    "type": "Bulvarı",
    "postal_code": "01170",
    "city": "Seyhan",
    "state": "Adana",
    "country": "TR"
  },
  {
    "input": "Atatürk Caddesi No:200 D:11, 01060 Çukurova/Adana",
    "number": "200",
    "street": "Atatürk",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "11",
    "postal_code": "01060",
    "city": "Çukurova",
    "state": "Adana",
    "country": "TR"
  },
  {
    "input": "Gazi Mustafa Kemal Bulvarı No:12/B D:3, 06570 Çankaya/Ankara",
    "number": "12",
    "civic_number_suffix": "B",
    "street": "Gazi Mustafa Kemal",
    "type": "Bulvarı",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "06570",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Konur Sokak No:8 D:2, 06420 Çankaya/Ankara",
    "number": "8",
    "street": "Konur",
    "type": "Sokak",
    "sec_unit_type": "D",
    "sec_unit_num": "2",
    "postal_code": "06420",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Selanik Caddesi No:82 D:5, 06650 Çankaya/Ankara",
    "number": "82",
    "street": "Selanik",
    "type": "Caddesi",
    "sec_unit_type": "D",
    "sec_unit_num": "5",
    "postal_code": "06650",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Necatibey Caddesi No:16, 06430 Çankaya/Ankara",
    "number": "16",
    "street": "Necatibey",
    "type": "Caddesi",
    "postal_code": "06430",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Filistin Sokak No:21 D:7, 06700 Çankaya/Ankara",
    "number": "21",
    "street": "Filistin",
    "type": "Sokak",
    "sec_unit_type": "D",
    "sec_unit_num": "7",
    "postal_code": "06700",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Reşat Nuri Sokak No:4, 06540 Çankaya/Ankara",
    "number": "4",
    "street": "Reşat Nuri",
    "type": "Sokak",
    "postal_code": "06540",
    "city": "Çankaya",
    "state": "Ankara",
    "country": "TR"
  },
  {
    "input": "Bağdat Cd. No:200 D:3, 34728 Kadıköy/İstanbul",
    "number": "200",
    "street": "Bağdat",
    "type": "Cd.",
    "sec_unit_type": "D",
    "sec_unit_num": "3",
    "postal_code": "34728",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  },
  {
    "input": "Bahariye Sk. No:7, 34714 Kadıköy/İstanbul",
    "number": "7",
    "street": "Bahariye",
    "type": "Sk.",
    "postal_code": "34714",
    "city": "Kadıköy",
    "state": "İstanbul",
    "country": "TR"
  }
];
