import { AddressTestCaseMap } from "../src/types/address";

export const namedfloorTests: AddressTestCaseMap = {
  "Nine Park avenue 1st Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "9",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "1",
    sec_unit_type: "Floor",
    postal_code: "10022",
    country: "US",
  },
  "1450 Park avenue 11st Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "1450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "11",
    sec_unit_type: "Floor",
    postal_code: "10022",
    country: "US",
  },
  "2450 Park avenue - Floor 2, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "2450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "2",
    sec_unit_type: "Floor",
    postal_code: "10022",
    country: "US",
    __skipTest: true,
  },
  "3450 Park Avenue, 3rd Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "3450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "3",
    sec_unit_type: "Floor",
    postal_code: "10022",
    country: "US",
  },
  "4450 Park Avenue - 4th Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "4450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "4",
    sec_unit_type: "Floor",
    postal_code: "10022",
    country: "US",
  },
};

export const existingTests: AddressTestCaseMap = {
  "1005 Gravenstein Hwy 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy N, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 Gravenstein Highway North, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 N Gravenstein Highway, Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Highway, Suite 500, Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    sec_unit_type: "Suite",
    sec_unit_num: "500",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Hwy Suite 500 Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    sec_unit_type: "Suite",
    sec_unit_num: "500",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Highway, Sebastopol, CA, 95472": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 N Gravenstein Highway Sebastopol CA 95472": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "HY",
    postal_code: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy N Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy N, Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy, N Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "North Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy, North Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "North Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "115 Broadway San Francisco CA": {
    number: "115",
    street: "Broadway",
    city: "San Francisco",
    state: "CA",
    country: "US",
  },
  "7800 Mill Station Rd, Sebastopol, CA 95472": {
    number: "7800",
    street: "Mill Station",
    type: "Rd",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "RD",
    postal_code: "95472",
    country: "US",
  },
  "7800 Mill Station Rd Sebastopol CA 95472": {
    number: "7800",
    street: "Mill Station",
    type: "Rd",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "RD",
    postal_code: "95472",
    country: "US",
  },
  "1005 State Highway 116 Sebastopol CA 95472": {
    number: "1005",
    street: "State Highway 116",
    city: "Sebastopol",
    state: "CA",
    postal_code: "95472",
    country: "US",
  },
  "1600 Pennsylvania Ave. Washington DC": {
    number: "1600",
    street: "Pennsylvania",
    type: "Ave",
    city: "Washington",
    short_street_type: "AV",
    state: "DC",
    country: "US",
  },
  "1600 Pennsylvania Avenue Washington DC": {
    number: "1600",
    street: "Pennsylvania",
    type: "Ave",
    city: "Washington",
    short_street_type: "AV",
    state: "DC",
    country: "US",
  },
  "48S 400E, Salt Lake City UT": {
    number: "48",
    prefix: "S",
    street: "400",
    suffix: "E",
    city: "Salt Lake City",
    state: "UT",
    country: "US",
  },
  "550 S 400 E #3206, Salt Lake City UT 84111": {
    number: "550",
    prefix: "S",
    street: "400",
    suffix: "E",
    sec_unit_type: "#",
    sec_unit_num: "3206",
    city: "Salt Lake City",
    state: "UT",
    postal_code: "84111",
    country: "US",
  },
  "6641 N 2200 W Apt D304 Park City, UT 84098": {
    number: "6641",
    prefix: "N",
    street: "2200",
    suffix: "W",
    sec_unit_type: "Apt",
    sec_unit_num: "D304",
    city: "Park City",
    state: "UT",
    postal_code: "84098",
    country: "US",
  },
  "100 South St, Philadelphia, PA": {
    number: "100",
    street: "South",
    type: "St",
    city: "Philadelphia",
    short_street_type: "ST",
    state: "PA",
    country: "US",
  },
  "100 S.E. Washington Ave, Minneapolis, MN": {
    number: "100",
    prefix: "SE",
    street: "Washington",
    type: "Ave",
    city: "Minneapolis",
    short_street_type: "AV",
    state: "MN",
    country: "US",
  },
  "3813 1/2 Some Road, Los Angeles, CA": {
    number: "3813",
    street: "Some",
    type: "Rd",
    city: "Los Angeles",
    short_street_type: "RD",
    state: "CA",
    country: "US",
  },
  "Mission & Valencia San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    city: "San Francisco",
    state: "CA",
    type2: "",
    type1: "",
    country: "US",
  },
  "Mission & Valencia, San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    city: "San Francisco",
    state: "CA",
    type2: "",
    type1: "",
    country: "US",
  },
  "Mission St and Valencia St San Francisco CA": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission St and Valencia St": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission St & Valencia St San Francisco CA": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission and Valencia Sts San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission & Valencia Sts. San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission and Valencia Sts.": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission & Valencia Streets San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission Avenue and Valencia Street San Francisco CA": {
    street1: "Mission",
    type1: "Ave",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "AV",
    short_street_type2: "ST",
    country: "US",
  },
  "1 First St, e San Jose CA": {
    number: "1",
    street: "First",
    type: "St",
    city: "East San Jose",
    short_street_type: "ST",
    state: "CA",
    country: "US",
  },
  "123 Maple Rochester, New York": {
    number: "123",
    street: "Maple",
    city: "Rochester",
    state: "NY",
    country: "US",
  },
  "233 S Wacker Dr 60606-6306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    postal_code: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr 606066306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    postal_code: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr 60606 6306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    postal_code: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "S Wacker Dr 60606 6306": {
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    postal_code: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr lobby 60606": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    sec_unit_type: "lobby",
    short_street_type: "DR",
    postal_code: "60606",
    country: "US",
  },
  "(233 S Wacker Dr lobby 60606)": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    sec_unit_type: "lobby",
    short_street_type: "DR",
    postal_code: "60606",
    country: "US",
  },
  "#42 233 S Wacker Dr 60606": {
    sec_unit_type: "#",
    sec_unit_num: "42",
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    short_street_type: "DR",
    postal_code: "60606",
    country: "US",
  },
  "lt42 99 Some Road, Some City LA": {
    sec_unit_type: "lt",
    sec_unit_num: "42",
    number: "99",
    street: "Some",
    type: "Rd",
    city: "Some City",
    short_street_type: "RD",
    state: "LA",
    country: "US",
  },
  "36401 County Road 43, Eaton, CO 80615": {
    number: "36401",
    street: "County Road 43",
    city: "Eaton",
    state: "CO",
    postal_code: "80615",
    country: "US",
  },
  "1234 COUNTY HWY 60E, Town, CO 12345": {
    number: "1234",
    street: "COUNTY HWY 60",
    suffix: "E",
    city: "Town",
    state: "CO",
    postal_code: "12345",
    country: "US",
  },
  "321 S. Washington": {
    number: "321",
    prefix: "S",
    street: "Washington",
    country: "US",
  },
  "'45 Quaker Ave, Ste 105'": {
    number: "45",
    street: "Quaker",
    type: "Ave",
    sec_unit_type: "Ste",
    short_street_type: "AV",
    sec_unit_num: "105",
    country: "US",
  },
  "2672 Industrial Row Troy, MI 48084": {
    number: "2672",
    street: "Industrial",
    type: "Row",
    city: "Troy",
    state: "MI",
    short_street_type: "RO",
    postal_code: "48084",
    country: "US",
  },
  "Post office Box 3094 Collierville TN 38027": {
    sec_unit_type: "Post office Box",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    postal_code: "38027",
    country: "US",
  },
  "P.O. box 3094 Collierville TN 38027": {
    sec_unit_type: "PO box",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    postal_code: "38027",
    country: "US",
  },
  "POBox 3094 Collierville TN 38027": {
    sec_unit_type: "POBox",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    postal_code: "38027",
    country: "US",
  },
  "N95W18855 Jay Dr, Menomonee Falls, WI 53051": {
    number: "N95W18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    postal_code: "53051",
    country: "US",
  },
  "N95W18855 Jay Dr Menomonee Falls WI 53051": {
    number: "N95W18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    postal_code: "53051",
    country: "US",
  },
  "n95w18855 Jay Dr Menomonee Falls WI 53051": {
    number: "n95w18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    postal_code: "53051",
    country: "US",
  },
  "10144 Potters Hatch Cmn Cupertino CA 95014": {
    number: "10144",
    street: "Potters Hatch",
    type: "Cmn",
    city: "Cupertino",
    state: "CA",
    short_street_type: "BL",
    postal_code: "95014",
    country: "US",
  },
  "10144 Potters Hatch Common Cupertino CA 95014": {
    number: "10144",
    street: "Potters Hatch",
    type: "Cmn",
    city: "Cupertino",
    state: "CA",
    short_street_type: "BL",
    postal_code: "95014",
    country: "US",
  },
  "36 Hathway Commons Lebanon OH 45036": {
    number: "36",
    street: "Hathway",
    type: "Cmns",
    city: "Lebanon",
    state: "OH",
    short_street_type: "BL",
    postal_code: "45036",
    country: "US",
  },
  "36 Hathway Cmns Lebanon OH 45036": {
    number: "36",
    street: "Hathway",
    type: "Cmns",
    city: "Lebanon",
    state: "OH",
    short_street_type: "BL",
    postal_code: "45036",
    country: "US",
  },
  "174 Sunset Crossroad Deer Isle ME 04627": {
    number: "174",
    street: "Sunset",
    type: "Xrd",
    city: "Deer Isle",
    state: "ME",
    short_street_type: "BL",
    postal_code: "04627",
    country: "US",
  },
  "174 Sunset Xrd Deer Isle ME 04627": {
    number: "174",
    street: "Sunset",
    type: "Xrd",
    city: "Deer Isle",
    state: "ME",
    short_street_type: "BL",
    postal_code: "04627",
    country: "US",
  },
  "905 Laing Crossroads Dawson GA 39842": {
    number: "905",
    street: "Laing",
    type: "Xrds",
    city: "Dawson",
    state: "GA",
    short_street_type: "BL",
    postal_code: "39842",
    country: "US",
  },
  "905 Laing Xrds Dawson GA 39842": {
    number: "905",
    street: "Laing",
    type: "Xrds",
    city: "Dawson",
    state: "GA",
    short_street_type: "BL",
    postal_code: "39842",
    country: "US",
  },
  "9402 Sequoia Fall San Antonio TX 78251": {
    number: "9402",
    street: "Sequoia",
    type: "Fall",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    postal_code: "78251",
    country: "US",
  },
  "24411 Alamosa Fls San Antonio TX 78255": {
    number: "24411",
    street: "Alamosa",
    type: "Falls",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    postal_code: "78255",
    country: "US",
  },
  "24411 Alamosa Falls San Antonio TX 78255": {
    number: "24411",
    street: "Alamosa",
    type: "Falls",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    postal_code: "78255",
    country: "US",
  },
  "15235 Spring Land San Antonio TX 78247": {
    number: "15235",
    street: "Spring",
    type: "Land",
    city: "San Antonio",
    state: "TX",
    short_street_type: "LD",
    postal_code: "78247",
    country: "US",
  },
  "2146 University Square Mall Tampa FL 33612": {
    number: "2146",
    street: "University Square",
    type: "Mall",
    city: "Tampa",
    state: "FL",
    short_street_type: "MA",
    postal_code: "33612",
    country: "US",
  },
  "415 Van Wyck Mews Norfolk VA 23517": {
    number: "415",
    street: "Van Wyck",
    type: "Mews",
    city: "Norfolk",
    state: "VA",
    short_street_type: "BL",
    postal_code: "23517",
    country: "US",
  },
  "22 Cumbres Pass Santa Fe New Mexico 87508": {
    number: "22",
    street: "Cumbres",
    type: "Pass",
    city: "Santa Fe",
    state: "NM",
    short_street_type: "BL",
    postal_code: "87508",
    country: "US",
  },
  "6 Maison Rue Hattiesburg MS 39402": {
    number: "6",
    street: "Maison",
    type: "Rue",
    city: "Hattiesburg",
    state: "MS",
    short_street_type: "RU",
    postal_code: "39402",
    country: "US",
  },
  "12921 Coyote Run Fishers IN 46038": {
    number: "12921",
    street: "Coyote",
    type: "Run",
    city: "Fishers",
    state: "IN",
    short_street_type: "RN",
    postal_code: "46038",
    country: "US",
  },
  "2974 London Wall Bloomfield Hills MI 48304": {
    number: "2974",
    street: "London",
    type: "Wall",
    city: "Bloomfield Hills",
    state: "MI",
    short_street_type: "BL",
    postal_code: "48304",
    country: "US",
  },
  "4349 North Neva Avenue, 123B, Norridge, IL 60706": {
    number: "4349",
    prefix: "N",
    street: "Neva",
    sec_unit_type: "123B",
    type: "Ave",
    city: "Norridge",
    state: "IL",
    postal_code: "60706",
    country: "US",
    __skipTest: true,
  },
  "4972 SW 91st Aven, Cooper City, FL 33328, USA": {
    city: "Cooper City",
    state: "FL",
    number: "4972",
    prefix: "SW",
    street: "91st",
    type: "Ave",
    short_street_type: "AV",
    postal_code: "33328",
    country: "US",
  },
  "925 SW 102ND TE, Pembroke Pines, FL 33025, USA": {
    city: "Pembroke Pines",
    state: "FL",
    number: "925",
    prefix: "SW",
    street: "102ND",
    type: "Ter",
    short_street_type: "TE",
    postal_code: "33025",
    country: "US",
  },
  "42 Wallaby Way, Sidney, TX 76442": {
    city: "Sidney",
    state: "TX",
    number: "42",
    street: "Wallaby",
    type: "Way",
    short_street_type: "WY",
    postal_code: "76442",
    country: "US",
  },
  "1120 S Lamar Blvd, Austin, TX 78704": {
    city: "Austin",
    state: "TX",
    number: "1120",
    prefix: "S",
    street: "Lamar",
    type: "Blvd",
    short_street_type: "BV",
    postal_code: "78704",
    country: "US",
  },
};

// from https://github.com/euphonie/parse-address/blob/master/test/test.js
export const canadianAddresses: AddressTestCaseMap = {
  "8483 San Pablo Street Gloucester, ON K1B 1L8": {
    number: "8483",
    street: "San Pablo",
    type: "St",
    short_street_type: "ST",
    city: "Gloucester",
    province: "ON",
    fsa: "K1B",
    ldu: "1L8",
    postal_code: "K1B 1L8",
    country: "CA",
  },
  "19 Miller Rd. Keswick, ON L4P 1L1": {
    number: "19",
    street: "Miller",
    type: "Rd",
    short_street_type: "RD",
    city: "Keswick",
    province: "ON",
    fsa: "L4P",
    ldu: "1L1",
    postal_code: "L4P 1L1",
    country: "CA",
  },
  "177 Corona Street Mont-Joli, QC G5H 2Y5": {
    number: "177",
    street: "Corona",
    type: "St",
    short_street_type: "ST",
    city: "Mont-Joli",
    province: "QC",
    fsa: "G5H",
    ldu: "2Y5",
    postal_code: "G5H 2Y5",
    country: "CA",
  },
  "68 N Gonzales Lane Vancouver, BC V5K 5A8": {
    number: "68",
    prefix: "N",
    street: "Gonzales",
    type: "Ln",
    short_street_type: "LN",
    city: "Vancouver",
    province: "BC",
    fsa: "V5K",
    ldu: "5A8",
    postal_code: "V5K 5A8",
    country: "CA",
  },
  // Test apparent multiple street types
  // place + st
  "19 Errol place St. John's NL A1A 5H6": {
    number: "19",
    street: "Errol",
    type: "Pl",
    short_street_type: "PL",
    city: "St. John's",
    province: "NL",
    fsa: "A1A",
    ldu: "5H6",
    postal_code: "A1A 5H6",
    country: "CA",
  },
  // station + rue
  "1325 Takahana station Rue Paris AB T5T 1E5": {
    number: "1325",
    street: "Takahana",
    type: "Sta",
    short_street_type: "SA",
    city: "Rue Paris",
    province: "AB",
    fsa: "T5T",
    ldu: "1E5",
    postal_code: "T5T 1E5",
    country: "CA",
  },
  "14205 96 Ave NW NW Edmonton AB T5N 0C2": {
    number: "14205",
    street: "96",
    type: "Ave",
    short_street_type: "AV",
    suffix: "NW",
    city: "Northwest Edmonton",
    province: "AB",
    fsa: "T5N",
    ldu: "0C2",
    postal_code: "T5N 0C2",
    country: "CA",
  },
  "1 Argyle St. L'Île-Des-Soeurs, QC H3E 5T5": {
    number: "1",
    street: "Argyle",
    type: "St",
    short_street_type: "ST",
    city: "L'Île-Des-Soeurs",
    province: "QC",
    fsa: "H3E",
    ldu: "5T5",
    postal_code: "H3E 5T5",
    country: "CA",
  },
  "10-123 1/2 main st nw Montréal, QC H3Z 2Y7": {
    number: "10-123",
    civic_number_suffix: "1/2",
    street: "main",
    type: "St",
    short_street_type: "ST",
    suffix: "NW",
    city: "Montréal",
    province: "QC",
    fsa: "H3Z",
    ldu: "2Y7",
    postal_code: "H3Z 2Y7",
    country: "CA",
  },
  "64 Cumberland Cres St. John's NL A1B 3M5": {
    number: "64",
    street: "Cumberland",
    type: "Cres",
    short_street_type: "CR",
    city: "St. John's",
    province: "NL",
    fsa: "A1B",
    ldu: "3M5",
    postal_code: "A1B 3M5",
    country: "CA",
  },
  
};

export const canadianTestCases: AddressTestCaseMap = {
  // Basic Canadian addresses with provinces and postal codes
  "123 Main Street, Toronto, ON M5V 3A8": {
    number: "123",
    street: "Main",
    type: "St",
    short_street_type: "ST",
    city: "Toronto",
    province: "ON",
    fsa: "M5V",
    ldu: "3A8",
    postal_code: "M5V 3A8",
    country: "CA",
  },
  "456 Elm Avenue, Vancouver, BC V6B 1A1": {
    number: "456",
    street: "Elm",
    type: "Ave",
    short_street_type: "AV",
    city: "Vancouver",
    province: "BC",
    fsa: "V6B",
    ldu: "1A1",
    postal_code: "V6B 1A1",
    country: "CA",
  },
  "789 Oak Drive, Calgary, AB T2P 2M5": {
    number: "789",
    street: "Oak",
    type: "Dr",
    short_street_type: "DR",
    city: "Calgary",
    province: "AB",
    fsa: "T2P",
    ldu: "2M5",
    postal_code: "T2P 2M5",
    country: "CA",
  },
  "1001 Pine Road, Winnipeg, MB R3C 0V8": {
    number: "1001",
    street: "Pine",
    type: "Rd",
    short_street_type: "RD",
    city: "Winnipeg",
    province: "MB",
    fsa: "R3C",
    ldu: "0V8",
    postal_code: "R3C 0V8",
    country: "CA",
  },

  // French street types (Quebec)
  "234 Rue Saint-Denis, Montréal, QC H2X 3L4": {
    number: "234",
    street: "Saint-Denis",
    type: "Rue",
    short_street_type: "RUE",
    city: "Montréal",
    province: "QC",
    fsa: "H2X",
    ldu: "3L4",
    postal_code: "H2X 3L4",
    country: "CA",
  },
  "567 Boulevard René-Lévesque, Québec, QC G1R 2B5": {
    number: "567",
    street: "René-Lévesque",
    type: "Blvd",
    short_street_type: "BV",
    city: "Québec",
    province: "QC",
    fsa: "G1R",
    ldu: "2B5",
    postal_code: "G1R 2B5",
    country: "CA",
  },
  "890 Chemin de la Côte-des-Neiges, Montréal, QC H3S 1Z1": {
    number: "890",
    street: "de la Côte-des-Neiges",
    type: "Ch",
    short_street_type: "CHE",
    city: "Montréal",
    province: "QC",
    fsa: "H3S",
    ldu: "1Z1",
    postal_code: "H3S 1Z1",
    country: "CA",
  },
  "123 Avenue du Parc, Montréal, QC H2W 2M4": {
    number: "123",
    street: "du Parc",
    type: "Ave",
    short_street_type: "AV",
    city: "Montréal",
    province: "QC",
    fsa: "H2W",
    ldu: "2M4",
    postal_code: "H2W 2M4",
    country: "CA",
  },

  // Directional prefixes and suffixes
  "1500 N Main Street, Ottawa, ON K1A 0A6": {
    number: "1500",
    prefix: "N",
    street: "Main",
    type: "St",
    short_street_type: "ST",
    city: "Ottawa",
    province: "ON",
    fsa: "K1A",
    ldu: "0A6",
    postal_code: "K1A 0A6",
    country: "CA",
  },
  "2000 King Street E, Hamilton, ON L8N 3C4": {
    number: "2000",
    street: "King",
    type: "St",
    suffix: "E",
    short_street_type: "ST",
    city: "Hamilton",
    province: "ON",
    fsa: "L8N",
    ldu: "3C4",
    postal_code: "L8N 3C4",
    country: "CA",
  },
  "300 SW Marine Drive, Vancouver, BC V5X 2R6": {
    number: "300",
    prefix: "SW",
    street: "Marine",
    type: "Dr",
    short_street_type: "DR",
    city: "Vancouver",
    province: "BC",
    fsa: "V5X",
    ldu: "2R6",
    postal_code: "V5X 2R6",
    country: "CA",
  },

  // Unit/apartment numbers
  "1234 Yonge Street, Apt 567, Toronto, ON M4T 1W5": {
    number: "1234",
    street: "Yonge",
    type: "St",
    short_street_type: "ST",
    sec_unit_type: "Apt",
    sec_unit_num: "567",
    city: "Toronto",
    province: "ON",
    fsa: "M4T",
    ldu: "1W5",
    postal_code: "M4T 1W5",
    country: "CA",
  },
  "5678 Robson Street, Suite 890, Vancouver, BC V6E 1A2": {
    number: "5678",
    street: "Robson",
    type: "St",
    short_street_type: "ST",
    sec_unit_type: "Suite",
    sec_unit_num: "890",
    city: "Vancouver",
    province: "BC",
    fsa: "V6E",
    ldu: "1A2",
    postal_code: "V6E 1A2",
    country: "CA",
  },
  "#101 999 Seymour Street, Vancouver, BC V6B 3M1": {
    sec_unit_type: "#",
    sec_unit_num: "101",
    number: "999",
    street: "Seymour",
    type: "St",
    short_street_type: "ST",
    city: "Vancouver",
    province: "BC",
    fsa: "V6B",
    ldu: "3M1",
    postal_code: "V6B 3M1",
    country: "CA",
  },

  // Canadian-specific street types
  "456 Maple Crescent, Regina, SK S4P 3Y2": {
    number: "456",
    street: "Maple",
    type: "Cres",
    short_street_type: "CR",
    city: "Regina",
    province: "SK",
    fsa: "S4P",
    ldu: "3Y2",
    postal_code: "S4P 3Y2",
    country: "CA",
  },
  "789 Birch Close, Edmonton, AB T5K 1M7": {
    number: "789",
    street: "Birch",
    type: "Close",
    short_street_type: "CL",
    city: "Edmonton",
    province: "AB",
    fsa: "T5K",
    ldu: "1M7",
    postal_code: "T5K 1M7",
    country: "CA",
  },
  "1010 Heritage Gate, Calgary, AB T2Z 3R4": {
    number: "1010",
    street: "Heritage",
    type: "Gate",
    short_street_type: "GT",
    city: "Calgary",
    province: "AB",
    fsa: "T2Z",
    ldu: "3R4",
    postal_code: "T2Z 3R4",
    country: "CA",
  },
  "2020 University Mews, Halifax, NS B3H 4R2": {
    number: "2020",
    street: "University",
    type: "Mews",
    short_street_type: "MW",
    city: "Halifax",
    province: "NS",
    fsa: "B3H",
    ldu: "4R2",
    postal_code: "B3H 4R2",
    country: "CA",
  },

  // All Canadian provinces and territories
  "100 Atlantic Avenue, St. John's, NL A1C 5T7": {
    number: "100",
    street: "Atlantic",
    type: "Ave",
    short_street_type: "AV",
    city: "St. John's",
    province: "NL",
    fsa: "A1C",
    ldu: "5T7",
    postal_code: "A1C 5T7",
    country: "CA",
  },
  "200 Prince Street, Charlottetown, PE C1A 4N6": {
    number: "200",
    street: "Prince",
    type: "St",
    short_street_type: "ST",
    city: "Charlottetown",
    province: "PE",
    fsa: "C1A",
    ldu: "4N6",
    postal_code: "C1A 4N6",
    country: "CA",
  },
  "300 Spring Garden Road, Halifax, NS B3J 3R7": {
    number: "300",
    street: "Spring Garden",
    type: "Rd",
    short_street_type: "RD",
    city: "Halifax",
    province: "NS",
    fsa: "B3J",
    ldu: "3R7",
    postal_code: "B3J 3R7",
    country: "CA",
  },
  "400 King Street, Fredericton, NB E3B 1E5": {
    number: "400",
    street: "King",
    type: "St",
    short_street_type: "ST",
    city: "Fredericton",
    province: "NB",
    fsa: "E3B",
    ldu: "1E5",
    postal_code: "E3B 1E5",
    country: "CA",
  },
  "500 Franklin Avenue, Yellowknife, NT X1A 2N1": {
    number: "500",
    street: "Franklin",
    type: "Ave",
    short_street_type: "AV",
    city: "Yellowknife",
    province: "NT",
    fsa: "X1A",
    ldu: "2N1",
    postal_code: "X1A 2N1",
    country: "CA",
  },
  "600 Federal Road, Iqaluit, NU X0A 0H0": {
    number: "600",
    street: "Federal",
    type: "Rd",
    short_street_type: "RD",
    city: "Iqaluit",
    province: "NU",
    fsa: "X0A",
    ldu: "0H0",
    postal_code: "X0A 0H0",
    country: "CA",
  },
  "700 Main Street, Whitehorse, YT Y1A 2A5": {
    number: "700",
    street: "Main",
    type: "St",
    short_street_type: "ST",
    city: "Whitehorse",
    province: "YT",
    fsa: "Y1A",
    ldu: "2A5",
    postal_code: "Y1A 2A5",
    country: "CA",
  },

  // Postal codes without spaces (should be normalized)
  "1111 Jasper Avenue, Edmonton, AB T5J0R2": {
    number: "1111",
    street: "Jasper",
    type: "Ave",
    short_street_type: "AV",
    city: "Edmonton",
    province: "AB",
    fsa: "T5J",
    ldu: "0R2",
    postal_code: "T5J 0R2",
    country: "CA",
  },

  // Mixed case postal codes (should be normalized to uppercase)
  "2222 Granville Street, Vancouver, BC v6h3v9": {
    number: "2222",
    street: "Granville",
    type: "St",
    short_street_type: "ST",
    city: "Vancouver",
    province: "BC",
    fsa: "V6H",
    ldu: "3V9",
    postal_code: "V6H 3V9",
    country: "CA",
  },

  // Rural route addresses
  "RR 1, Box 123, Smiths Falls, ON K7A 4S4": {
    sec_unit_type: "RR",
    sec_unit_num: "1",
    street: "Box",
    country: "CA",
  },

  // Highway addresses
  "12345 Highway 401, Kingston, ON K7L 5H6": {
    number: "12345",
    street: "401",
    type: "Hwy",
    short_street_type: "HW",
    city: "Kingston",
    province: "ON",
    fsa: "K7L",
    ldu: "5H6",
    postal_code: "K7L 5H6",
    country: "CA",
  },
  "6789 Trans-Canada Highway, Kamloops, BC V2C 2A8": {
    number: "6789",
    street: "Trans-Canada",
    type: "Hwy",
    short_street_type: "HW",
    city: "Kamloops",
    province: "BC",
    fsa: "V2C",
    ldu: "2A8",
    postal_code: "V2C 2A8",
    country: "CA",
  },

  // Intersection addresses
  "Yonge Street and Bloor Street, Toronto, ON": {
    street1: "Yonge",
    type1: "St",
    street2: "Bloor",
    type2: "St",
    city: "Toronto",
    province: "ON",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "CA",
  },
  "Robson St & Granville St, Vancouver, BC": {
    street1: "Robson",
    type1: "St",
    street2: "Granville", 
    type2: "St",
    city: "Vancouver",
    province: "BC",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "CA",
  },

  // Addresses without postal codes
  "888 Water Street, St. John's, NL": {
    number: "888",
    street: "Water",
    type: "St",
    short_street_type: "ST",
    city: "St. John's",
    province: "NL",
    country: "CA",
  },
  "999 Portage Avenue, Winnipeg, MB": {
    number: "999",
    street: "Portage",
    type: "Ave",
    short_street_type: "AV",
    city: "Winnipeg",
    province: "MB",
    country: "CA",
  },

  // French addresses with accents
  "456 Rue Sainte-Catherine Est, Montréal, QC H2L 2C1": {
    number: "456",
    street: "Sainte-Catherine",
    type: "Rue",
    suffix: "E",
    short_street_type: "RUE",
    city: "Montréal",
    province: "QC",
    fsa: "H2L",
    ldu: "2C1",
    postal_code: "H2L 2C1",
    country: "CA",
  },
  "789 Avenue des Pins, Montréal, QC H2W 1P5": {
    number: "789",
    street: "des Pins",
    type: "Ave",
    short_street_type: "AV",
    city: "Montréal",
    province: "QC",
    fsa: "H2W",
    ldu: "1P5",
    postal_code: "H2W 1P5",
    country: "CA",
  },

  // Concession road addresses (rural Ontario)
  "1234 Concession Road 5, Guelph, ON N1H 6J1": {
    number: "1234",
    street: "Road 5",
    type: "Conc",
    short_street_type: "CO",
    city: "Guelph",
    province: "ON",
    fsa: "N1H",
    ldu: "6J1",
    postal_code: "N1H 6J1",
    country: "CA",
  },

  // Line addresses (rural Ontario)
  "5678 Line 42, Orangeville, ON L9W 2Z2": {
    number: "5678",
    street: "42",
    type: "Line",
    short_street_type: "LI",
    city: "Orangeville",
    province: "ON",
    fsa: "L9W",
    ldu: "2Z2",
    postal_code: "L9W 2Z2",
    country: "CA",
  },
};
