import { AddressTestCaseMap } from "../src/types/address";

export const namedfloorTests: AddressTestCaseMap = {
  "One Park avenue 1st Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "1",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "1",
    sec_unit_type: "Floor",
    zip: "10022",
    country: "US",
  },
  "1450 Park avenue 11st Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "1450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "11",
    sec_unit_type: "Floor",
    zip: "10022",
    country: "US",
  },
  "2450 Park avenue - Floor 2, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "2450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "2",
    sec_unit_type: "Floor",
    zip: "10022",
    country: "US",
    __skipTest: true,
  },
  "3450 Park Avenue, 3rd Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "3450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "3",
    sec_unit_type: "Floor",
    zip: "10022",
    country: "US",
  },
  "4450 Park Avenue - 4th Floor, New York, NY 10022": {
    city: "New York",
    state: "NY",
    number: "4450",
    street: "Park",
    type: "Ave",
    short_street_type: "AV",
    sec_unit_num: "4",
    sec_unit_type: "Floor",
    zip: "10022",
    country: "US",
  },
};

export const existingTests: AddressTestCaseMap = {
  "1005 Gravenstein Hwy 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy N, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 Gravenstein Highway North, 95472": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 N Gravenstein Highway, Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Highway, Suite 500, Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    sec_unit_type: "Suite",
    sec_unit_num: "500",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Hwy Suite 500 Sebastopol, CA": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    sec_unit_type: "Suite",
    sec_unit_num: "500",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 N Gravenstein Highway, Sebastopol, CA, 95472": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 N Gravenstein Highway Sebastopol CA 95472": {
    number: "1005",
    prefix: "N",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "HY",
    zip: "95472",
    country: "US",
  },
  "1005 Gravenstein Hwy N Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy N, Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    suffix: "N",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy, N Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "North Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy, North Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "North Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "1005 Gravenstein Hwy Sebastopol CA": {
    number: "1005",
    street: "Gravenstein",
    type: "Hwy",
    city: "Sebastopol",
    short_street_type: "HY",
    state: "CA",
    country: "US",
  },
  "115 Broadway San Francisco CA": {
    number: "115",
    street: "Broadway",
    city: "San Francisco",
    state: "CA",
    country: "US",
  },
  "7800 Mill Station Rd, Sebastopol, CA 95472": {
    number: "7800",
    street: "Mill Station",
    type: "Rd",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "RD",
    zip: "95472",
    country: "US",
  },
  "7800 Mill Station Rd Sebastopol CA 95472": {
    number: "7800",
    street: "Mill Station",
    type: "Rd",
    city: "Sebastopol",
    state: "CA",
    short_street_type: "RD",
    zip: "95472",
    country: "US",
  },
  "1005 State Highway 116 Sebastopol CA 95472": {
    number: "1005",
    street: "State Highway 116",
    city: "Sebastopol",
    state: "CA",
    zip: "95472",
    country: "US",
  },
  "1600 Pennsylvania Ave. Washington DC": {
    number: "1600",
    street: "Pennsylvania",
    type: "Ave",
    city: "Washington",
    short_street_type: "AV",
    state: "DC",
    country: "US",
  },
  "1600 Pennsylvania Avenue Washington DC": {
    number: "1600",
    street: "Pennsylvania",
    type: "Ave",
    city: "Washington",
    short_street_type: "AV",
    state: "DC",
    country: "US",
  },
  "48S 400E, Salt Lake City UT": {
    number: "48",
    prefix: "S",
    street: "400",
    suffix: "E",
    city: "Salt Lake City",
    state: "UT",
    country: "US",
  },
  "550 S 400 E #3206, Salt Lake City UT 84111": {
    number: "550",
    prefix: "S",
    street: "400",
    suffix: "E",
    sec_unit_type: "#",
    sec_unit_num: "3206",
    city: "Salt Lake City",
    state: "UT",
    zip: "84111",
    country: "US",
  },
  "6641 N 2200 W Apt D304 Park City, UT 84098": {
    number: "6641",
    prefix: "N",
    street: "2200",
    suffix: "W",
    sec_unit_type: "Apt",
    sec_unit_num: "D304",
    city: "Park City",
    state: "UT",
    zip: "84098",
    country: "US",
  },
  "100 South St, Philadelphia, PA": {
    number: "100",
    street: "South",
    type: "St",
    city: "Philadelphia",
    short_street_type: "ST",
    state: "PA",
    country: "US",
  },
  "100 S.E. Washington Ave, Minneapolis, MN": {
    number: "100",
    prefix: "SE",
    street: "Washington",
    type: "Ave",
    city: "Minneapolis",
    short_street_type: "AV",
    state: "MN",
    country: "US",
  },
  "3813 1/2 Some Road, Los Angeles, CA": {
    number: "3813",
    street: "Some",
    type: "Rd",
    city: "Los Angeles",
    short_street_type: "RD",
    state: "CA",
    country: "US",
  },
  "Mission & Valencia San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    city: "San Francisco",
    state: "CA",
    type2: "",
    type1: "",
    country: "US",
  },
  "Mission & Valencia, San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    city: "San Francisco",
    state: "CA",
    type2: "",
    type1: "",
    country: "US",
  },
  "Mission St and Valencia St San Francisco CA": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission St and Valencia St": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission St & Valencia St San Francisco CA": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission and Valencia Sts San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission & Valencia Sts. San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission and Valencia Sts.": {
    street1: "Mission",
    type1: "St",
    street2: "Valencia",
    type2: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission & Valencia Streets San Francisco CA": {
    street1: "Mission",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    type1: "St",
    short_street_type1: "ST",
    short_street_type2: "ST",
    country: "US",
  },
  "Mission Avenue and Valencia Street San Francisco CA": {
    street1: "Mission",
    type1: "Ave",
    street2: "Valencia",
    type2: "St",
    city: "San Francisco",
    state: "CA",
    short_street_type1: "AV",
    short_street_type2: "ST",
    country: "US",
  },
  "1 First St, e San Jose CA": {
    number: "1",
    street: "First",
    type: "St",
    city: "East San Jose",
    short_street_type: "ST",
    state: "CA",
    country: "US",
  },
  "123 Maple Rochester, New York": {
    number: "123",
    street: "Maple",
    city: "Rochester",
    state: "NY",
    country: "US",
  },
  "233 S Wacker Dr 60606-6306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    zip: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr 606066306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    zip: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr 60606 6306": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    zip: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "S Wacker Dr 60606 6306": {
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    zip: "60606",
    short_street_type: "DR",
    plus4: "6306",
    country: "US",
  },
  "233 S Wacker Dr lobby 60606": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    sec_unit_type: "lobby",
    short_street_type: "DR",
    zip: "60606",
    country: "US",
  },
  "(233 S Wacker Dr lobby 60606)": {
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    sec_unit_type: "lobby",
    short_street_type: "DR",
    zip: "60606",
    country: "US",
  },
  "#42 233 S Wacker Dr 60606": {
    sec_unit_type: "#",
    sec_unit_num: "42",
    number: "233",
    prefix: "S",
    street: "Wacker",
    type: "Dr",
    short_street_type: "DR",
    zip: "60606",
    country: "US",
  },
  "lt42 99 Some Road, Some City LA": {
    sec_unit_type: "lt",
    sec_unit_num: "42",
    number: "99",
    street: "Some",
    type: "Rd",
    city: "Some City",
    short_street_type: "RD",
    state: "LA",
    country: "US",
  },
  "36401 County Road 43, Eaton, CO 80615": {
    number: "36401",
    street: "County Road 43",
    city: "Eaton",
    state: "CO",
    zip: "80615",
    country: "US",
  },
  "1234 COUNTY HWY 60E, Town, CO 12345": {
    number: "1234",
    street: "COUNTY HWY 60",
    suffix: "E",
    city: "Town",
    state: "CO",
    zip: "12345",
    country: "US",
  },
  "321 S. Washington": {
    number: "321",
    prefix: "S",
    street: "Washington",
    country: "US",
  },
  "'45 Quaker Ave, Ste 105'": {
    number: "45",
    street: "Quaker",
    type: "Ave",
    sec_unit_type: "Ste",
    short_street_type: "AV",
    sec_unit_num: "105",
    country: "US",
  },
  "2672 Industrial Row Troy, MI 48084": {
    number: "2672",
    street: "Industrial",
    type: "Row",
    city: "Troy",
    state: "MI",
    short_street_type: "RO",
    zip: "48084",
    country: "US",
  },
  "Post office Box 3094 Collierville TN 38027": {
    sec_unit_type: "Post office Box",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    zip: "38027",
    country: "US",
  },
  "P.O. box 3094 Collierville TN 38027": {
    sec_unit_type: "PO box",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    zip: "38027",
    country: "US",
  },
  "POBox 3094 Collierville TN 38027": {
    sec_unit_type: "POBox",
    sec_unit_num: "3094",
    city: "Collierville",
    state: "TN",
    zip: "38027",
    country: "US",
  },
  "N95W18855 Jay Dr, Menomonee Falls, WI 53051": {
    number: "N95W18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    zip: "53051",
    country: "US",
  },
  "N95W18855 Jay Dr Menomonee Falls WI 53051": {
    number: "N95W18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    zip: "53051",
    country: "US",
  },
  "n95w18855 Jay Dr Menomonee Falls WI 53051": {
    number: "n95w18855",
    street: "Jay",
    type: "Dr",
    city: "Menomonee Falls",
    state: "WI",
    short_street_type: "DR",
    zip: "53051",
    country: "US",
  },
  "10144 Potters Hatch Cmn Cupertino CA 95014": {
    number: "10144",
    street: "Potters Hatch",
    type: "Cmn",
    city: "Cupertino",
    state: "CA",
    short_street_type: "BL",
    zip: "95014",
    country: "US",
  },
  "10144 Potters Hatch Common Cupertino CA 95014": {
    number: "10144",
    street: "Potters Hatch",
    type: "Cmn",
    city: "Cupertino",
    state: "CA",
    short_street_type: "BL",
    zip: "95014",
    country: "US",
  },
  "36 Hathway Commons Lebanon OH 45036": {
    number: "36",
    street: "Hathway",
    type: "Cmns",
    city: "Lebanon",
    state: "OH",
    short_street_type: "BL",
    zip: "45036",
    country: "US",
  },
  "36 Hathway Cmns Lebanon OH 45036": {
    number: "36",
    street: "Hathway",
    type: "Cmns",
    city: "Lebanon",
    state: "OH",
    short_street_type: "BL",
    zip: "45036",
    country: "US",
  },
  "174 Sunset Crossroad Deer Isle ME 04627": {
    number: "174",
    street: "Sunset",
    type: "Xrd",
    city: "Deer Isle",
    state: "ME",
    short_street_type: "BL",
    zip: "04627",
    country: "US",
  },
  "174 Sunset Xrd Deer Isle ME 04627": {
    number: "174",
    street: "Sunset",
    type: "Xrd",
    city: "Deer Isle",
    state: "ME",
    short_street_type: "BL",
    zip: "04627",
    country: "US",
  },
  "905 Laing Crossroads Dawson GA 39842": {
    number: "905",
    street: "Laing",
    type: "Xrds",
    city: "Dawson",
    state: "GA",
    short_street_type: "BL",
    zip: "39842",
    country: "US",
  },
  "905 Laing Xrds Dawson GA 39842": {
    number: "905",
    street: "Laing",
    type: "Xrds",
    city: "Dawson",
    state: "GA",
    short_street_type: "BL",
    zip: "39842",
    country: "US",
  },
  "9402 Sequoia Fall San Antonio TX 78251": {
    number: "9402",
    street: "Sequoia",
    type: "Fall",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    zip: "78251",
    country: "US",
  },
  "24411 Alamosa Fls San Antonio TX 78255": {
    number: "24411",
    street: "Alamosa",
    type: "Falls",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    zip: "78255",
    country: "US",
  },
  "24411 Alamosa Falls San Antonio TX 78255": {
    number: "24411",
    street: "Alamosa",
    type: "Falls",
    city: "San Antonio",
    state: "TX",
    short_street_type: "FA",
    zip: "78255",
    country: "US",
  },
  "15235 Spring Land San Antonio TX 78247": {
    number: "15235",
    street: "Spring",
    type: "Land",
    city: "San Antonio",
    state: "TX",
    short_street_type: "LD",
    zip: "78247",
    country: "US",
  },
  "2146 University Square Mall Tampa FL 33612": {
    number: "2146",
    street: "University Square",
    type: "Mall",
    city: "Tampa",
    state: "FL",
    short_street_type: "MA",
    zip: "33612",
    country: "US",
  },
  "415 Van Wyck Mews Norfolk VA 23517": {
    number: "415",
    street: "Van Wyck",
    type: "Mews",
    city: "Norfolk",
    state: "VA",
    short_street_type: "BL",
    zip: "23517",
    country: "US",
  },
  "22 Cumbres Pass Santa Fe New Mexico 87508": {
    number: "22",
    street: "Cumbres",
    type: "Pass",
    city: "Santa Fe",
    state: "NM",
    short_street_type: "BL",
    zip: "87508",
    country: "US",
  },
  "6 Maison Rue Hattiesburg MS 39402": {
    number: "6",
    street: "Maison",
    type: "Rue",
    city: "Hattiesburg",
    state: "MS",
    short_street_type: "RU",
    zip: "39402",
    country: "US",
  },
  "12921 Coyote Run Fishers IN 46038": {
    number: "12921",
    street: "Coyote",
    type: "Run",
    city: "Fishers",
    state: "IN",
    short_street_type: "RN",
    zip: "46038",
    country: "US",
  },
  "2974 London Wall Bloomfield Hills MI 48304": {
    number: "2974",
    street: "London",
    type: "Wall",
    city: "Bloomfield Hills",
    state: "MI",
    short_street_type: "BL",
    zip: "48304",
    country: "US",
  },
};

// from https://github.com/euphonie/parse-address/blob/master/test/test.js
export const canadianAddresses = {
  "8483 San Pablo Street Gloucester, ON K1B 1L8": {
    unit_number: "8483",
    street: "San Pablo",
    type: "St",
    city: "Gloucester",
    state: "ON",
    fsa: "K1B",
    ldu: "1L8",
    country: "US",
  },
  "19 Miller Rd. Keswick, ON L4P 1L1": {
    unit_number: "19",
    street: "Miller",
    type: "Rd",
    city: "Keswick",
    state: "ON",
    fsa: "L4P",
    ldu: "1L1",
    country: "US",
  },
  "177 Corona Street Mont-Joli, QC G5H 2Y5": {
    unit_number: "177",
    street: "Corona",
    type: "St",
    city: "Mont-Joli",
    state: "QC",
    fsa: "G5H",
    ldu: "2Y5",
    country: "US",
  },
  "68 N Gonzales Lane Vancouver, BC V5K 5A8": {
    unit_number: "68",
    prefix: "N",
    street: "Gonzales",
    type: "Lane",
    city: "Vancouver",
    state: "BC",
    fsa: "V5K",
    ldu: "5A8",
    country: "US",
  },
  // Test apparent multiple street types
  // place + st
  "19 Errol place St. John's NL A1A 5H6": {
    unit_number: "19",
    street: "Errol",
    type: "Pl",
    city: "St. John's",
    state: "NL",
    fsa: "A1A",
    ldu: "5H6",
    country: "US",
  },
  // station + rue
  "1325 Takahana station Rue Paris AB T5T 1E5": {
    unit_number: "1325",
    street: "Takahana",
    type: "Sta",
    city: "Rue Paris",
    state: "AB",
    fsa: "T5T",
    ldu: "1E5",
    country: "US",
  },
  "14205 96 Ave NW NW Edmonton AB T5N 0C2": {
    unit_number: "14205",
    street: "96",
    type: "Ave",
    suffix: "NW",
    city: "Northwest Edmonton",
    state: "AB",
    fsa: "T5N",
    ldu: "0C2",
    country: "US",
  },
  "1 Argyle St. L'Île-Des-Soeurs, QC H3E 5T5": {
    unit_number: "1",
    street: "Argyle",
    type: "St",
    city: "L'Île-Des-Soeurs",
    state: "QC",
    fsa: "H3E",
    ldu: "5T5",
    country: "US",
  },
  "10-123 1/2 main st nw Montréal, QC H3Z 2Y7": {
    unit_number: "10-123",
    civic_number_suffix: "1/2",
    street: "main",
    type: "St",
    suffix: "nw",
    city: "Montréal",
    state: "QC",
    fsa: "H3Z",
    ldu: "2Y7",
    country: "US",
  },
  "64 Cumberland Cres St. John's NL A1B 3M5": {
    unit_number: "64",
    street: "Cumberland",
    type: "Cres",
    city: "St. John's",
    state: "NL",
    fsa: "A1B",
    ldu: "3M5",
    country: "US",
  },
  "4349 North Neva Avenue, 123B, Norridge, IL 60706": {
    number: "4349",
    prefix: "N",
    street: "Neva",
    sec_unit_type: "123B",
    type: "Ave",
    city: "Norridge",
    state: "IL",
    zip: "60706",
    country: "US",
    __skipTest: true,
  },
  "4972 SW 91st Aven, Cooper City, FL 33328, USA": {
    city: "Cooper City",
    state: "FL",
    number: "4972",
    prefix: "SW",
    street: "91st",
    type: "Ave",
    short_street_type: "AV",
    zip: "33328",
    country: "US",
  },
  "925 SW 102ND TE, Pembroke Pines, FL 33025, USA": {
    city: "Pembroke Pines",
    state: "FL",
    number: "925",
    prefix: "SW",
    street: "102ND",
    type: "Ter",
    short_street_type: "TE",
    zip: "33025",
    country: "US",
  },
  "42 Wallaby Way, Sidney, TX 76442": {
    city: "Sidney",
    state: "TX",
    number: "42",
    street: "Wallaby",
    type: "Way",
    short_street_type: "WY",
    zip: "76442",
    country: "US",
  },
  "1120 S Lamar Blvd, Austin, TX 78704": {
    city: "Austin",
    state: "TX",
    number: "1120",
    prefix: "S",
    street: "Lamar",
    type: "Blvd",
    short_street_type: "BV",
    zip: "78704",
    country: "US",
  },
};
